// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/anthropic/messages.hpp"
#include "../../../interface/protocols/anthropic/messages_strings.hpp"
#include "base.hpp"
#include "../../curl.hpp"

namespace jai::llm {

BEGIN_DESERIALIZE(anthropic::Message::Container)
    FIELD(src, id),
    FIELD(src, expires_at)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::Usage::CacheCreation)
    FIELD(src, ephemeral_1h_input_tokens),
    FIELD(src, ephemeral_5m_input_tokens)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::Usage::ServerToolUsage)
    FIELD(src, web_fetch_requests),
    FIELD(src, web_search_requests)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::Usage)
    FIELD(src, cache_creation),
    FIELD(src, cache_creation_input_tokens),
    FIELD(src, cache_read_input_tokens),
    FIELD(src, inference_geo),
    FIELD(src, input_tokens),
    FIELD(src, output_tokens),
    FIELD(src, server_tool_use),
    FIELD(src, service_tier)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock::CitationCharLocation)
    FIELD(src, cited_text),
    FIELD(src, document_index),
    FIELD(src, document_title),
    FIELD(src, end_char_index),
    FIELD(src, file_id),
    FIELD(src, start_char_index),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock::CitationPageLocation)
    FIELD(src, cited_text),
    FIELD(src, document_index),
    FIELD(src, document_title),
    FIELD(src, end_page_number),
    FIELD(src, file_id),
    FIELD(src, start_page_number),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock::CitationContentBlockLocation)
    FIELD(src, cited_text),
    FIELD(src, document_index),
    FIELD(src, document_title),
    FIELD(src, end_block_index),
    FIELD(src, file_id),
    FIELD(src, start_block_index),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock::CitationsWebSearchResultLocation)
    FIELD(src, cited_text),
    FIELD(src, encrypted_index),
    FIELD(src, title),
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock::CitationsSearchResultLocation)
    FIELD(src, cited_text),
    FIELD(src, end_block_index),
    FIELD(src, search_result_index),
    FIELD(src, source),
    FIELD(src, start_block_index),
    FIELD(src, title),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextBlock)
    FIELD(src, citations),
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ThinkingBlock)
    FIELD(src, signature),
    FIELD(src, thinking),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::RedactedThinkingBlock)
    FIELD(src, data),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolUseBlock::DirectCaller)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolUseBlock::ServerToolCaller)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolUseBlock::ServerToolCaller20260120)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolUseBlock)
    FIELD(src, id),
    FIELD(src, caller),
    FIELD(src, input),
    FIELD(src, name),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ServerToolUseBlock::DirectCaller)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ServerToolUseBlock::ServerToolCaller)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ServerToolUseBlock::ServerToolCaller20260120)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ServerToolUseBlock)
    FIELD(src, id),
    FIELD(src, caller),
    FIELD(src, input),
    FIELD(src, name),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock::DirectCaller)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock::ServerToolCaller)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock::ServerToolCaller20260120)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultError)
    FIELD(src, error_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock::WebSearchResultBlock)
    FIELD(src, encrypted_content),
    FIELD(src, page_age),
    FIELD(src, title),
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebSearchToolResultBlock)
    FIELD(src, caller),
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::DirectCaller)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::ServerToolCaller)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::ServerToolCaller20260120)
    FIELD(src, tool_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchToolResultErrorBlock)
    FIELD(src, error_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::CitationsConfig)
    FIELD(src, enabled)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::Base64PDFSource)
    FIELD(src, data),
    FIELD(src, media_type),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::PlainTextSource)
    FIELD(src, data),
    FIELD(src, media_type),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock)
    FIELD(src, citations),
    FIELD(src, source),
    FIELD(src, title),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock)
    FIELD(src, content),
    FIELD(src, retrieved_at),
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::WebFetchToolResultBlock)
    FIELD(src, caller),
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultError)
    FIELD(src, error_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionResultBlock::CodeExecutionOutputBlock)
    FIELD(src, file_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionResultBlock)
    FIELD(src, content),
    FIELD(src, return_code),
    FIELD_ALT(src, stderr_, "stderr"),
    FIELD_ALT(src, stdout_, "stdout"),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock::EncryptedCodeExecutionResultBlock::CodeExecutionOutputBlock)
    FIELD(src, file_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock::EncryptedCodeExecutionResultBlock)
    FIELD(src, content),
    FIELD(src, encrypted_stdout),
    FIELD(src, return_code),
    FIELD_ALT(src, stderr_, "stderr"),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::CodeExecutionToolResultBlock)
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::BashCodeExecutionToolResultBlock::BashCodeExecutionToolResultError)
    FIELD(src, error_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::BashCodeExecutionToolResultBlock::BashCodeExecutionResultBlock::BashCodeExecutionOutputBlock)
    FIELD(src, file_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::BashCodeExecutionToolResultBlock::BashCodeExecutionResultBlock)
    FIELD(src, content),
    FIELD(src, return_code),
    FIELD_ALT(src, stderr_, "stderr"),
    FIELD_ALT(src, stdout_, "stdout"),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::BashCodeExecutionToolResultBlock)
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionToolResultError)
    FIELD(src, error_code),
    FIELD(src, error_message),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionViewResultBlock)
    FIELD(src, content),
    FIELD(src, file_type),
    FIELD(src, num_lines),
    FIELD(src, start_line),
    FIELD(src, total_lines),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionCreateResultBlock)
    FIELD(src, is_file_update),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionStrReplaceResultBlock)
    FIELD(src, lines),
    FIELD(src, new_lines),
    FIELD(src, new_start),
    FIELD(src, old_lines),
    FIELD(src, old_start),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::TextEditorCodeExecutionToolResultBlock)
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolSearchToolResultBlock::ToolSearchToolResultError)
    FIELD(src, error_code),
    FIELD(src, error_message),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolSearchToolResultBlock::ToolSearchToolSearchResultBlock::ToolReferenceBlock)
    FIELD(src, tool_name),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolSearchToolResultBlock::ToolSearchToolSearchResultBlock)
    FIELD(src, tool_references),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ToolSearchToolResultBlock)
    FIELD(src, content),
    FIELD(src, tool_use_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message::ContainerUploadBlock)
    FIELD(src, file_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(anthropic::Message)
    FIELD(src, id),
    FIELD(src, container),
    FIELD(src, content),
    FIELD(src, model),
    FIELD(src, role),
    FIELD(src, stop_reason),
    FIELD(src, stop_sequence),
    FIELD(src, type),
    FIELD(src, usage)
END_DESERIALIZE

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::TextBlock::TextCitation)
    auto kind = EXTRACT_KIND(anthropic::Message::TextBlock::TextCitationKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::TextBlock::TextCitationKind::CHAR_LOCATION, anthropic::Message::TextBlock::CitationCharLocation)
    FIELD_KIND(src, kind, anthropic::Message::TextBlock::TextCitationKind::PAGE_LOCATION, anthropic::Message::TextBlock::CitationPageLocation)
    FIELD_KIND(src, kind, anthropic::Message::TextBlock::TextCitationKind::CONTENT_BLOCK_LOCATION, anthropic::Message::TextBlock::CitationContentBlockLocation)
    FIELD_KIND(src, kind, anthropic::Message::TextBlock::TextCitationKind::WEB_SEARCH_RESULT_LOCATION, anthropic::Message::TextBlock::CitationsWebSearchResultLocation)
    FIELD_KIND(src, kind, anthropic::Message::TextBlock::TextCitationKind::SEARCH_RESULT_LOCATION, anthropic::Message::TextBlock::CitationsSearchResultLocation)
END_DESERIALIZE_VARIANT(anthropic::Message::TextBlock::TextCitation)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::ToolUseBlock::Caller)
    auto kind = EXTRACT_KIND(anthropic::Message::ToolUseBlock::CallerKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::ToolUseBlock::CallerKind::DIRECT, anthropic::Message::ToolUseBlock::DirectCaller)
    FIELD_KIND(src, kind, anthropic::Message::ToolUseBlock::CallerKind::CODE_EXECUTION_20250825, anthropic::Message::ToolUseBlock::ServerToolCaller)
    FIELD_KIND(src, kind, anthropic::Message::ToolUseBlock::CallerKind::CODE_EXECUTION_20260120, anthropic::Message::ToolUseBlock::ServerToolCaller20260120)
END_DESERIALIZE_VARIANT(anthropic::Message::ToolUseBlock::Caller)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::ServerToolUseBlock::Caller)
    auto kind = EXTRACT_KIND(anthropic::Message::ServerToolUseBlock::CallerKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::ServerToolUseBlock::CallerKind::DIRECT, anthropic::Message::ServerToolUseBlock::DirectCaller)
    FIELD_KIND(src, kind, anthropic::Message::ServerToolUseBlock::CallerKind::CODE_EXECUTION_20250825, anthropic::Message::ServerToolUseBlock::ServerToolCaller)
    FIELD_KIND(src, kind, anthropic::Message::ServerToolUseBlock::CallerKind::CODE_EXECUTION_20260120, anthropic::Message::ServerToolUseBlock::ServerToolCaller20260120)
END_DESERIALIZE_VARIANT(anthropic::Message::ServerToolUseBlock::Caller)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::WebSearchToolResultBlock::Caller)
    auto kind = EXTRACT_KIND(anthropic::Message::WebSearchToolResultBlock::CallerKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::WebSearchToolResultBlock::CallerKind::DIRECT, anthropic::Message::WebSearchToolResultBlock::DirectCaller)
    FIELD_KIND(src, kind, anthropic::Message::WebSearchToolResultBlock::CallerKind::CODE_EXECUTION_20250825, anthropic::Message::WebSearchToolResultBlock::ServerToolCaller)
    FIELD_KIND(src, kind, anthropic::Message::WebSearchToolResultBlock::CallerKind::CODE_EXECUTION_20260120, anthropic::Message::WebSearchToolResultBlock::ServerToolCaller20260120)
END_DESERIALIZE_VARIANT(anthropic::Message::WebSearchToolResultBlock::Caller)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultBlockContent)
    if (src.is_array()) {
        return T{DeserializeTo<std::vector<anthropic::Message::WebSearchToolResultBlock::WebSearchResultBlock>>(src)};
    }
    auto kind = EXTRACT_KIND(anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultBlockContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultBlockContentKind::WEB_SEARCH_TOOL_RESULT_ERROR, anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultError)
END_DESERIALIZE_VARIANT(anthropic::Message::WebSearchToolResultBlock::WebSearchToolResultBlockContent)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::Source)
    auto kind = EXTRACT_KIND(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::SourceKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::SourceKind::BASE64, anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::Base64PDFSource)
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::SourceKind::TEXT, anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::PlainTextSource)
END_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::WebFetchBlock::DocumentBlock::Source)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::Caller)
    auto kind = EXTRACT_KIND(anthropic::Message::WebFetchToolResultBlock::CallerKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::CallerKind::DIRECT, anthropic::Message::WebFetchToolResultBlock::DirectCaller)
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::CallerKind::CODE_EXECUTION_20250825, anthropic::Message::WebFetchToolResultBlock::ServerToolCaller)
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::CallerKind::CODE_EXECUTION_20260120, anthropic::Message::WebFetchToolResultBlock::ServerToolCaller20260120)
END_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::Caller)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::Content)
    auto kind = EXTRACT_KIND(anthropic::Message::WebFetchToolResultBlock::ContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::ContentKind::WEB_FETCH_TOOL_RESULT_ERROR, anthropic::Message::WebFetchToolResultBlock::WebFetchToolResultErrorBlock)
    FIELD_KIND(src, kind, anthropic::Message::WebFetchToolResultBlock::ContentKind::WEB_FETCH_RESULT, anthropic::Message::WebFetchToolResultBlock::WebFetchBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::WebFetchToolResultBlock::Content)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContent)
    auto kind = EXTRACT_KIND(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContentKind::CODE_EXECUTION_TOOL_RESULT_ERROR, anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultError)
    FIELD_KIND(src, kind, anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContentKind::CODE_EXECUTION_RESULT, anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContentKind::ENCRYPTED_CODE_EXECUTION_RESULT, anthropic::Message::CodeExecutionToolResultBlock::EncryptedCodeExecutionResultBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::CodeExecutionToolResultBlock::CodeExecutionToolResultBlockContent)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::BashCodeExecutionToolResultBlock::Content)
    auto kind = EXTRACT_KIND(anthropic::Message::BashCodeExecutionToolResultBlock::ContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::BashCodeExecutionToolResultBlock::ContentKind::BASH_CODE_EXECUTION_TOOL_RESULT_ERROR, anthropic::Message::BashCodeExecutionToolResultBlock::BashCodeExecutionToolResultError)
    FIELD_KIND(src, kind, anthropic::Message::BashCodeExecutionToolResultBlock::ContentKind::BASH_CODE_EXECUTION_RESULT, anthropic::Message::BashCodeExecutionToolResultBlock::BashCodeExecutionResultBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::BashCodeExecutionToolResultBlock::Content)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::TextEditorCodeExecutionToolResultBlock::Content)
    auto kind = EXTRACT_KIND(anthropic::Message::TextEditorCodeExecutionToolResultBlock::ContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::TextEditorCodeExecutionToolResultBlock::ContentKind::TEXT_EDITOR_CODE_EXECUTION_TOOL_RESULT_ERROR, anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionToolResultError)
    FIELD_KIND(src, kind, anthropic::Message::TextEditorCodeExecutionToolResultBlock::ContentKind::TEXT_EDITOR_CODE_EXECUTION_VIEW_RESULT, anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionViewResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::TextEditorCodeExecutionToolResultBlock::ContentKind::TEXT_EDITOR_CODE_EXECUTION_CREATE_RESULT, anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionCreateResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::TextEditorCodeExecutionToolResultBlock::ContentKind::TEXT_EDITOR_CODE_EXECUTION_STR_REPLACE_RESULT, anthropic::Message::TextEditorCodeExecutionToolResultBlock::TextEditorCodeExecutionStrReplaceResultBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::TextEditorCodeExecutionToolResultBlock::Content)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::ToolSearchToolResultBlock::Content)
    auto kind = EXTRACT_KIND(anthropic::Message::ToolSearchToolResultBlock::ContentKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::ToolSearchToolResultBlock::ContentKind::TOOL_SEARCH_TOOL_RESULT_ERROR, anthropic::Message::ToolSearchToolResultBlock::ToolSearchToolResultError)
    FIELD_KIND(src, kind, anthropic::Message::ToolSearchToolResultBlock::ContentKind::TOOL_SEARCH_TOOL_SEARCH_RESULT, anthropic::Message::ToolSearchToolResultBlock::ToolSearchToolSearchResultBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::ToolSearchToolResultBlock::Content)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::ContentBlock)
    auto kind = EXTRACT_KIND(anthropic::Message::ContentBlockKind, src, "type");
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::TEXT, anthropic::Message::TextBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::THINKING, anthropic::Message::ThinkingBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::REDACTED_THINKING, anthropic::Message::RedactedThinkingBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::TOOL_USE, anthropic::Message::ToolUseBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::SERVER_TOOL_USE, anthropic::Message::ServerToolUseBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::WEB_SEARCH_TOOL_RESULT, anthropic::Message::WebSearchToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::WEB_FETCH_TOOL_RESULT, anthropic::Message::WebFetchToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::CODE_EXECUTION_TOOL_RESULT, anthropic::Message::CodeExecutionToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::BASH_CODE_EXECUTION_TOOL_RESULT, anthropic::Message::BashCodeExecutionToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::TEXT_EDITOR_CODE_EXECUTION_TOOL_RESULT, anthropic::Message::TextEditorCodeExecutionToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::TOOL_SEARCH_TOOL_RESULT, anthropic::Message::ToolSearchToolResultBlock)
    FIELD_KIND(src, kind, anthropic::Message::ContentBlockKind::CONTAINER_UPLOAD, anthropic::Message::ContainerUploadBlock)
END_DESERIALIZE_VARIANT(anthropic::Message::ContentBlock)

BEGIN_DESERIALIZE_VARIANT(anthropic::Message::Model)
    if (src.is_string()) {
        return T{DeserializeTo<anthropic::Message::ModelValues>(src)};
    }
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
END_DESERIALIZE_VARIANT(anthropic::Message::Model)

/***
 * Top-level Deserialize
 */
namespace anthropic {
    Message Deserialize(const curl::Response& response) {
        if (response.body.size() < response.body_len + simdjson::SIMDJSON_PADDING) {
            throw AnnotatedException{"Simdjson padding check failed"};
        }

        static thread_local simdjson::dom::parser parser{};

        try {
            simdjson::dom::element doc = parser.parse(
                reinterpret_cast<const char*>(response.body.data()), response.body_len);
            return DeserializeTo<Message>(doc);
        } catch (const simdjson::simdjson_error& e) {
            throw AnnotatedException{"anthropic::Deserialize Failed", e.what()};
        }
    }
}

} // namespace jai::llm
