// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/gemini/generate_content.hpp"
#include "../../../interface/protocols/gemini/generate_content_strings.hpp"
#include "base.hpp"
#include "../../curl.hpp"

namespace jai::llm {

BEGIN_DESERIALIZE(gemini::Blob)
    FIELD(src, mimeType),
    FIELD(src, data)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::CitationSource)
    FIELD(src, startIndex),
    FIELD(src, endIndex),
    FIELD(src, uri),
    FIELD(src, license)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::CodeExecutionResult)
    FIELD(src, outcome),
    FIELD(src, output)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::ExecutableCode)
    FIELD(src, language),
    FIELD(src, code)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::FileData)
    FIELD(src, mimeType),
    FIELD(src, fileUri)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::FunctionCall)
    FIELD(src, id),
    FIELD(src, name),
    FIELD(src, args)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::FunctionResponseBlob)
    FIELD(src, mimeType),
    FIELD(src, data)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GoogleAiGenerativelanguageV1betaSegment)
    FIELD(src, partIndex),
    FIELD(src, startIndex),
    FIELD(src, endIndex),
    FIELD(src, text)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GroundingPassageId)
    FIELD(src, passageId),
    FIELD(src, partIndex)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Image)
    FIELD(src, sourceUri),
    FIELD(src, imageUri),
    FIELD(src, title),
    FIELD(src, domain)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::LogprobsResultCandidate)
    FIELD(src, token),
    FIELD(src, tokenId),
    FIELD(src, logProbability)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::ModalityTokenCount)
    FIELD(src, modality),
    FIELD(src, tokenCount)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::ModelStatus)
    FIELD(src, modelStage),
    FIELD(src, retirementTime),
    FIELD(src, message)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::RetrievalMetadata)
    FIELD(src, googleSearchDynamicRetrievalScore)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::RetrievedContext)
    FIELD(src, uri),
    FIELD(src, title),
    FIELD(src, text),
    FIELD(src, fileSearchStore)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::ReviewSnippet)
    FIELD(src, reviewId),
    FIELD(src, googleMapsUri),
    FIELD(src, title)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::SafetyRating)
    FIELD(src, category),
    FIELD(src, probability),
    FIELD(src, blocked)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::SearchEntryPoint)
    FIELD(src, renderedContent),
    FIELD(src, sdkBlob)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::SemanticRetrieverChunk)
    FIELD(src, source),
    FIELD(src, chunk)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::UrlMetadata)
    FIELD(src, retrievedUrl),
    FIELD(src, urlRetrievalStatus)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Web)
    FIELD(src, uri),
    FIELD(src, title)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::CitationMetadata)
    FIELD(src, citationSources)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::FunctionResponsePart)
    FIELD(src, inlineData)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GoogleAiGenerativelanguageV1betaGroundingSupport)
    FIELD(src, segment),
    FIELD(src, groundingChunkIndices),
    FIELD(src, confidenceScores)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::TopCandidates)
    FIELD(src, candidates)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::UsageMetadata)
    FIELD(src, promptTokenCount),
    FIELD(src, cachedContentTokenCount),
    FIELD(src, candidatesTokenCount),
    FIELD(src, toolUsePromptTokenCount),
    FIELD(src, thoughtsTokenCount),
    FIELD(src, totalTokenCount),
    FIELD(src, promptTokensDetails),
    FIELD(src, cacheTokensDetails),
    FIELD(src, candidatesTokensDetails),
    FIELD(src, toolUsePromptTokensDetails)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::PlaceAnswerSources)
    FIELD(src, reviewSnippets)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::PromptFeedback)
    FIELD(src, blockReason),
    FIELD(src, safetyRatings)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::AttributionSourceId)
    FIELD(src, groundingPassage),
    FIELD(src, semanticRetrieverChunk)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::UrlContextMetadata)
    FIELD(src, urlMetadata)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::FunctionResponse)
    FIELD(src, id),
    FIELD(src, name),
    FIELD(src, response),
    FIELD(src, parts),
    FIELD(src, willContinue),
    FIELD(src, scheduling)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::LogprobsResult)
    FIELD(src, logProbabilitySum),
    FIELD(src, topCandidates),
    FIELD(src, chosenCandidates)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Maps)
    FIELD(src, uri),
    FIELD(src, title),
    FIELD(src, text),
    FIELD(src, placeId),
    FIELD(src, placeAnswerSources)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Part)
    FIELD(src, text),
    FIELD(src, inlineData),
    FIELD(src, functionCall),
    FIELD(src, functionResponse),
    FIELD(src, fileData),
    FIELD(src, executableCode),
    FIELD(src, codeExecutionResult),
    FIELD(src, thought),
    FIELD(src, thoughtSignature),
    FIELD(src, partMetadata),
    FIELD(src, mediaResolution)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GroundingChunk)
    FIELD(src, web),
    FIELD(src, image),
    FIELD(src, retrievedContext),
    FIELD(src, maps)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Content)
    FIELD(src, parts),
    FIELD(src, role)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GroundingMetadata)
    FIELD(src, searchEntryPoint),
    FIELD(src, groundingChunks),
    FIELD(src, groundingSupports),
    FIELD(src, retrievalMetadata),
    FIELD(src, webSearchQueries),
    FIELD(src, imageSearchQueries),
    FIELD(src, googleMapsWidgetContextToken)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GroundingAttribution)
    FIELD(src, sourceId),
    FIELD(src, content)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::Candidate)
    FIELD(src, index),
    FIELD(src, content),
    FIELD(src, finishReason),
    FIELD(src, finishMessage),
    FIELD(src, safetyRatings),
    FIELD(src, citationMetadata),
    FIELD(src, tokenCount),
    FIELD(src, groundingAttributions),
    FIELD(src, groundingMetadata),
    FIELD(src, avgLogprobs),
    FIELD(src, logprobsResult),
    FIELD(src, urlContextMetadata)
END_DESERIALIZE

BEGIN_DESERIALIZE(gemini::GenerateContentResponse)
    FIELD(src, candidates),
    FIELD(src, promptFeedback),
    FIELD(src, usageMetadata),
    FIELD(src, modelVersion),
    FIELD(src, responseId),
    FIELD(src, modelStatus)
END_DESERIALIZE

/***
 * Top-level Deserialize
 */
namespace gemini {
    Response Deserialize(const curl::Response& response) {
        if (response.body.size() < response.body_len + simdjson::SIMDJSON_PADDING) {
            throw AnnotatedException{"Simdjson padding check failed"};
        }

        static thread_local simdjson::dom::parser parser{};

        try {
            simdjson::dom::element doc = parser.parse(
                reinterpret_cast<const char*>(response.body.data()), response.body_len);
            return DeserializeTo<Response>(doc);
        } catch (const simdjson::simdjson_error& e) {
            throw AnnotatedException{"gemini::Deserialize Failed", e.what()};
        }
    }
}

} // namespace jai::llm
