// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/openai/responses.hpp"
#include "../../../interface/protocols/openai/responses_strings.hpp"
#include "base.hpp"
#include "../../curl.hpp"

namespace jai::llm {

BEGIN_DESERIALIZE(openai::Response::ResponseError)
    FIELD(src, code),
    FIELD(src, message)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Response_incomplete_details)
    FIELD(src, reason)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::EasyInputMessage::ResponseInputText)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::EasyInputMessage::ResponseInputImage)
    FIELD(src, detail),
    FIELD(src, type),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::EasyInputMessage::ResponseInputFile)
    FIELD(src, type),
    FIELD(src, file_data),
    FIELD(src, file_id),
    FIELD(src, file_url),
    FIELD(src, filename)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::EasyInputMessage)
    FIELD(src, content),
    FIELD(src, role),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Message::ResponseInputText)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Message::ResponseInputImage)
    FIELD(src, detail),
    FIELD(src, type),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Message::ResponseInputFile)
    FIELD(src, type),
    FIELD(src, file_data),
    FIELD(src, file_id),
    FIELD(src, file_url),
    FIELD(src, filename)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Message)
    FIELD(src, content),
    FIELD(src, role),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::FileCitation)
    FIELD(src, file_id),
    FIELD(src, filename),
    FIELD(src, index),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::URLCitation)
    FIELD(src, end_index),
    FIELD(src, start_index),
    FIELD(src, title),
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::ContainerFileCitation)
    FIELD(src, container_id),
    FIELD(src, end_index),
    FIELD(src, file_id),
    FIELD(src, filename),
    FIELD(src, start_index),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::FilePath)
    FIELD(src, file_id),
    FIELD(src, index),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::ResponseOutputText_logprobs::ResponseOutputText_logprobs_top_logprobs)
    FIELD(src, token),
    FIELD(src, bytes),
    FIELD(src, logprob)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText::ResponseOutputText_logprobs)
    FIELD(src, token),
    FIELD(src, bytes),
    FIELD(src, logprob),
    FIELD(src, top_logprobs)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputText)
    FIELD(src, annotations),
    FIELD(src, logprobs),
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage::ResponseOutputRefusal)
    FIELD(src, refusal),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseOutputMessage)
    FIELD(src, id),
    FIELD(src, content),
    FIELD(src, role),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFileSearchToolCall::ResponseFileSearchToolCall_results)
    FIELD(src, attributes),
    FIELD(src, file_id),
    FIELD(src, filename),
    FIELD(src, score),
    FIELD(src, text)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFileSearchToolCall)
    FIELD(src, id),
    FIELD(src, queries),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, results)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Click)
    FIELD(src, button),
    FIELD(src, type),
    FIELD(src, x),
    FIELD(src, y)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::DoubleClick)
    FIELD(src, type),
    FIELD(src, x),
    FIELD(src, y)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Drag::Drag_path)
    FIELD(src, x),
    FIELD(src, y)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Drag)
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Keypress)
    FIELD(src, keys),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Move)
    FIELD(src, type),
    FIELD(src, x),
    FIELD(src, y)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Screenshot)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Scroll)
    FIELD(src, scroll_x),
    FIELD(src, scroll_y),
    FIELD(src, type),
    FIELD(src, x),
    FIELD(src, y)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Type)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::Wait)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall::ResponseComputerToolCall_pending_safety_checks)
    FIELD(src, id),
    FIELD(src, code),
    FIELD(src, message)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseComputerToolCall)
    FIELD(src, id),
    FIELD(src, action),
    FIELD(src, call_id),
    FIELD(src, pending_safety_checks),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ComputerCallOutput::ResponseComputerToolCallOutputScreenshot)
    FIELD(src, type),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ComputerCallOutput::ComputerCallOutput_acknowledged_safety_checks)
    FIELD(src, id),
    FIELD(src, code),
    FIELD(src, message)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ComputerCallOutput)
    FIELD(src, call_id),
    FIELD(src, output),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, acknowledged_safety_checks),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionWebSearch::Search::Search_sources)
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionWebSearch::Search)
    FIELD(src, query),
    FIELD(src, type),
    FIELD(src, queries),
    FIELD(src, sources)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionWebSearch::OpenPage)
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionWebSearch::FindInPage)
    FIELD(src, pattern),
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionWebSearch)
    FIELD(src, id),
    FIELD(src, action),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionToolCall)
    FIELD(src, arguments),
    FIELD(src, call_id),
    FIELD(src, name),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionCallOutput::ResponseInputTextContent)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionCallOutput::ResponseInputImageContent)
    FIELD(src, type),
    FIELD(src, detail),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionCallOutput::ResponseInputFileContent)
    FIELD(src, type),
    FIELD(src, file_data),
    FIELD(src, file_id),
    FIELD(src, file_url),
    FIELD(src, filename)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionCallOutput)
    FIELD(src, call_id),
    FIELD(src, output),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseReasoningItem::SummaryTextContent)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseReasoningItem::ResponseReasoningItem_content)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseReasoningItem)
    FIELD(src, id),
    FIELD(src, summary),
    FIELD(src, type),
    FIELD(src, content),
    FIELD(src, encrypted_content),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCompactionItemParam)
    FIELD(src, encrypted_content),
    FIELD(src, type),
    FIELD(src, id)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ImageGenerationCall)
    FIELD(src, id),
    FIELD(src, result),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCodeInterpreterToolCall::Logs)
    FIELD(src, logs),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCodeInterpreterToolCall::Image)
    FIELD(src, type),
    FIELD(src, url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCodeInterpreterToolCall)
    FIELD(src, id),
    FIELD(src, code),
    FIELD(src, container_id),
    FIELD(src, outputs),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::LocalShellCall::LocalShellCall_action)
    FIELD(src, command),
    FIELD(src, env),
    FIELD(src, type),
    FIELD(src, timeout_ms),
    FIELD(src, user),
    FIELD(src, working_directory)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::LocalShellCall)
    FIELD(src, id),
    FIELD(src, action),
    FIELD(src, call_id),
    FIELD(src, status),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::LocalShellCallOutput)
    FIELD(src, id),
    FIELD(src, output),
    FIELD(src, type),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCall::ShellCall_action)
    FIELD(src, commands),
    FIELD(src, max_output_length),
    FIELD(src, timeout_ms)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCall::LocalEnvironment::LocalSkill)
    FIELD(src, description),
    FIELD(src, name),
    FIELD(src, path)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCall::LocalEnvironment)
    FIELD(src, type),
    FIELD(src, skills)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCall::ContainerReference)
    FIELD(src, container_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCall)
    FIELD(src, action),
    FIELD(src, call_id),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, environment),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Timeout)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Exit)
    FIELD(src, exit_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent)
    FIELD(src, outcome),
    FIELD_ALT(src, stderr_, "stderr"),
    FIELD_ALT(src, stdout_, "stdout")
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ShellCallOutput)
    FIELD(src, call_id),
    FIELD(src, output),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, max_output_length),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchCall::CreateFile)
    FIELD(src, diff),
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchCall::DeleteFile)
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchCall::UpdateFile)
    FIELD(src, diff),
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchCall)
    FIELD(src, call_id),
    FIELD(src, operation),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, id)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchCallOutput)
    FIELD(src, call_id),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, output)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::McpListTools::McpListTools_tools)
    FIELD(src, input_schema),
    FIELD(src, name),
    FIELD(src, annotations),
    FIELD(src, description)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::McpListTools)
    FIELD(src, id),
    FIELD(src, server_label),
    FIELD(src, tools),
    FIELD(src, type),
    FIELD(src, error)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::McpApprovalRequest)
    FIELD(src, id),
    FIELD(src, arguments),
    FIELD(src, name),
    FIELD(src, server_label),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::McpApprovalResponse)
    FIELD(src, approval_request_id),
    FIELD(src, approve),
    FIELD(src, type),
    FIELD(src, id),
    FIELD(src, reason)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::McpCall)
    FIELD(src, id),
    FIELD(src, arguments),
    FIELD(src, name),
    FIELD(src, server_label),
    FIELD(src, type),
    FIELD(src, approval_request_id),
    FIELD(src, error),
    FIELD(src, output),
    FIELD(src, status)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCustomToolCallOutput::ResponseInputText)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCustomToolCallOutput::ResponseInputImage)
    FIELD(src, detail),
    FIELD(src, type),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCustomToolCallOutput::ResponseInputFile)
    FIELD(src, type),
    FIELD(src, file_data),
    FIELD(src, file_id),
    FIELD(src, file_url),
    FIELD(src, filename)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCustomToolCallOutput)
    FIELD(src, call_id),
    FIELD(src, output),
    FIELD(src, type),
    FIELD(src, id)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCustomToolCall)
    FIELD(src, call_id),
    FIELD(src, input),
    FIELD(src, name),
    FIELD(src, type),
    FIELD(src, id)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ItemReference)
    FIELD(src, id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseCompactionItem)
    FIELD(src, id),
    FIELD(src, encrypted_content),
    FIELD(src, type),
    FIELD(src, created_by)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCall::ResponseFunctionShellToolCall_action)
    FIELD(src, commands),
    FIELD(src, max_output_length),
    FIELD(src, timeout_ms)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCall::ResponseLocalEnvironment)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCall::ResponseContainerReference)
    FIELD(src, container_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCall)
    FIELD(src, id),
    FIELD(src, action),
    FIELD(src, call_id),
    FIELD(src, environment),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, created_by)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Timeout)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Exit)
    FIELD(src, exit_code),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output)
    FIELD(src, outcome),
    FIELD_ALT(src, stderr_, "stderr"),
    FIELD_ALT(src, stdout_, "stdout"),
    FIELD(src, created_by)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseFunctionShellToolCallOutput)
    FIELD(src, id),
    FIELD(src, call_id),
    FIELD(src, max_output_length),
    FIELD(src, output),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, created_by)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseApplyPatchToolCall::CreateFile)
    FIELD(src, diff),
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseApplyPatchToolCall::DeleteFile)
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseApplyPatchToolCall::UpdateFile)
    FIELD(src, diff),
    FIELD(src, path),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseApplyPatchToolCall)
    FIELD(src, id),
    FIELD(src, call_id),
    FIELD(src, operation),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, created_by)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseApplyPatchToolCallOutput)
    FIELD(src, id),
    FIELD(src, call_id),
    FIELD(src, status),
    FIELD(src, type),
    FIELD(src, created_by),
    FIELD(src, output)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceAllowed)
    FIELD(src, mode),
    FIELD(src, tools),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceTypes)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceFunction)
    FIELD(src, name),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceMcp)
    FIELD(src, server_label),
    FIELD(src, type),
    FIELD(src, name)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceCustom)
    FIELD(src, name),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceApplyPatch)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ToolChoiceShell)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionTool)
    FIELD(src, name),
    FIELD(src, parameters),
    FIELD(src, strict),
    FIELD(src, type),
    FIELD(src, description)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool::ComparisonFilter)
    FIELD(src, key),
    FIELD(src, type),
    FIELD(src, value)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool::CompoundFilter::ComparisonFilter)
    FIELD(src, key),
    FIELD(src, type),
    FIELD(src, value)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool::CompoundFilter)
    FIELD(src, filters),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool::FileSearchTool_ranking_options::FileSearchTool_ranking_options_hybrid_search)
    FIELD(src, embedding_weight),
    FIELD(src, text_weight)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool::FileSearchTool_ranking_options)
    FIELD(src, hybrid_search),
    FIELD(src, ranker),
    FIELD(src, score_threshold)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FileSearchTool)
    FIELD(src, type),
    FIELD(src, vector_store_ids),
    FIELD(src, filters),
    FIELD(src, max_num_results),
    FIELD(src, ranking_options)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ComputerTool)
    FIELD(src, display_height),
    FIELD(src, display_width),
    FIELD(src, environment),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::WebSearchTool::WebSearchTool_filters)
    FIELD(src, allowed_domains)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::WebSearchTool::WebSearchTool_user_location)
    FIELD(src, city),
    FIELD(src, country),
    FIELD(src, region),
    FIELD(src, timezone),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::WebSearchTool)
    FIELD(src, type),
    FIELD(src, filters),
    FIELD(src, search_context_size),
    FIELD(src, user_location)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Mcp::McpToolFilter)
    FIELD(src, read_only),
    FIELD(src, tool_names)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Mcp::McpToolApprovalFilter::McpToolApprovalFilter_always)
    FIELD(src, read_only),
    FIELD(src, tool_names)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Mcp::McpToolApprovalFilter::McpToolApprovalFilter_never)
    FIELD(src, read_only),
    FIELD(src, tool_names)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Mcp::McpToolApprovalFilter)
    FIELD(src, always),
    FIELD(src, never)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Mcp)
    FIELD(src, server_label),
    FIELD(src, type),
    FIELD(src, allowed_tools),
    FIELD(src, authorization),
    FIELD(src, connector_id),
    FIELD(src, headers),
    FIELD(src, require_approval),
    FIELD(src, server_description),
    FIELD(src, server_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyDisabled)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyAllowlist::ContainerNetworkPolicyDomainSecret)
    FIELD(src, domain),
    FIELD(src, name),
    FIELD(src, value)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyAllowlist)
    FIELD(src, allowed_domains),
    FIELD(src, type),
    FIELD(src, domain_secrets)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CodeInterpreter::CodeInterpreterToolAuto)
    FIELD(src, type),
    FIELD(src, file_ids),
    FIELD(src, memory_limit),
    FIELD(src, network_policy)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CodeInterpreter)
    FIELD(src, container),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ImageGeneration::ImageGeneration_input_image_mask)
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ImageGeneration)
    FIELD(src, type),
    FIELD(src, action),
    FIELD(src, background),
    FIELD(src, input_fidelity),
    FIELD(src, input_image_mask),
    FIELD(src, model),
    FIELD(src, moderation),
    FIELD(src, output_compression),
    FIELD(src, output_format),
    FIELD(src, partial_images),
    FIELD(src, quality),
    FIELD(src, size)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::LocalShell)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyDisabled)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyAllowlist::ContainerNetworkPolicyDomainSecret)
    FIELD(src, domain),
    FIELD(src, name),
    FIELD(src, value)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyAllowlist)
    FIELD(src, allowed_domains),
    FIELD(src, type),
    FIELD(src, domain_secrets)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::SkillReference)
    FIELD(src, skill_id),
    FIELD(src, type),
    FIELD(src, version)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::InlineSkill::InlineSkillSource)
    FIELD(src, data),
    FIELD(src, media_type),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto::InlineSkill)
    FIELD(src, description),
    FIELD(src, name),
    FIELD(src, source),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerAuto)
    FIELD(src, type),
    FIELD(src, file_ids),
    FIELD(src, memory_limit),
    FIELD(src, network_policy),
    FIELD(src, skills)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::LocalEnvironment::LocalSkill)
    FIELD(src, description),
    FIELD(src, name),
    FIELD(src, path)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::LocalEnvironment)
    FIELD(src, type),
    FIELD(src, skills)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool::ContainerReference)
    FIELD(src, container_id),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::FunctionShellTool)
    FIELD(src, type),
    FIELD(src, environment)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CustomTool::Text)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CustomTool::Grammar)
    FIELD(src, definition),
    FIELD(src, syntax),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::CustomTool)
    FIELD(src, name),
    FIELD(src, type),
    FIELD(src, description),
    FIELD(src, format)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::WebSearchPreviewTool::WebSearchPreviewTool_user_location)
    FIELD(src, type),
    FIELD(src, city),
    FIELD(src, country),
    FIELD(src, region),
    FIELD(src, timezone)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::WebSearchPreviewTool)
    FIELD(src, type),
    FIELD(src, search_context_size),
    FIELD(src, user_location)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ApplyPatchTool)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Response_conversation)
    FIELD(src, id)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponsePrompt::ResponseInputText)
    FIELD(src, text),
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponsePrompt::ResponseInputImage)
    FIELD(src, detail),
    FIELD(src, type),
    FIELD(src, file_id),
    FIELD(src, image_url)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponsePrompt::ResponseInputFile)
    FIELD(src, type),
    FIELD(src, file_data),
    FIELD(src, file_id),
    FIELD(src, file_url),
    FIELD(src, filename)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponsePrompt)
    FIELD(src, id),
    FIELD(src, variables),
    FIELD(src, version)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::Reasoning)
    FIELD(src, effort),
    FIELD(src, generate_summary),
    FIELD(src, summary)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseTextConfig::ResponseFormatText)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseTextConfig::ResponseFormatTextJSONSchemaConfig)
    FIELD(src, name),
    FIELD(src, schema),
    FIELD(src, type),
    FIELD(src, description),
    FIELD(src, strict)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseTextConfig::ResponseFormatJSONObject)
    FIELD(src, type)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseTextConfig)
    FIELD(src, format),
    FIELD(src, verbosity)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseUsage::ResponseUsage_input_tokens_details)
    FIELD(src, cached_tokens)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseUsage::ResponseUsage_output_tokens_details)
    FIELD(src, reasoning_tokens)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response::ResponseUsage)
    FIELD(src, input_tokens),
    FIELD(src, input_tokens_details),
    FIELD(src, output_tokens),
    FIELD(src, output_tokens_details),
    FIELD(src, total_tokens)
END_DESERIALIZE

BEGIN_DESERIALIZE(openai::Response)
    FIELD(src, id),
    FIELD(src, created_at),
    FIELD(src, error),
    FIELD(src, incomplete_details),
    FIELD(src, instructions),
    FIELD(src, metadata),
    FIELD(src, model),
    FIELD(src, object),
    FIELD(src, output),
    FIELD(src, parallel_tool_calls),
    FIELD(src, temperature),
    FIELD(src, tool_choice),
    FIELD(src, tools),
    FIELD(src, top_p),
    FIELD(src, background),
    FIELD(src, completed_at),
    FIELD(src, conversation),
    FIELD(src, max_output_tokens),
    FIELD(src, max_tool_calls),
    FIELD(src, output_text),
    FIELD(src, previous_response_id),
    FIELD(src, prompt),
    FIELD(src, prompt_cache_key),
    FIELD(src, prompt_cache_retention),
    FIELD(src, reasoning),
    FIELD(src, safety_identifier),
    FIELD(src, service_tier),
    FIELD(src, status),
    FIELD(src, text),
    FIELD(src, top_logprobs),
    FIELD(src, truncation),
    FIELD(src, usage),
    FIELD(src, user)
END_DESERIALIZE

BEGIN_DESERIALIZE_VARIANT(openai::Response::EasyInputMessage::ResponseInputContent)
    auto kind = EXTRACT_KIND(openai::Response::EasyInputMessage::ResponseInputContentKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::EasyInputMessage::ResponseInputContentKind::INPUT_TEXT, openai::Response::EasyInputMessage::ResponseInputText)
    FIELD_KIND(src, kind, openai::Response::EasyInputMessage::ResponseInputContentKind::INPUT_IMAGE, openai::Response::EasyInputMessage::ResponseInputImage)
    FIELD_KIND(src, kind, openai::Response::EasyInputMessage::ResponseInputContentKind::INPUT_FILE, openai::Response::EasyInputMessage::ResponseInputFile)
END_DESERIALIZE_VARIANT(openai::Response::EasyInputMessage::ResponseInputContent)

BEGIN_DESERIALIZE_VARIANT(openai::Response::EasyInputMessage::Content)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    if (src.is_array()) {
        return T{DeserializeTo<std::vector<openai::Response::EasyInputMessage::ResponseInputContent>>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::EasyInputMessage::Content)

BEGIN_DESERIALIZE_VARIANT(openai::Response::Message::ResponseInputMessageContentList)
    auto kind = EXTRACT_KIND(openai::Response::Message::ResponseInputMessageContentListKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::Message::ResponseInputMessageContentListKind::INPUT_TEXT, openai::Response::Message::ResponseInputText)
    FIELD_KIND(src, kind, openai::Response::Message::ResponseInputMessageContentListKind::INPUT_IMAGE, openai::Response::Message::ResponseInputImage)
    FIELD_KIND(src, kind, openai::Response::Message::ResponseInputMessageContentListKind::INPUT_FILE, openai::Response::Message::ResponseInputFile)
END_DESERIALIZE_VARIANT(openai::Response::Message::ResponseInputMessageContentList)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseOutputMessage::ResponseOutputText::Annotations)
    auto kind = EXTRACT_KIND(openai::Response::ResponseOutputMessage::ResponseOutputText::AnnotationsKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ResponseOutputText::AnnotationsKind::FILE_CITATION, openai::Response::ResponseOutputMessage::ResponseOutputText::FileCitation)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ResponseOutputText::AnnotationsKind::URL_CITATION, openai::Response::ResponseOutputMessage::ResponseOutputText::URLCitation)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ResponseOutputText::AnnotationsKind::CONTAINER_FILE_CITATION, openai::Response::ResponseOutputMessage::ResponseOutputText::ContainerFileCitation)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ResponseOutputText::AnnotationsKind::FILE_PATH, openai::Response::ResponseOutputMessage::ResponseOutputText::FilePath)
END_DESERIALIZE_VARIANT(openai::Response::ResponseOutputMessage::ResponseOutputText::Annotations)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseOutputMessage::Content)
    auto kind = EXTRACT_KIND(openai::Response::ResponseOutputMessage::ContentKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ContentKind::OUTPUT_TEXT, openai::Response::ResponseOutputMessage::ResponseOutputText)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputMessage::ContentKind::REFUSAL, openai::Response::ResponseOutputMessage::ResponseOutputRefusal)
END_DESERIALIZE_VARIANT(openai::Response::ResponseOutputMessage::Content)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseFileSearchToolCall::ResponseFileSearchToolCall_results::Attributes)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    if (src.is_number()) {
        return T{DeserializeTo<double>(src)};
    }
    if (src.is_bool()) {
        return T{DeserializeTo<bool>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::ResponseFileSearchToolCall::ResponseFileSearchToolCall_results::Attributes)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseComputerToolCall::Action)
    auto kind = EXTRACT_KIND(openai::Response::ResponseComputerToolCall::ActionKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::CLICK, openai::Response::ResponseComputerToolCall::Click)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::DOUBLE_CLICK, openai::Response::ResponseComputerToolCall::DoubleClick)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::DRAG, openai::Response::ResponseComputerToolCall::Drag)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::KEYPRESS, openai::Response::ResponseComputerToolCall::Keypress)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::MOVE, openai::Response::ResponseComputerToolCall::Move)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::SCREENSHOT, openai::Response::ResponseComputerToolCall::Screenshot)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::SCROLL, openai::Response::ResponseComputerToolCall::Scroll)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::TYPE, openai::Response::ResponseComputerToolCall::Type)
    FIELD_KIND(src, kind, openai::Response::ResponseComputerToolCall::ActionKind::WAIT, openai::Response::ResponseComputerToolCall::Wait)
END_DESERIALIZE_VARIANT(openai::Response::ResponseComputerToolCall::Action)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionWebSearch::Action)
    auto kind = EXTRACT_KIND(openai::Response::ResponseFunctionWebSearch::ActionKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionWebSearch::ActionKind::SEARCH, openai::Response::ResponseFunctionWebSearch::Search)
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionWebSearch::ActionKind::OPEN_PAGE, openai::Response::ResponseFunctionWebSearch::OpenPage)
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionWebSearch::ActionKind::FIND_IN_PAGE, openai::Response::ResponseFunctionWebSearch::FindInPage)
END_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionWebSearch::Action)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FunctionCallOutput::Output)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    auto kind = EXTRACT_KIND(openai::Response::FunctionCallOutput::OutputKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::FunctionCallOutput::OutputKind::INPUT_TEXT, openai::Response::FunctionCallOutput::ResponseInputTextContent)
    FIELD_KIND(src, kind, openai::Response::FunctionCallOutput::OutputKind::INPUT_IMAGE, openai::Response::FunctionCallOutput::ResponseInputImageContent)
    FIELD_KIND(src, kind, openai::Response::FunctionCallOutput::OutputKind::INPUT_FILE, openai::Response::FunctionCallOutput::ResponseInputFileContent)
END_DESERIALIZE_VARIANT(openai::Response::FunctionCallOutput::Output)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseCodeInterpreterToolCall::Outputs)
    auto kind = EXTRACT_KIND(openai::Response::ResponseCodeInterpreterToolCall::OutputsKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseCodeInterpreterToolCall::OutputsKind::LOGS, openai::Response::ResponseCodeInterpreterToolCall::Logs)
    FIELD_KIND(src, kind, openai::Response::ResponseCodeInterpreterToolCall::OutputsKind::IMAGE, openai::Response::ResponseCodeInterpreterToolCall::Image)
END_DESERIALIZE_VARIANT(openai::Response::ResponseCodeInterpreterToolCall::Outputs)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ShellCall::Environment)
    auto kind = EXTRACT_KIND(openai::Response::ShellCall::EnvironmentKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ShellCall::EnvironmentKind::LOCAL, openai::Response::ShellCall::LocalEnvironment)
    FIELD_KIND(src, kind, openai::Response::ShellCall::EnvironmentKind::CONTAINER_REFERENCE, openai::Response::ShellCall::ContainerReference)
END_DESERIALIZE_VARIANT(openai::Response::ShellCall::Environment)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Outcome)
    auto kind = EXTRACT_KIND(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::OutcomeKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::OutcomeKind::TIMEOUT, openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Timeout)
    FIELD_KIND(src, kind, openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::OutcomeKind::EXIT, openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Exit)
END_DESERIALIZE_VARIANT(openai::Response::ShellCallOutput::ResponseFunctionShellCallOutputContent::Outcome)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ApplyPatchCall::Operation)
    auto kind = EXTRACT_KIND(openai::Response::ApplyPatchCall::OperationKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ApplyPatchCall::OperationKind::CREATE_FILE, openai::Response::ApplyPatchCall::CreateFile)
    FIELD_KIND(src, kind, openai::Response::ApplyPatchCall::OperationKind::DELETE_FILE, openai::Response::ApplyPatchCall::DeleteFile)
    FIELD_KIND(src, kind, openai::Response::ApplyPatchCall::OperationKind::UPDATE_FILE, openai::Response::ApplyPatchCall::UpdateFile)
END_DESERIALIZE_VARIANT(openai::Response::ApplyPatchCall::Operation)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseCustomToolCallOutput::Output)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::ResponseCustomToolCallOutput::Output)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionShellToolCall::Environment)
    auto kind = EXTRACT_KIND(openai::Response::ResponseFunctionShellToolCall::EnvironmentKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionShellToolCall::EnvironmentKind::LOCAL, openai::Response::ResponseFunctionShellToolCall::ResponseLocalEnvironment)
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionShellToolCall::EnvironmentKind::CONTAINER_REFERENCE, openai::Response::ResponseFunctionShellToolCall::ResponseContainerReference)
END_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionShellToolCall::Environment)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Outcome)
    auto kind = EXTRACT_KIND(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::OutcomeKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::OutcomeKind::TIMEOUT, openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Timeout)
    FIELD_KIND(src, kind, openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::OutcomeKind::EXIT, openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Exit)
END_DESERIALIZE_VARIANT(openai::Response::ResponseFunctionShellToolCallOutput::ResponseFunctionShellToolCallOutput_output::Outcome)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseApplyPatchToolCall::Operation)
    auto kind = EXTRACT_KIND(openai::Response::ResponseApplyPatchToolCall::OperationKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseApplyPatchToolCall::OperationKind::CREATE_FILE, openai::Response::ResponseApplyPatchToolCall::CreateFile)
    FIELD_KIND(src, kind, openai::Response::ResponseApplyPatchToolCall::OperationKind::DELETE_FILE, openai::Response::ResponseApplyPatchToolCall::DeleteFile)
    FIELD_KIND(src, kind, openai::Response::ResponseApplyPatchToolCall::OperationKind::UPDATE_FILE, openai::Response::ResponseApplyPatchToolCall::UpdateFile)
END_DESERIALIZE_VARIANT(openai::Response::ResponseApplyPatchToolCall::Operation)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FileSearchTool::CompoundFilter::Filters)
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::FileSearchTool::CompoundFilter::ComparisonFilter>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::FileSearchTool::CompoundFilter::Filters)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FileSearchTool::Filters)
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::FileSearchTool::ComparisonFilter>(src)};
    }
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::FileSearchTool::CompoundFilter>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::FileSearchTool::Filters)

BEGIN_DESERIALIZE_VARIANT(openai::Response::Mcp::AllowedTools)
    if (src.is_array()) {
        return T{DeserializeTo<std::vector<std::string>>(src)};
    }
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::Mcp::McpToolFilter>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::Mcp::AllowedTools)

BEGIN_DESERIALIZE_VARIANT(openai::Response::Mcp::RequireApproval)
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::Mcp::McpToolApprovalFilter>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::Mcp::RequireApproval)

BEGIN_DESERIALIZE_VARIANT(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::NetworkPolicy)
    auto kind = EXTRACT_KIND(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::NetworkPolicyKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::CodeInterpreter::CodeInterpreterToolAuto::NetworkPolicyKind::DISABLED, openai::Response::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyDisabled)
    FIELD_KIND(src, kind, openai::Response::CodeInterpreter::CodeInterpreterToolAuto::NetworkPolicyKind::ALLOWLIST, openai::Response::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyAllowlist)
END_DESERIALIZE_VARIANT(openai::Response::CodeInterpreter::CodeInterpreterToolAuto::NetworkPolicy)

BEGIN_DESERIALIZE_VARIANT(openai::Response::CodeInterpreter::Container)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    auto kind = EXTRACT_KIND(openai::Response::CodeInterpreter::ContainerKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::CodeInterpreter::ContainerKind::AUTO, openai::Response::CodeInterpreter::CodeInterpreterToolAuto)
END_DESERIALIZE_VARIANT(openai::Response::CodeInterpreter::Container)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::ContainerAuto::NetworkPolicy)
    auto kind = EXTRACT_KIND(openai::Response::FunctionShellTool::ContainerAuto::NetworkPolicyKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::ContainerAuto::NetworkPolicyKind::DISABLED, openai::Response::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyDisabled)
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::ContainerAuto::NetworkPolicyKind::ALLOWLIST, openai::Response::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyAllowlist)
END_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::ContainerAuto::NetworkPolicy)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::ContainerAuto::Skills)
    auto kind = EXTRACT_KIND(openai::Response::FunctionShellTool::ContainerAuto::SkillsKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::ContainerAuto::SkillsKind::SKILL_REFERENCE, openai::Response::FunctionShellTool::ContainerAuto::SkillReference)
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::ContainerAuto::SkillsKind::INLINE, openai::Response::FunctionShellTool::ContainerAuto::InlineSkill)
END_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::ContainerAuto::Skills)

BEGIN_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::Environment)
    auto kind = EXTRACT_KIND(openai::Response::FunctionShellTool::EnvironmentKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::EnvironmentKind::CONTAINER_AUTO, openai::Response::FunctionShellTool::ContainerAuto)
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::EnvironmentKind::LOCAL, openai::Response::FunctionShellTool::LocalEnvironment)
    FIELD_KIND(src, kind, openai::Response::FunctionShellTool::EnvironmentKind::CONTAINER_REFERENCE, openai::Response::FunctionShellTool::ContainerReference)
END_DESERIALIZE_VARIANT(openai::Response::FunctionShellTool::Environment)

BEGIN_DESERIALIZE_VARIANT(openai::Response::CustomTool::CustomToolInputFormat)
    auto kind = EXTRACT_KIND(openai::Response::CustomTool::CustomToolInputFormatKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::CustomTool::CustomToolInputFormatKind::TEXT, openai::Response::CustomTool::Text)
    FIELD_KIND(src, kind, openai::Response::CustomTool::CustomToolInputFormatKind::GRAMMAR, openai::Response::CustomTool::Grammar)
END_DESERIALIZE_VARIANT(openai::Response::CustomTool::CustomToolInputFormat)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponsePrompt::Variables)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    auto kind = EXTRACT_KIND(openai::Response::ResponsePrompt::VariablesKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponsePrompt::VariablesKind::INPUT_TEXT, openai::Response::ResponsePrompt::ResponseInputText)
    FIELD_KIND(src, kind, openai::Response::ResponsePrompt::VariablesKind::INPUT_IMAGE, openai::Response::ResponsePrompt::ResponseInputImage)
    FIELD_KIND(src, kind, openai::Response::ResponsePrompt::VariablesKind::INPUT_FILE, openai::Response::ResponsePrompt::ResponseInputFile)
END_DESERIALIZE_VARIANT(openai::Response::ResponsePrompt::Variables)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseTextConfig::ResponseFormatTextConfig)
    auto kind = EXTRACT_KIND(openai::Response::ResponseTextConfig::ResponseFormatTextConfigKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseTextConfig::ResponseFormatTextConfigKind::TEXT, openai::Response::ResponseTextConfig::ResponseFormatText)
    FIELD_KIND(src, kind, openai::Response::ResponseTextConfig::ResponseFormatTextConfigKind::JSON_SCHEMA, openai::Response::ResponseTextConfig::ResponseFormatTextJSONSchemaConfig)
    FIELD_KIND(src, kind, openai::Response::ResponseTextConfig::ResponseFormatTextConfigKind::JSON_OBJECT, openai::Response::ResponseTextConfig::ResponseFormatJSONObject)
END_DESERIALIZE_VARIANT(openai::Response::ResponseTextConfig::ResponseFormatTextConfig)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseInputItem)
    auto kind = EXTRACT_KIND(openai::Response::ResponseInputItemKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::EASY_INPUT_MESSAGE, openai::Response::EasyInputMessage)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MESSAGE, openai::Response::Message)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::ASSISTANT, openai::Response::ResponseOutputMessage)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FILE_SEARCH_CALL, openai::Response::ResponseFileSearchToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::COMPUTER_CALL, openai::Response::ResponseComputerToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::COMPUTER_CALL_OUTPUT, openai::Response::ComputerCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::WEB_SEARCH_CALL, openai::Response::ResponseFunctionWebSearch)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FUNCTION_CALL, openai::Response::ResponseFunctionToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FUNCTION_CALL_OUTPUT, openai::Response::FunctionCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::REASONING, openai::Response::ResponseReasoningItem)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_COMPACTION_ITEM_PARAM, openai::Response::ResponseCompactionItemParam)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::IMAGE_GENERATION_CALL, openai::Response::ImageGenerationCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::CODE_INTERPRETER_CALL, openai::Response::ResponseCodeInterpreterToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::LOCAL_SHELL_CALL, openai::Response::LocalShellCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::LOCAL_SHELL_CALL_OUTPUT, openai::Response::LocalShellCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::SHELL_CALL, openai::Response::ShellCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::SHELL_CALL_OUTPUT, openai::Response::ShellCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::APPLY_PATCH_CALL, openai::Response::ApplyPatchCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::APPLY_PATCH_CALL_OUTPUT, openai::Response::ApplyPatchCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MCP_LIST_TOOLS, openai::Response::McpListTools)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MCP_APPROVAL_REQUEST, openai::Response::McpApprovalRequest)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MCP_APPROVAL_RESPONSE, openai::Response::McpApprovalResponse)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MCP_CALL, openai::Response::McpCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::CUSTOM_TOOL_CALL_OUTPUT, openai::Response::ResponseCustomToolCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::CUSTOM_TOOL_CALL, openai::Response::ResponseCustomToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::ITEM_REFERENCE, openai::Response::ItemReference)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_COMPACTION_ITEM, openai::Response::ResponseCompactionItem)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_FUNCTION_SHELL_TOOL_CALL, openai::Response::ResponseFunctionShellToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_FUNCTION_SHELL_TOOL_CALL_OUTPUT, openai::Response::ResponseFunctionShellToolCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_APPLY_PATCH_TOOL_CALL, openai::Response::ResponseApplyPatchToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::RESPONSE_APPLY_PATCH_TOOL_CALL_OUTPUT, openai::Response::ResponseApplyPatchToolCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::ALLOWED_TOOLS, openai::Response::ToolChoiceAllowed)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::TOOL_CHOICE_FUNCTION, openai::Response::ToolChoiceFunction)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::TOOL_CHOICE_MCP, openai::Response::ToolChoiceMcp)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::TOOL_CHOICE_CUSTOM, openai::Response::ToolChoiceCustom)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::TOOL_CHOICE_APPLY_PATCH, openai::Response::ToolChoiceApplyPatch)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::TOOL_CHOICE_SHELL, openai::Response::ToolChoiceShell)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FUNCTION_TOOL, openai::Response::FunctionTool)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FILE_SEARCH, openai::Response::FileSearchTool)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::COMPUTER_USE_PREVIEW, openai::Response::ComputerTool)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::MCP, openai::Response::Mcp)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::CODE_INTERPRETER, openai::Response::CodeInterpreter)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::IMAGE_GENERATION, openai::Response::ImageGeneration)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::LOCAL_SHELL, openai::Response::LocalShell)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::FUNCTION_SHELL_TOOL, openai::Response::FunctionShellTool)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::CUSTOM_TOOL, openai::Response::CustomTool)
    FIELD_KIND(src, kind, openai::Response::ResponseInputItemKind::APPLY_PATCH_TOOL, openai::Response::ApplyPatchTool)
END_DESERIALIZE_VARIANT(openai::Response::ResponseInputItem)

BEGIN_DESERIALIZE_VARIANT(openai::Response::Instructions)
    if (src.is_string()) {
        return T{DeserializeTo<std::string>(src)};
    }
    if (src.is_array()) {
        return T{DeserializeTo<std::vector<openai::Response::ResponseInputItem>>(src)};
    }
END_DESERIALIZE_VARIANT(openai::Response::Instructions)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ResponseOutputItem)
    auto kind = EXTRACT_KIND(openai::Response::ResponseOutputItemKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::MESSAGE, openai::Response::ResponseOutputMessage)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::FILE_SEARCH_CALL, openai::Response::ResponseFileSearchToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::FUNCTION_CALL, openai::Response::ResponseFunctionToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::WEB_SEARCH_CALL, openai::Response::ResponseFunctionWebSearch)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::COMPUTER_CALL, openai::Response::ResponseComputerToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::REASONING, openai::Response::ResponseReasoningItem)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::COMPACTION, openai::Response::ResponseCompactionItem)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::IMAGE_GENERATION_CALL, openai::Response::ImageGenerationCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::CODE_INTERPRETER_CALL, openai::Response::ResponseCodeInterpreterToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::LOCAL_SHELL_CALL, openai::Response::LocalShellCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::SHELL_CALL, openai::Response::ResponseFunctionShellToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::SHELL_CALL_OUTPUT, openai::Response::ResponseFunctionShellToolCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::APPLY_PATCH_CALL, openai::Response::ResponseApplyPatchToolCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::APPLY_PATCH_CALL_OUTPUT, openai::Response::ResponseApplyPatchToolCallOutput)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::MCP_CALL, openai::Response::McpCall)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::MCP_LIST_TOOLS, openai::Response::McpListTools)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::MCP_APPROVAL_REQUEST, openai::Response::McpApprovalRequest)
    FIELD_KIND(src, kind, openai::Response::ResponseOutputItemKind::CUSTOM_TOOL_CALL, openai::Response::ResponseCustomToolCall)
END_DESERIALIZE_VARIANT(openai::Response::ResponseOutputItem)

BEGIN_DESERIALIZE_VARIANT(openai::Response::ToolChoice)
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::ToolChoiceTypes>(src)};
    }
    auto kind = EXTRACT_KIND(openai::Response::ToolChoiceKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::ALLOWED_TOOLS, openai::Response::ToolChoiceAllowed)
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::FUNCTION, openai::Response::ToolChoiceFunction)
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::MCP, openai::Response::ToolChoiceMcp)
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::CUSTOM, openai::Response::ToolChoiceCustom)
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::APPLY_PATCH, openai::Response::ToolChoiceApplyPatch)
    FIELD_KIND(src, kind, openai::Response::ToolChoiceKind::SHELL, openai::Response::ToolChoiceShell)
END_DESERIALIZE_VARIANT(openai::Response::ToolChoice)

BEGIN_DESERIALIZE_VARIANT(openai::Response::Tool)
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::WebSearchTool>(src)};
    }
    if (src.is_object()) {
        return T{DeserializeTo<openai::Response::WebSearchPreviewTool>(src)};
    }
    auto kind = EXTRACT_KIND(openai::Response::ToolKind, src, "type");
    FIELD_KIND(src, kind, openai::Response::ToolKind::FUNCTION, openai::Response::FunctionTool)
    FIELD_KIND(src, kind, openai::Response::ToolKind::FILE_SEARCH, openai::Response::FileSearchTool)
    FIELD_KIND(src, kind, openai::Response::ToolKind::COMPUTER_USE_PREVIEW, openai::Response::ComputerTool)
    FIELD_KIND(src, kind, openai::Response::ToolKind::MCP, openai::Response::Mcp)
    FIELD_KIND(src, kind, openai::Response::ToolKind::CODE_INTERPRETER, openai::Response::CodeInterpreter)
    FIELD_KIND(src, kind, openai::Response::ToolKind::IMAGE_GENERATION, openai::Response::ImageGeneration)
    FIELD_KIND(src, kind, openai::Response::ToolKind::LOCAL_SHELL, openai::Response::LocalShell)
    FIELD_KIND(src, kind, openai::Response::ToolKind::SHELL, openai::Response::FunctionShellTool)
    FIELD_KIND(src, kind, openai::Response::ToolKind::CUSTOM, openai::Response::CustomTool)
    FIELD_KIND(src, kind, openai::Response::ToolKind::APPLY_PATCH, openai::Response::ApplyPatchTool)
END_DESERIALIZE_VARIANT(openai::Response::Tool)

/***
 * Top-level Deserialize
 */
namespace openai {
    Response Deserialize(const curl::Response& response) {
        if (response.body.size() < response.body_len + simdjson::SIMDJSON_PADDING) {
            throw AnnotatedException{"Simdjson padding check failed"};
        }

        static thread_local simdjson::dom::parser parser{};

        try {
            simdjson::dom::element doc = parser.parse(
                reinterpret_cast<const char*>(response.body.data()), response.body_len);
            return DeserializeTo<Response>(doc);
        } catch (const simdjson::simdjson_error& e) {
            throw AnnotatedException{"openai::Deserialize Failed", e.what()};
        }
    }
}

} // namespace jai::llm
