// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "../../core/types.hpp"


namespace jai::llm::gemini {


/***
 * Vocabulary enums
 */
enum class Behavior { UNSPECIFIED, BLOCKING, NON_BLOCKING };
enum class BlockReason { BLOCK_REASON_UNSPECIFIED, SAFETY, OTHER, BLOCKLIST, PROHIBITED_CONTENT, IMAGE_SAFETY };
enum class Category { HARM_CATEGORY_UNSPECIFIED, HARM_CATEGORY_DEROGATORY, HARM_CATEGORY_TOXICITY, HARM_CATEGORY_VIOLENCE, HARM_CATEGORY_SEXUAL, HARM_CATEGORY_MEDICAL, HARM_CATEGORY_DANGEROUS, HARM_CATEGORY_HARASSMENT, HARM_CATEGORY_HATE_SPEECH, HARM_CATEGORY_SEXUALLY_EXPLICIT, HARM_CATEGORY_DANGEROUS_CONTENT, HARM_CATEGORY_CIVIC_INTEGRITY };
enum class DynamicRetrievalConfigMode { MODE_UNSPECIFIED, MODE_DYNAMIC };
enum class Environment { ENVIRONMENT_UNSPECIFIED, ENVIRONMENT_BROWSER };
enum class FinishReason { FINISH_REASON_UNSPECIFIED, STOP, MAX_TOKENS, SAFETY, RECITATION, LANGUAGE, OTHER, BLOCKLIST, PROHIBITED_CONTENT, SPII, MALFORMED_FUNCTION_CALL, IMAGE_SAFETY, IMAGE_PROHIBITED_CONTENT, IMAGE_OTHER, NO_IMAGE, IMAGE_RECITATION, UNEXPECTED_TOOL_CALL, TOO_MANY_TOOL_CALLS, MISSING_THOUGHT_SIGNATURE, MALFORMED_RESPONSE };
enum class FunctionCallingConfigMode { MODE_UNSPECIFIED, AUTO, ANY, NONE, VALIDATED };
enum class Language { LANGUAGE_UNSPECIFIED, PYTHON };
enum class MediaResolution { MEDIA_RESOLUTION_UNSPECIFIED, MEDIA_RESOLUTION_LOW, MEDIA_RESOLUTION_MEDIUM, MEDIA_RESOLUTION_HIGH };
enum class Modality { MODALITY_UNSPECIFIED, TEXT, IMAGE, VIDEO, AUDIO, DOCUMENT };
enum class ModelStage { MODEL_STAGE_UNSPECIFIED, UNSTABLE_EXPERIMENTAL, EXPERIMENTAL, PREVIEW, STABLE, LEGACY, DEPRECATED, RETIRED };
enum class Outcome { OUTCOME_UNSPECIFIED, OUTCOME_OK, OUTCOME_FAILED, OUTCOME_DEADLINE_EXCEEDED };
enum class Probability { HARM_PROBABILITY_UNSPECIFIED, NEGLIGIBLE, LOW, MEDIUM, HIGH };
enum class Scheduling { SCHEDULING_UNSPECIFIED, SILENT, WHEN_IDLE, INTERRUPT };
enum class ThinkingLevel { THINKING_LEVEL_UNSPECIFIED, MINIMAL, LOW, MEDIUM, HIGH };
enum class Threshold { HARM_BLOCK_THRESHOLD_UNSPECIFIED, BLOCK_LOW_AND_ABOVE, BLOCK_MEDIUM_AND_ABOVE, BLOCK_ONLY_HIGH, BLOCK_NONE, OFF };
enum class Type { TYPE_UNSPECIFIED, STRING, NUMBER, INTEGER, BOOLEAN, ARRAY, OBJECT, NULL_T };
enum class UrlRetrievalStatus { URL_RETRIEVAL_STATUS_UNSPECIFIED, URL_RETRIEVAL_STATUS_SUCCESS, URL_RETRIEVAL_STATUS_ERROR, URL_RETRIEVAL_STATUS_PAYWALL, URL_RETRIEVAL_STATUS_UNSAFE };


/***
 * Data structures
 */
/** Raw media bytes. Text should not be sent as raw bytes, use the 'text' field. */
struct Blob {
    std::optional<std::string> mimeType{};
    std::optional<std::string> data{};
};

/** A citation to a source for a portion of a specific response. */
struct CitationSource {
    std::optional<int64_t> startIndex{};
    std::optional<int64_t> endIndex{};
    std::optional<std::string> uri{};
    std::optional<std::string> license{};
};

/** Tool that executes code generated by the model, and automatically returns the result to the model. S... */
struct CodeExecution {
};

/** Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used. */
struct CodeExecutionResult {
    Required<Outcome> outcome;
    std::optional<std::string> output{};
};

/** Computer Use tool type. */
struct ComputerUse {
    Required<Environment> environment;
    std::optional<std::vector<std::string>> excludedPredefinedFunctions{};
};

/** Describes the options to customize dynamic retrieval. */
struct DynamicRetrievalConfig {
    Required<DynamicRetrievalConfigMode> mode;
    Required<double> dynamicThreshold;
};

/** Code generated by the model that is meant to be executed, and the result returned to the model. Only... */
struct ExecutableCode {
    Required<Language> language;
    Required<std::string> code;
};

/** URI based data. */
struct FileData {
    std::optional<std::string> mimeType{};
    Required<std::string> fileUri;
};

/** The FileSearch tool that retrieves knowledge from Semantic Retrieval corpora. Files are imported to ... */
struct FileSearch {
    Required<std::vector<std::string>> fileSearchStoreNames;
    std::optional<int64_t> topK{};
    std::optional<std::string> metadataFilter{};
};

/** A predicted `FunctionCall` returned from the model that contains a string representing the `Function... */
struct FunctionCall {
    std::optional<std::string> id{};
    Required<std::string> name;
    std::optional<jai::llm::json::Object> args{};
};

/** Configuration for specifying function calling behavior. */
struct FunctionCallingConfig {
    std::optional<FunctionCallingConfigMode> mode{};
    std::optional<std::vector<std::string>> allowedFunctionNames{};
};

/** Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionRespon... */
struct FunctionResponseBlob {
    std::optional<std::string> mimeType{};
    std::optional<std::string> data{};
};

/** Segment of the content. */
struct GoogleAiGenerativelanguageV1betaSegment {
    std::optional<int64_t> partIndex{};
    std::optional<int64_t> startIndex{};
    std::optional<int64_t> endIndex{};
    std::optional<std::string> text{};
};

/** The GoogleMaps Tool that provides geospatial context for the user's query. */
struct GoogleMaps {
    std::optional<bool> enableWidget{};
};

/** Identifier for a part within a `GroundingPassage`. */
struct GroundingPassageId {
    std::optional<std::string> passageId{};
    std::optional<int64_t> partIndex{};
};

/** Chunk from image search. */
struct Image {
    std::optional<std::string> sourceUri{};
    std::optional<std::string> imageUri{};
    std::optional<std::string> title{};
    std::optional<std::string> domain{};
};

/** Config for image generation features. */
struct ImageConfig {
    std::optional<std::string> aspectRatio{};
    std::optional<std::string> imageSize{};
};

/** Image search for grounding and related configurations. */
struct ImageSearch {
};

/** Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive)... */
struct Interval {
    std::optional<std::string> startTime{};
    std::optional<std::string> endTime{};
};

/** An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to repre... */
struct LatLng {
    Required<double> latitude;
    Required<double> longitude;
};

/** Candidate for the logprobs token and score. */
struct LogprobsResultCandidate {
    std::optional<std::string> token{};
    std::optional<int64_t> tokenId{};
    std::optional<double> logProbability{};
};

/** Represents token counting info for a single modality. */
struct ModalityTokenCount {
    std::optional<Modality> modality{};
    std::optional<int64_t> tokenCount{};
};

/** The status of the underlying model. This is used to indicate the stage of the underlying model and t... */
struct ModelStatus {
    std::optional<ModelStage> modelStage{};
    std::optional<std::string> retirementTime{};
    std::optional<std::string> message{};
};

/** The configuration for the prebuilt speaker to use. */
struct PrebuiltVoiceConfig {
    Required<std::string> voiceName;
};

/** Metadata related to retrieval in the grounding flow. */
struct RetrievalMetadata {
    std::optional<double> googleSearchDynamicRetrievalScore{};
};

/** Chunk from context retrieved by the file search tool. */
struct RetrievedContext {
    std::optional<std::string> uri{};
    std::optional<std::string> title{};
    std::optional<std::string> text{};
    std::optional<std::string> fileSearchStore{};
};

/** Encapsulates a snippet of a user review that answers a question about the features of a specific pla... */
struct ReviewSnippet {
    std::optional<std::string> reviewId{};
    std::optional<std::string> googleMapsUri{};
    std::optional<std::string> title{};
};

/** Safety rating for a piece of content. The safety rating contains the category of harm and the harm p... */
struct SafetyRating {
    std::optional<Category> category{};
    std::optional<Probability> probability{};
    std::optional<bool> blocked{};
};

/** Safety setting, affecting the safety-blocking behavior. Passing a safety setting for a category chan... */
struct SafetySetting {
    Required<Category> category;
    Required<Threshold> threshold;
};

/** The `Schema` object allows the definition of input and output data types. These types can be objects... */
struct Schema {
    Required<Type> type;
    std::optional<std::string> format{};
    std::optional<std::string> title{};
    std::optional<std::string> description{};
    std::optional<bool> nullable{};
    std::optional<std::vector<std::string>> enum_value{};  // JSON: "enum"
    std::optional<ValueBox<Schema>> items{};
    std::optional<int64_t> maxItems{};
    std::optional<int64_t> minItems{};
    std::optional<jai::llm::json::Object> properties{};
    std::optional<std::vector<std::string>> required{};
    std::optional<int64_t> minProperties{};
    std::optional<int64_t> maxProperties{};
    std::optional<double> minimum{};
    std::optional<double> maximum{};
    std::optional<int64_t> minLength{};
    std::optional<int64_t> maxLength{};
    std::optional<std::string> pattern{};
    std::optional<jai::llm::json::Value> example{};
    std::optional<std::vector<Schema>> anyOf{};
    std::optional<std::vector<std::string>> propertyOrdering{};
    std::optional<jai::llm::json::Value> default_value{};  // JSON: "default"
};

/** Google search entry point. */
struct SearchEntryPoint {
    std::optional<std::string> renderedContent{};
    std::optional<std::string> sdkBlob{};
};

/** Identifier for a `Chunk` retrieved via Semantic Retriever specified in the `GenerateAnswerRequest` u... */
struct SemanticRetrieverChunk {
    std::optional<std::string> source{};
    std::optional<std::string> chunk{};
};

/** A transport that can stream HTTP requests and responses. Next ID: 6 */
struct StreamableHttpTransport {
    Required<std::string> url;
    Required<std::map<std::string, std::string>> headers;
    Required<std::string> timeout;
    Required<std::string> sseReadTimeout;
    Required<bool> terminateOnClose;
};

/** Config for thinking features. */
struct ThinkingConfig {
    Required<bool> includeThoughts;
    Required<int64_t> thinkingBudget;
    std::optional<ThinkingLevel> thinkingLevel{};
};

/** Tool to support URL context retrieval. */
struct UrlContext {
};

/** Context of the a single url retrieval. */
struct UrlMetadata {
    std::optional<std::string> retrievedUrl{};
    std::optional<UrlRetrievalStatus> urlRetrievalStatus{};
};

/** Chunk from the web. */
struct Web {
    std::optional<std::string> uri{};
    std::optional<std::string> title{};
};

/** Standard web search for grounding and related configurations. */
struct WebSearch {
};

/** A collection of source attributions for a piece of content. */
struct CitationMetadata {
    std::optional<std::vector<CitationSource>> citationSources{};
};

/** Tool to retrieve public web data for grounding, powered by Google. */
struct GoogleSearchRetrieval {
    Required<DynamicRetrievalConfig> dynamicRetrievalConfig;
};

/** A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` c... */
struct FunctionResponsePart {
    std::optional<FunctionResponseBlob> inlineData{};
};

/** Grounding support. */
struct GoogleAiGenerativelanguageV1betaGroundingSupport {
    std::optional<GoogleAiGenerativelanguageV1betaSegment> segment{};
    std::optional<std::vector<int64_t>> groundingChunkIndices{};
    std::optional<std::vector<double>> confidenceScores{};
};

/** Retrieval config. */
struct RetrievalConfig {
    std::optional<LatLng> latLng{};
    std::optional<std::string> languageCode{};
};

/** Candidates with top log probabilities at each decoding step. */
struct TopCandidates {
    std::optional<std::vector<LogprobsResultCandidate>> candidates{};
};

/** Metadata on the generation request's token usage. */
struct UsageMetadata {
    std::optional<int64_t> promptTokenCount{};
    std::optional<int64_t> cachedContentTokenCount{};
    std::optional<int64_t> candidatesTokenCount{};
    std::optional<int64_t> toolUsePromptTokenCount{};
    std::optional<int64_t> thoughtsTokenCount{};
    std::optional<int64_t> totalTokenCount{};
    std::optional<std::vector<ModalityTokenCount>> promptTokensDetails{};
    std::optional<std::vector<ModalityTokenCount>> cacheTokensDetails{};
    std::optional<std::vector<ModalityTokenCount>> candidatesTokensDetails{};
    std::optional<std::vector<ModalityTokenCount>> toolUsePromptTokensDetails{};
};

/** The configuration for the voice to use. */
struct VoiceConfig {
    Required<PrebuiltVoiceConfig> prebuiltVoiceConfig;
};

/** Collection of sources that provide answers about the features of a given place in Google Maps. Each ... */
struct PlaceAnswerSources {
    std::optional<std::vector<ReviewSnippet>> reviewSnippets{};
};

/** A set of the feedback metadata the prompt specified in `GenerateContentRequest.content`. */
struct PromptFeedback {
    std::optional<BlockReason> blockReason{};
    std::optional<std::vector<SafetyRating>> safetyRatings{};
};

/** Structured representation of a function declaration as defined by the [OpenAPI 3.03 specification](h... */
struct FunctionDeclaration {
    Required<std::string> name;
    Required<std::string> description;
    std::optional<Schema> parameters{};
    std::optional<jai::llm::json::Value> parametersJsonSchema{};
    std::optional<Schema> response{};
    std::optional<jai::llm::json::Value> responseJsonSchema{};
    std::optional<Behavior> behavior{};
};

/** Identifier for the source contributing to this attribution. */
struct AttributionSourceId {
    std::optional<GroundingPassageId> groundingPassage{};
    std::optional<SemanticRetrieverChunk> semanticRetrieverChunk{};
};

/** A MCPServer is a server that can be called by the model to perform actions. It is a server that impl... */
struct McpServer {
    Required<StreamableHttpTransport> streamableHttpTransport;
    Required<std::string> name;
};

/** Metadata related to url context retrieval tool. */
struct UrlContextMetadata {
    std::optional<std::vector<UrlMetadata>> urlMetadata{};
};

/** Different types of search that can be enabled on the GoogleSearch tool. */
struct SearchTypes {
    std::optional<WebSearch> webSearch{};
    std::optional<ImageSearch> imageSearch{};
};

/** The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration... */
struct FunctionResponse {
    std::optional<std::string> id{};
    Required<std::string> name;
    Required<jai::llm::json::Object> response;
    std::optional<std::vector<FunctionResponsePart>> parts{};
    std::optional<bool> willContinue{};
    std::optional<Scheduling> scheduling{};
};

/** The Tool configuration containing parameters for specifying `Tool` use in the request. */
struct ToolConfig {
    std::optional<FunctionCallingConfig> functionCallingConfig{};
    std::optional<RetrievalConfig> retrievalConfig{};
};

/** Logprobs Result */
struct LogprobsResult {
    std::optional<double> logProbabilitySum{};
    std::optional<std::vector<TopCandidates>> topCandidates{};
    std::optional<std::vector<LogprobsResultCandidate>> chosenCandidates{};
};

/** The configuration for a single speaker in a multi speaker setup. */
struct SpeakerVoiceConfig {
    Required<std::string> speaker;
    Required<VoiceConfig> voiceConfig;
};

/** A grounding chunk from Google Maps. A Maps chunk corresponds to a single place. */
struct Maps {
    std::optional<std::string> uri{};
    std::optional<std::string> title{};
    std::optional<std::string> text{};
    std::optional<std::string> placeId{};
    std::optional<PlaceAnswerSources> placeAnswerSources{};
};

/** GoogleSearch tool type. Tool to support Google Search in Model. Powered by Google. */
struct GoogleSearch {
    std::optional<Interval> timeRangeFilter{};
    std::optional<SearchTypes> searchTypes{};
};

/** A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of dat... */
struct Part {
    std::optional<std::string> text{};
    std::optional<Blob> inlineData{};
    std::optional<FunctionCall> functionCall{};
    std::optional<FunctionResponse> functionResponse{};
    std::optional<FileData> fileData{};
    std::optional<ExecutableCode> executableCode{};
    std::optional<CodeExecutionResult> codeExecutionResult{};
    std::optional<bool> thought{};
    std::optional<std::string> thoughtSignature{};
    std::optional<jai::llm::json::Object> partMetadata{};
    std::optional<MediaResolution> mediaResolution{};
};

/** The configuration for the multi-speaker setup. */
struct MultiSpeakerVoiceConfig {
    Required<std::vector<SpeakerVoiceConfig>> speakerVoiceConfigs;
};

/** A `GroundingChunk` represents a segment of supporting evidence that grounds the model's response. It... */
struct GroundingChunk {
    std::optional<Web> web{};
    std::optional<Image> image{};
    std::optional<RetrievedContext> retrievedContext{};
    std::optional<Maps> maps{};
};

/** Tool details that the model may use to generate response. A `Tool` is a piece of code that enables t... */
struct Tool {
    std::optional<std::vector<FunctionDeclaration>> functionDeclarations{};
    std::optional<GoogleSearchRetrieval> googleSearchRetrieval{};
    std::optional<CodeExecution> codeExecution{};
    std::optional<GoogleSearch> googleSearch{};
    std::optional<ComputerUse> computerUse{};
    std::optional<UrlContext> urlContext{};
    std::optional<FileSearch> fileSearch{};
    std::optional<std::vector<McpServer>> mcpServers{};
    std::optional<GoogleMaps> googleMaps{};
};

/** The base structured datatype containing multi-part content of a message. A `Content` includes a `rol... */
struct Content {
    std::optional<std::vector<Part>> parts{};
    std::optional<std::string> role{};
};

/** Config for speech generation and transcription. */
struct SpeechConfig {
    Required<VoiceConfig> voiceConfig;
    std::optional<MultiSpeakerVoiceConfig> multiSpeakerVoiceConfig{};
    std::optional<std::string> languageCode{};
};

/** Metadata returned to client when grounding is enabled. */
struct GroundingMetadata {
    std::optional<SearchEntryPoint> searchEntryPoint{};
    std::optional<std::vector<GroundingChunk>> groundingChunks{};
    std::optional<std::vector<GoogleAiGenerativelanguageV1betaGroundingSupport>> groundingSupports{};
    std::optional<RetrievalMetadata> retrievalMetadata{};
    std::optional<std::vector<std::string>> webSearchQueries{};
    std::optional<std::vector<std::string>> imageSearchQueries{};
    std::optional<std::string> googleMapsWidgetContextToken{};
};

/** Attribution for a source that contributed to an answer. */
struct GroundingAttribution {
    std::optional<AttributionSourceId> sourceId{};
    std::optional<Content> content{};
};

/** Configuration options for model generation and outputs. Not all parameters are configurable for ever... */
struct GenerationConfig {
    std::optional<int64_t> candidateCount{};
    std::optional<std::vector<std::string>> stopSequences{};
    std::optional<int64_t> maxOutputTokens{};
    std::optional<double> temperature{};
    std::optional<double> topP{};
    std::optional<int64_t> topK{};
    std::optional<int64_t> seed{};
    std::optional<std::string> responseMimeType{};
    std::optional<Schema> responseSchema{};
    std::optional<jai::llm::json::Value> _responseJsonSchema{};
    std::optional<jai::llm::json::Value> responseJsonSchema{};
    std::optional<double> presencePenalty{};
    std::optional<double> frequencyPenalty{};
    std::optional<bool> responseLogprobs{};
    std::optional<int64_t> logprobs{};
    std::optional<bool> enableEnhancedCivicAnswers{};
    std::optional<std::vector<std::string>> responseModalities{};
    std::optional<SpeechConfig> speechConfig{};
    std::optional<ThinkingConfig> thinkingConfig{};
    std::optional<ImageConfig> imageConfig{};
    std::optional<MediaResolution> mediaResolution{};
};

/** A response candidate generated from the model. */
struct Candidate {
    std::optional<int64_t> index{};
    std::optional<Content> content{};
    std::optional<FinishReason> finishReason{};
    std::optional<std::string> finishMessage{};
    std::optional<std::vector<SafetyRating>> safetyRatings{};
    std::optional<CitationMetadata> citationMetadata{};
    std::optional<int64_t> tokenCount{};
    std::optional<std::vector<GroundingAttribution>> groundingAttributions{};
    std::optional<GroundingMetadata> groundingMetadata{};
    std::optional<double> avgLogprobs{};
    std::optional<LogprobsResult> logprobsResult{};
    std::optional<UrlContextMetadata> urlContextMetadata{};
};

/** Request to generate a completion from the model. */
struct GenerateContentRequest {
    Required<std::string> model;
    std::optional<Content> systemInstruction{};
    Required<std::vector<Content>> contents;
    std::optional<std::vector<Tool>> tools{};
    std::optional<ToolConfig> toolConfig{};
    std::optional<std::vector<SafetySetting>> safetySettings{};
    std::optional<GenerationConfig> generationConfig{};
    std::optional<std::string> cachedContent{};
};

/** Response from the model supporting multiple candidate responses. Safety ratings and content filterin... */
struct GenerateContentResponse {
    std::optional<std::vector<Candidate>> candidates{};
    std::optional<PromptFeedback> promptFeedback{};
    std::optional<UsageMetadata> usageMetadata{};
    std::optional<std::string> modelVersion{};
    std::optional<std::string> responseId{};
    std::optional<ModelStatus> modelStatus{};
};

using Request = GenerateContentRequest;
using Response = GenerateContentResponse;


} // namespace jai::llm::gemini
