// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#pragma once

#include "../../core/strings_base.hpp"
#include "../../core/error.hpp"
#include "generate_content.hpp"

namespace jai::llm {

template <>
constexpr std::optional<gemini::Behavior>
from_string_view<gemini::Behavior>(std::string_view sv) {
    if (sv == "UNSPECIFIED") return gemini::Behavior::UNSPECIFIED;
    if (sv == "BLOCKING") return gemini::Behavior::BLOCKING;
    if (sv == "NON_BLOCKING") return gemini::Behavior::NON_BLOCKING;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Behavior val) {
    switch (val) {
        case gemini::Behavior::UNSPECIFIED: return "UNSPECIFIED";
        case gemini::Behavior::BLOCKING: return "BLOCKING";
        case gemini::Behavior::NON_BLOCKING: return "NON_BLOCKING";
        default: throw AnnotatedException{"invalid gemini::Behavior"};
    }
}

template <>
constexpr std::optional<gemini::BlockReason>
from_string_view<gemini::BlockReason>(std::string_view sv) {
    if (sv == "BLOCK_REASON_UNSPECIFIED") return gemini::BlockReason::BLOCK_REASON_UNSPECIFIED;
    if (sv == "SAFETY") return gemini::BlockReason::SAFETY;
    if (sv == "OTHER") return gemini::BlockReason::OTHER;
    if (sv == "BLOCKLIST") return gemini::BlockReason::BLOCKLIST;
    if (sv == "PROHIBITED_CONTENT") return gemini::BlockReason::PROHIBITED_CONTENT;
    if (sv == "IMAGE_SAFETY") return gemini::BlockReason::IMAGE_SAFETY;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::BlockReason val) {
    switch (val) {
        case gemini::BlockReason::BLOCK_REASON_UNSPECIFIED: return "BLOCK_REASON_UNSPECIFIED";
        case gemini::BlockReason::SAFETY: return "SAFETY";
        case gemini::BlockReason::OTHER: return "OTHER";
        case gemini::BlockReason::BLOCKLIST: return "BLOCKLIST";
        case gemini::BlockReason::PROHIBITED_CONTENT: return "PROHIBITED_CONTENT";
        case gemini::BlockReason::IMAGE_SAFETY: return "IMAGE_SAFETY";
        default: throw AnnotatedException{"invalid gemini::BlockReason"};
    }
}

template <>
constexpr std::optional<gemini::Category>
from_string_view<gemini::Category>(std::string_view sv) {
    if (sv == "HARM_CATEGORY_UNSPECIFIED") return gemini::Category::HARM_CATEGORY_UNSPECIFIED;
    if (sv == "HARM_CATEGORY_DEROGATORY") return gemini::Category::HARM_CATEGORY_DEROGATORY;
    if (sv == "HARM_CATEGORY_TOXICITY") return gemini::Category::HARM_CATEGORY_TOXICITY;
    if (sv == "HARM_CATEGORY_VIOLENCE") return gemini::Category::HARM_CATEGORY_VIOLENCE;
    if (sv == "HARM_CATEGORY_SEXUAL") return gemini::Category::HARM_CATEGORY_SEXUAL;
    if (sv == "HARM_CATEGORY_MEDICAL") return gemini::Category::HARM_CATEGORY_MEDICAL;
    if (sv == "HARM_CATEGORY_DANGEROUS") return gemini::Category::HARM_CATEGORY_DANGEROUS;
    if (sv == "HARM_CATEGORY_HARASSMENT") return gemini::Category::HARM_CATEGORY_HARASSMENT;
    if (sv == "HARM_CATEGORY_HATE_SPEECH") return gemini::Category::HARM_CATEGORY_HATE_SPEECH;
    if (sv == "HARM_CATEGORY_SEXUALLY_EXPLICIT") return gemini::Category::HARM_CATEGORY_SEXUALLY_EXPLICIT;
    if (sv == "HARM_CATEGORY_DANGEROUS_CONTENT") return gemini::Category::HARM_CATEGORY_DANGEROUS_CONTENT;
    if (sv == "HARM_CATEGORY_CIVIC_INTEGRITY") return gemini::Category::HARM_CATEGORY_CIVIC_INTEGRITY;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Category val) {
    switch (val) {
        case gemini::Category::HARM_CATEGORY_UNSPECIFIED: return "HARM_CATEGORY_UNSPECIFIED";
        case gemini::Category::HARM_CATEGORY_DEROGATORY: return "HARM_CATEGORY_DEROGATORY";
        case gemini::Category::HARM_CATEGORY_TOXICITY: return "HARM_CATEGORY_TOXICITY";
        case gemini::Category::HARM_CATEGORY_VIOLENCE: return "HARM_CATEGORY_VIOLENCE";
        case gemini::Category::HARM_CATEGORY_SEXUAL: return "HARM_CATEGORY_SEXUAL";
        case gemini::Category::HARM_CATEGORY_MEDICAL: return "HARM_CATEGORY_MEDICAL";
        case gemini::Category::HARM_CATEGORY_DANGEROUS: return "HARM_CATEGORY_DANGEROUS";
        case gemini::Category::HARM_CATEGORY_HARASSMENT: return "HARM_CATEGORY_HARASSMENT";
        case gemini::Category::HARM_CATEGORY_HATE_SPEECH: return "HARM_CATEGORY_HATE_SPEECH";
        case gemini::Category::HARM_CATEGORY_SEXUALLY_EXPLICIT: return "HARM_CATEGORY_SEXUALLY_EXPLICIT";
        case gemini::Category::HARM_CATEGORY_DANGEROUS_CONTENT: return "HARM_CATEGORY_DANGEROUS_CONTENT";
        case gemini::Category::HARM_CATEGORY_CIVIC_INTEGRITY: return "HARM_CATEGORY_CIVIC_INTEGRITY";
        default: throw AnnotatedException{"invalid gemini::Category"};
    }
}

template <>
constexpr std::optional<gemini::DynamicRetrievalConfigMode>
from_string_view<gemini::DynamicRetrievalConfigMode>(std::string_view sv) {
    if (sv == "MODE_UNSPECIFIED") return gemini::DynamicRetrievalConfigMode::MODE_UNSPECIFIED;
    if (sv == "MODE_DYNAMIC") return gemini::DynamicRetrievalConfigMode::MODE_DYNAMIC;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::DynamicRetrievalConfigMode val) {
    switch (val) {
        case gemini::DynamicRetrievalConfigMode::MODE_UNSPECIFIED: return "MODE_UNSPECIFIED";
        case gemini::DynamicRetrievalConfigMode::MODE_DYNAMIC: return "MODE_DYNAMIC";
        default: throw AnnotatedException{"invalid gemini::DynamicRetrievalConfigMode"};
    }
}

template <>
constexpr std::optional<gemini::Environment>
from_string_view<gemini::Environment>(std::string_view sv) {
    if (sv == "ENVIRONMENT_UNSPECIFIED") return gemini::Environment::ENVIRONMENT_UNSPECIFIED;
    if (sv == "ENVIRONMENT_BROWSER") return gemini::Environment::ENVIRONMENT_BROWSER;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Environment val) {
    switch (val) {
        case gemini::Environment::ENVIRONMENT_UNSPECIFIED: return "ENVIRONMENT_UNSPECIFIED";
        case gemini::Environment::ENVIRONMENT_BROWSER: return "ENVIRONMENT_BROWSER";
        default: throw AnnotatedException{"invalid gemini::Environment"};
    }
}

template <>
constexpr std::optional<gemini::FinishReason>
from_string_view<gemini::FinishReason>(std::string_view sv) {
    if (sv == "FINISH_REASON_UNSPECIFIED") return gemini::FinishReason::FINISH_REASON_UNSPECIFIED;
    if (sv == "STOP") return gemini::FinishReason::STOP;
    if (sv == "MAX_TOKENS") return gemini::FinishReason::MAX_TOKENS;
    if (sv == "SAFETY") return gemini::FinishReason::SAFETY;
    if (sv == "RECITATION") return gemini::FinishReason::RECITATION;
    if (sv == "LANGUAGE") return gemini::FinishReason::LANGUAGE;
    if (sv == "OTHER") return gemini::FinishReason::OTHER;
    if (sv == "BLOCKLIST") return gemini::FinishReason::BLOCKLIST;
    if (sv == "PROHIBITED_CONTENT") return gemini::FinishReason::PROHIBITED_CONTENT;
    if (sv == "SPII") return gemini::FinishReason::SPII;
    if (sv == "MALFORMED_FUNCTION_CALL") return gemini::FinishReason::MALFORMED_FUNCTION_CALL;
    if (sv == "IMAGE_SAFETY") return gemini::FinishReason::IMAGE_SAFETY;
    if (sv == "IMAGE_PROHIBITED_CONTENT") return gemini::FinishReason::IMAGE_PROHIBITED_CONTENT;
    if (sv == "IMAGE_OTHER") return gemini::FinishReason::IMAGE_OTHER;
    if (sv == "NO_IMAGE") return gemini::FinishReason::NO_IMAGE;
    if (sv == "IMAGE_RECITATION") return gemini::FinishReason::IMAGE_RECITATION;
    if (sv == "UNEXPECTED_TOOL_CALL") return gemini::FinishReason::UNEXPECTED_TOOL_CALL;
    if (sv == "TOO_MANY_TOOL_CALLS") return gemini::FinishReason::TOO_MANY_TOOL_CALLS;
    if (sv == "MISSING_THOUGHT_SIGNATURE") return gemini::FinishReason::MISSING_THOUGHT_SIGNATURE;
    if (sv == "MALFORMED_RESPONSE") return gemini::FinishReason::MALFORMED_RESPONSE;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::FinishReason val) {
    switch (val) {
        case gemini::FinishReason::FINISH_REASON_UNSPECIFIED: return "FINISH_REASON_UNSPECIFIED";
        case gemini::FinishReason::STOP: return "STOP";
        case gemini::FinishReason::MAX_TOKENS: return "MAX_TOKENS";
        case gemini::FinishReason::SAFETY: return "SAFETY";
        case gemini::FinishReason::RECITATION: return "RECITATION";
        case gemini::FinishReason::LANGUAGE: return "LANGUAGE";
        case gemini::FinishReason::OTHER: return "OTHER";
        case gemini::FinishReason::BLOCKLIST: return "BLOCKLIST";
        case gemini::FinishReason::PROHIBITED_CONTENT: return "PROHIBITED_CONTENT";
        case gemini::FinishReason::SPII: return "SPII";
        case gemini::FinishReason::MALFORMED_FUNCTION_CALL: return "MALFORMED_FUNCTION_CALL";
        case gemini::FinishReason::IMAGE_SAFETY: return "IMAGE_SAFETY";
        case gemini::FinishReason::IMAGE_PROHIBITED_CONTENT: return "IMAGE_PROHIBITED_CONTENT";
        case gemini::FinishReason::IMAGE_OTHER: return "IMAGE_OTHER";
        case gemini::FinishReason::NO_IMAGE: return "NO_IMAGE";
        case gemini::FinishReason::IMAGE_RECITATION: return "IMAGE_RECITATION";
        case gemini::FinishReason::UNEXPECTED_TOOL_CALL: return "UNEXPECTED_TOOL_CALL";
        case gemini::FinishReason::TOO_MANY_TOOL_CALLS: return "TOO_MANY_TOOL_CALLS";
        case gemini::FinishReason::MISSING_THOUGHT_SIGNATURE: return "MISSING_THOUGHT_SIGNATURE";
        case gemini::FinishReason::MALFORMED_RESPONSE: return "MALFORMED_RESPONSE";
        default: throw AnnotatedException{"invalid gemini::FinishReason"};
    }
}

template <>
constexpr std::optional<gemini::FunctionCallingConfigMode>
from_string_view<gemini::FunctionCallingConfigMode>(std::string_view sv) {
    if (sv == "MODE_UNSPECIFIED") return gemini::FunctionCallingConfigMode::MODE_UNSPECIFIED;
    if (sv == "AUTO") return gemini::FunctionCallingConfigMode::AUTO;
    if (sv == "ANY") return gemini::FunctionCallingConfigMode::ANY;
    if (sv == "NONE") return gemini::FunctionCallingConfigMode::NONE;
    if (sv == "VALIDATED") return gemini::FunctionCallingConfigMode::VALIDATED;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::FunctionCallingConfigMode val) {
    switch (val) {
        case gemini::FunctionCallingConfigMode::MODE_UNSPECIFIED: return "MODE_UNSPECIFIED";
        case gemini::FunctionCallingConfigMode::AUTO: return "AUTO";
        case gemini::FunctionCallingConfigMode::ANY: return "ANY";
        case gemini::FunctionCallingConfigMode::NONE: return "NONE";
        case gemini::FunctionCallingConfigMode::VALIDATED: return "VALIDATED";
        default: throw AnnotatedException{"invalid gemini::FunctionCallingConfigMode"};
    }
}

template <>
constexpr std::optional<gemini::Language>
from_string_view<gemini::Language>(std::string_view sv) {
    if (sv == "LANGUAGE_UNSPECIFIED") return gemini::Language::LANGUAGE_UNSPECIFIED;
    if (sv == "PYTHON") return gemini::Language::PYTHON;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Language val) {
    switch (val) {
        case gemini::Language::LANGUAGE_UNSPECIFIED: return "LANGUAGE_UNSPECIFIED";
        case gemini::Language::PYTHON: return "PYTHON";
        default: throw AnnotatedException{"invalid gemini::Language"};
    }
}

template <>
constexpr std::optional<gemini::MediaResolution>
from_string_view<gemini::MediaResolution>(std::string_view sv) {
    if (sv == "MEDIA_RESOLUTION_UNSPECIFIED") return gemini::MediaResolution::MEDIA_RESOLUTION_UNSPECIFIED;
    if (sv == "MEDIA_RESOLUTION_LOW") return gemini::MediaResolution::MEDIA_RESOLUTION_LOW;
    if (sv == "MEDIA_RESOLUTION_MEDIUM") return gemini::MediaResolution::MEDIA_RESOLUTION_MEDIUM;
    if (sv == "MEDIA_RESOLUTION_HIGH") return gemini::MediaResolution::MEDIA_RESOLUTION_HIGH;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::MediaResolution val) {
    switch (val) {
        case gemini::MediaResolution::MEDIA_RESOLUTION_UNSPECIFIED: return "MEDIA_RESOLUTION_UNSPECIFIED";
        case gemini::MediaResolution::MEDIA_RESOLUTION_LOW: return "MEDIA_RESOLUTION_LOW";
        case gemini::MediaResolution::MEDIA_RESOLUTION_MEDIUM: return "MEDIA_RESOLUTION_MEDIUM";
        case gemini::MediaResolution::MEDIA_RESOLUTION_HIGH: return "MEDIA_RESOLUTION_HIGH";
        default: throw AnnotatedException{"invalid gemini::MediaResolution"};
    }
}

template <>
constexpr std::optional<gemini::Modality>
from_string_view<gemini::Modality>(std::string_view sv) {
    if (sv == "MODALITY_UNSPECIFIED") return gemini::Modality::MODALITY_UNSPECIFIED;
    if (sv == "TEXT") return gemini::Modality::TEXT;
    if (sv == "IMAGE") return gemini::Modality::IMAGE;
    if (sv == "VIDEO") return gemini::Modality::VIDEO;
    if (sv == "AUDIO") return gemini::Modality::AUDIO;
    if (sv == "DOCUMENT") return gemini::Modality::DOCUMENT;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Modality val) {
    switch (val) {
        case gemini::Modality::MODALITY_UNSPECIFIED: return "MODALITY_UNSPECIFIED";
        case gemini::Modality::TEXT: return "TEXT";
        case gemini::Modality::IMAGE: return "IMAGE";
        case gemini::Modality::VIDEO: return "VIDEO";
        case gemini::Modality::AUDIO: return "AUDIO";
        case gemini::Modality::DOCUMENT: return "DOCUMENT";
        default: throw AnnotatedException{"invalid gemini::Modality"};
    }
}

template <>
constexpr std::optional<gemini::ModelStage>
from_string_view<gemini::ModelStage>(std::string_view sv) {
    if (sv == "MODEL_STAGE_UNSPECIFIED") return gemini::ModelStage::MODEL_STAGE_UNSPECIFIED;
    if (sv == "UNSTABLE_EXPERIMENTAL") return gemini::ModelStage::UNSTABLE_EXPERIMENTAL;
    if (sv == "EXPERIMENTAL") return gemini::ModelStage::EXPERIMENTAL;
    if (sv == "PREVIEW") return gemini::ModelStage::PREVIEW;
    if (sv == "STABLE") return gemini::ModelStage::STABLE;
    if (sv == "LEGACY") return gemini::ModelStage::LEGACY;
    if (sv == "DEPRECATED") return gemini::ModelStage::DEPRECATED;
    if (sv == "RETIRED") return gemini::ModelStage::RETIRED;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::ModelStage val) {
    switch (val) {
        case gemini::ModelStage::MODEL_STAGE_UNSPECIFIED: return "MODEL_STAGE_UNSPECIFIED";
        case gemini::ModelStage::UNSTABLE_EXPERIMENTAL: return "UNSTABLE_EXPERIMENTAL";
        case gemini::ModelStage::EXPERIMENTAL: return "EXPERIMENTAL";
        case gemini::ModelStage::PREVIEW: return "PREVIEW";
        case gemini::ModelStage::STABLE: return "STABLE";
        case gemini::ModelStage::LEGACY: return "LEGACY";
        case gemini::ModelStage::DEPRECATED: return "DEPRECATED";
        case gemini::ModelStage::RETIRED: return "RETIRED";
        default: throw AnnotatedException{"invalid gemini::ModelStage"};
    }
}

template <>
constexpr std::optional<gemini::Outcome>
from_string_view<gemini::Outcome>(std::string_view sv) {
    if (sv == "OUTCOME_UNSPECIFIED") return gemini::Outcome::OUTCOME_UNSPECIFIED;
    if (sv == "OUTCOME_OK") return gemini::Outcome::OUTCOME_OK;
    if (sv == "OUTCOME_FAILED") return gemini::Outcome::OUTCOME_FAILED;
    if (sv == "OUTCOME_DEADLINE_EXCEEDED") return gemini::Outcome::OUTCOME_DEADLINE_EXCEEDED;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Outcome val) {
    switch (val) {
        case gemini::Outcome::OUTCOME_UNSPECIFIED: return "OUTCOME_UNSPECIFIED";
        case gemini::Outcome::OUTCOME_OK: return "OUTCOME_OK";
        case gemini::Outcome::OUTCOME_FAILED: return "OUTCOME_FAILED";
        case gemini::Outcome::OUTCOME_DEADLINE_EXCEEDED: return "OUTCOME_DEADLINE_EXCEEDED";
        default: throw AnnotatedException{"invalid gemini::Outcome"};
    }
}

template <>
constexpr std::optional<gemini::Probability>
from_string_view<gemini::Probability>(std::string_view sv) {
    if (sv == "HARM_PROBABILITY_UNSPECIFIED") return gemini::Probability::HARM_PROBABILITY_UNSPECIFIED;
    if (sv == "NEGLIGIBLE") return gemini::Probability::NEGLIGIBLE;
    if (sv == "LOW") return gemini::Probability::LOW;
    if (sv == "MEDIUM") return gemini::Probability::MEDIUM;
    if (sv == "HIGH") return gemini::Probability::HIGH;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Probability val) {
    switch (val) {
        case gemini::Probability::HARM_PROBABILITY_UNSPECIFIED: return "HARM_PROBABILITY_UNSPECIFIED";
        case gemini::Probability::NEGLIGIBLE: return "NEGLIGIBLE";
        case gemini::Probability::LOW: return "LOW";
        case gemini::Probability::MEDIUM: return "MEDIUM";
        case gemini::Probability::HIGH: return "HIGH";
        default: throw AnnotatedException{"invalid gemini::Probability"};
    }
}

template <>
constexpr std::optional<gemini::Scheduling>
from_string_view<gemini::Scheduling>(std::string_view sv) {
    if (sv == "SCHEDULING_UNSPECIFIED") return gemini::Scheduling::SCHEDULING_UNSPECIFIED;
    if (sv == "SILENT") return gemini::Scheduling::SILENT;
    if (sv == "WHEN_IDLE") return gemini::Scheduling::WHEN_IDLE;
    if (sv == "INTERRUPT") return gemini::Scheduling::INTERRUPT;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Scheduling val) {
    switch (val) {
        case gemini::Scheduling::SCHEDULING_UNSPECIFIED: return "SCHEDULING_UNSPECIFIED";
        case gemini::Scheduling::SILENT: return "SILENT";
        case gemini::Scheduling::WHEN_IDLE: return "WHEN_IDLE";
        case gemini::Scheduling::INTERRUPT: return "INTERRUPT";
        default: throw AnnotatedException{"invalid gemini::Scheduling"};
    }
}

template <>
constexpr std::optional<gemini::ServiceTier>
from_string_view<gemini::ServiceTier>(std::string_view sv) {
    if (sv == "unspecified") return gemini::ServiceTier::UNSPECIFIED;
    if (sv == "standard") return gemini::ServiceTier::STANDARD;
    if (sv == "flex") return gemini::ServiceTier::FLEX;
    if (sv == "priority") return gemini::ServiceTier::PRIORITY;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::ServiceTier val) {
    switch (val) {
        case gemini::ServiceTier::UNSPECIFIED: return "unspecified";
        case gemini::ServiceTier::STANDARD: return "standard";
        case gemini::ServiceTier::FLEX: return "flex";
        case gemini::ServiceTier::PRIORITY: return "priority";
        default: throw AnnotatedException{"invalid gemini::ServiceTier"};
    }
}

template <>
constexpr std::optional<gemini::ThinkingLevel>
from_string_view<gemini::ThinkingLevel>(std::string_view sv) {
    if (sv == "THINKING_LEVEL_UNSPECIFIED") return gemini::ThinkingLevel::THINKING_LEVEL_UNSPECIFIED;
    if (sv == "MINIMAL") return gemini::ThinkingLevel::MINIMAL;
    if (sv == "LOW") return gemini::ThinkingLevel::LOW;
    if (sv == "MEDIUM") return gemini::ThinkingLevel::MEDIUM;
    if (sv == "HIGH") return gemini::ThinkingLevel::HIGH;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::ThinkingLevel val) {
    switch (val) {
        case gemini::ThinkingLevel::THINKING_LEVEL_UNSPECIFIED: return "THINKING_LEVEL_UNSPECIFIED";
        case gemini::ThinkingLevel::MINIMAL: return "MINIMAL";
        case gemini::ThinkingLevel::LOW: return "LOW";
        case gemini::ThinkingLevel::MEDIUM: return "MEDIUM";
        case gemini::ThinkingLevel::HIGH: return "HIGH";
        default: throw AnnotatedException{"invalid gemini::ThinkingLevel"};
    }
}

template <>
constexpr std::optional<gemini::Threshold>
from_string_view<gemini::Threshold>(std::string_view sv) {
    if (sv == "HARM_BLOCK_THRESHOLD_UNSPECIFIED") return gemini::Threshold::HARM_BLOCK_THRESHOLD_UNSPECIFIED;
    if (sv == "BLOCK_LOW_AND_ABOVE") return gemini::Threshold::BLOCK_LOW_AND_ABOVE;
    if (sv == "BLOCK_MEDIUM_AND_ABOVE") return gemini::Threshold::BLOCK_MEDIUM_AND_ABOVE;
    if (sv == "BLOCK_ONLY_HIGH") return gemini::Threshold::BLOCK_ONLY_HIGH;
    if (sv == "BLOCK_NONE") return gemini::Threshold::BLOCK_NONE;
    if (sv == "OFF") return gemini::Threshold::OFF;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Threshold val) {
    switch (val) {
        case gemini::Threshold::HARM_BLOCK_THRESHOLD_UNSPECIFIED: return "HARM_BLOCK_THRESHOLD_UNSPECIFIED";
        case gemini::Threshold::BLOCK_LOW_AND_ABOVE: return "BLOCK_LOW_AND_ABOVE";
        case gemini::Threshold::BLOCK_MEDIUM_AND_ABOVE: return "BLOCK_MEDIUM_AND_ABOVE";
        case gemini::Threshold::BLOCK_ONLY_HIGH: return "BLOCK_ONLY_HIGH";
        case gemini::Threshold::BLOCK_NONE: return "BLOCK_NONE";
        case gemini::Threshold::OFF: return "OFF";
        default: throw AnnotatedException{"invalid gemini::Threshold"};
    }
}

template <>
constexpr std::optional<gemini::ToolType>
from_string_view<gemini::ToolType>(std::string_view sv) {
    if (sv == "TOOL_TYPE_UNSPECIFIED") return gemini::ToolType::TOOL_TYPE_UNSPECIFIED;
    if (sv == "GOOGLE_SEARCH_WEB") return gemini::ToolType::GOOGLE_SEARCH_WEB;
    if (sv == "GOOGLE_SEARCH_IMAGE") return gemini::ToolType::GOOGLE_SEARCH_IMAGE;
    if (sv == "URL_CONTEXT") return gemini::ToolType::URL_CONTEXT;
    if (sv == "GOOGLE_MAPS") return gemini::ToolType::GOOGLE_MAPS;
    if (sv == "FILE_SEARCH") return gemini::ToolType::FILE_SEARCH;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::ToolType val) {
    switch (val) {
        case gemini::ToolType::TOOL_TYPE_UNSPECIFIED: return "TOOL_TYPE_UNSPECIFIED";
        case gemini::ToolType::GOOGLE_SEARCH_WEB: return "GOOGLE_SEARCH_WEB";
        case gemini::ToolType::GOOGLE_SEARCH_IMAGE: return "GOOGLE_SEARCH_IMAGE";
        case gemini::ToolType::URL_CONTEXT: return "URL_CONTEXT";
        case gemini::ToolType::GOOGLE_MAPS: return "GOOGLE_MAPS";
        case gemini::ToolType::FILE_SEARCH: return "FILE_SEARCH";
        default: throw AnnotatedException{"invalid gemini::ToolType"};
    }
}

template <>
constexpr std::optional<gemini::Type>
from_string_view<gemini::Type>(std::string_view sv) {
    if (sv == "TYPE_UNSPECIFIED") return gemini::Type::TYPE_UNSPECIFIED;
    if (sv == "STRING") return gemini::Type::STRING;
    if (sv == "NUMBER") return gemini::Type::NUMBER;
    if (sv == "INTEGER") return gemini::Type::INTEGER;
    if (sv == "BOOLEAN") return gemini::Type::BOOLEAN;
    if (sv == "ARRAY") return gemini::Type::ARRAY;
    if (sv == "OBJECT") return gemini::Type::OBJECT;
    if (sv == "NULL") return gemini::Type::NULL_T;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::Type val) {
    switch (val) {
        case gemini::Type::TYPE_UNSPECIFIED: return "TYPE_UNSPECIFIED";
        case gemini::Type::STRING: return "STRING";
        case gemini::Type::NUMBER: return "NUMBER";
        case gemini::Type::INTEGER: return "INTEGER";
        case gemini::Type::BOOLEAN: return "BOOLEAN";
        case gemini::Type::ARRAY: return "ARRAY";
        case gemini::Type::OBJECT: return "OBJECT";
        case gemini::Type::NULL_T: return "NULL";
        default: throw AnnotatedException{"invalid gemini::Type"};
    }
}

template <>
constexpr std::optional<gemini::UrlRetrievalStatus>
from_string_view<gemini::UrlRetrievalStatus>(std::string_view sv) {
    if (sv == "URL_RETRIEVAL_STATUS_UNSPECIFIED") return gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_UNSPECIFIED;
    if (sv == "URL_RETRIEVAL_STATUS_SUCCESS") return gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_SUCCESS;
    if (sv == "URL_RETRIEVAL_STATUS_ERROR") return gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_ERROR;
    if (sv == "URL_RETRIEVAL_STATUS_PAYWALL") return gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_PAYWALL;
    if (sv == "URL_RETRIEVAL_STATUS_UNSAFE") return gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_UNSAFE;
    return std::nullopt;
}

constexpr std::string_view to_string_view(gemini::UrlRetrievalStatus val) {
    switch (val) {
        case gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_UNSPECIFIED: return "URL_RETRIEVAL_STATUS_UNSPECIFIED";
        case gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_SUCCESS: return "URL_RETRIEVAL_STATUS_SUCCESS";
        case gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_ERROR: return "URL_RETRIEVAL_STATUS_ERROR";
        case gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_PAYWALL: return "URL_RETRIEVAL_STATUS_PAYWALL";
        case gemini::UrlRetrievalStatus::URL_RETRIEVAL_STATUS_UNSAFE: return "URL_RETRIEVAL_STATUS_UNSAFE";
        default: throw AnnotatedException{"invalid gemini::UrlRetrievalStatus"};
    }
}

} // namespace jai::llm
