// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/anthropic/messages.hpp"
#include "base.hpp"

using namespace simdjson::builder;

namespace jai::llm::anthropic {

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ImageBlockParam::Base64ImageSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ImageBlockParam::URLImageSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ImageBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ImageBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::Base64PDFSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::PlainTextSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::Base64ImageSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::URLImageSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::ContentBlockSource)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::URLPDFSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::DocumentBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
    FIELD(obj, context, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::SearchResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ThinkingBlockParam)
    FIELD(obj, signature, CommaDirection::NONE)
    FIELD(obj, thinking, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::RedactedThinkingBlockParam)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolUseBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolUseBlockParam::DirectCaller)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolUseBlockParam::ServerToolCaller)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolUseBlockParam::ServerToolCaller20260120)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolUseBlockParam)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, input, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, caller, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ImageBlockParam::Base64ImageSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ImageBlockParam::URLImageSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ImageBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ImageBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::SearchResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::Base64PDFSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::PlainTextSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::Base64ImageSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::URLImageSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::ContentBlockSource)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::URLPDFSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::DocumentBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
    FIELD(obj, context, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ToolReferenceBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam::ToolReferenceBlockParam)
    FIELD(obj, tool_name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolResultBlockParam)
    FIELD(obj, tool_use_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, content, CommaDirection::BEFORE)
    FIELD(obj, is_error, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ServerToolUseBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ServerToolUseBlockParam::DirectCaller)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ServerToolUseBlockParam::ServerToolCaller)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ServerToolUseBlockParam::ServerToolCaller20260120)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ServerToolUseBlockParam)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, input, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, caller, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::WebSearchResultBlockParam)
    FIELD(obj, encrypted_content, CommaDirection::NONE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
    FIELD(obj, page_age, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::WebSearchToolRequestError)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::DirectCaller)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::ServerToolCaller)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam::ServerToolCaller20260120)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebSearchToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, caller, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchToolResultErrorBlockParam)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::Base64PDFSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::PlainTextSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::Base64ImageSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::URLImageSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource::ImageBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::ContentBlockSource)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::URLPDFSource)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam::DocumentBlockParam)
    FIELD(obj, source, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
    FIELD(obj, context, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::WebFetchBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
    FIELD(obj, retrieved_at, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::DirectCaller)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::ServerToolCaller)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam::ServerToolCaller20260120)
    FIELD(obj, tool_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::WebFetchToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, caller, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::CodeExecutionToolResultErrorParam)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::CodeExecutionResultBlockParam::CodeExecutionOutputBlockParam)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::CodeExecutionResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, return_code, CommaDirection::BEFORE)
    FIELD_ALT(obj, stderr_, "stderr", CommaDirection::BEFORE)
    FIELD_ALT(obj, stdout_, "stdout", CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::EncryptedCodeExecutionResultBlockParam::CodeExecutionOutputBlockParam)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::EncryptedCodeExecutionResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, encrypted_stdout, CommaDirection::BEFORE)
    FIELD(obj, return_code, CommaDirection::BEFORE)
    FIELD_ALT(obj, stderr_, "stderr", CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::CodeExecutionToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::BashCodeExecutionToolResultBlockParam::BashCodeExecutionToolResultErrorParam)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::BashCodeExecutionToolResultBlockParam::BashCodeExecutionResultBlockParam::BashCodeExecutionOutputBlockParam)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::BashCodeExecutionToolResultBlockParam::BashCodeExecutionResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, return_code, CommaDirection::BEFORE)
    FIELD_ALT(obj, stderr_, "stderr", CommaDirection::BEFORE)
    FIELD_ALT(obj, stdout_, "stdout", CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::BashCodeExecutionToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::BashCodeExecutionToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam::TextEditorCodeExecutionToolResultErrorParam)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, error_message, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam::TextEditorCodeExecutionViewResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, file_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, num_lines, CommaDirection::BEFORE)
    FIELD(obj, start_line, CommaDirection::BEFORE)
    FIELD(obj, total_lines, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam::TextEditorCodeExecutionCreateResultBlockParam)
    FIELD(obj, is_file_update, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam::TextEditorCodeExecutionStrReplaceResultBlockParam)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, lines, CommaDirection::BEFORE)
    FIELD(obj, new_lines, CommaDirection::BEFORE)
    FIELD(obj, new_start, CommaDirection::BEFORE)
    FIELD(obj, old_lines, CommaDirection::BEFORE)
    FIELD(obj, old_start, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::TextEditorCodeExecutionToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam::ToolSearchToolResultErrorParam)
    FIELD(obj, error_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam::ToolSearchToolSearchResultBlockParam::ToolReferenceBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam::ToolSearchToolSearchResultBlockParam::ToolReferenceBlockParam)
    FIELD(obj, tool_name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam::ToolSearchToolSearchResultBlockParam)
    FIELD(obj, tool_references, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ToolSearchToolResultBlockParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, tool_use_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ContainerUploadBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam::ContainerUploadBlockParam)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MessageParam)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, role, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Metadata)
    FIELD(obj, user_id, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::OutputConfig::JSONOutputFormat)
    FIELD(obj, schema, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::OutputConfig)
    FIELD(obj, effort, CommaDirection::NONE)
    FIELD(obj, format, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CitationCharLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_char_index, CommaDirection::BEFORE)
    FIELD(obj, start_char_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CitationPageLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_page_number, CommaDirection::BEFORE)
    FIELD(obj, start_page_number, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CitationContentBlockLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, document_index, CommaDirection::BEFORE)
    FIELD(obj, document_title, CommaDirection::BEFORE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CitationWebSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, encrypted_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam::CitationSearchResultLocationParam)
    FIELD(obj, cited_text, CommaDirection::NONE)
    FIELD(obj, end_block_index, CommaDirection::BEFORE)
    FIELD(obj, search_result_index, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, start_block_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::TextBlockParam)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ThinkingConfigEnabled)
    FIELD(obj, budget_tokens, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ThinkingConfigDisabled)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ThinkingConfigAdaptive)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceAuto)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, disable_parallel_tool_use, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceAny)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, disable_parallel_tool_use, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceTool)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, disable_parallel_tool_use, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceNone)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Tool::Tool_input_schema)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, properties, CommaDirection::BEFORE)
    FIELD(obj, required, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Tool::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Tool)
    FIELD(obj, input_schema, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
    FIELD(obj, eager_input_streaming, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolBash20250124::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolBash20250124)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20250522::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20250522)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20250825::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20250825)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20260120::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeExecutionTool20260120)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MemoryTool20250818::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::MemoryTool20250818)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250124::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250124)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250429::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250429)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250728::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolTextEditor20250728)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, input_examples, CommaDirection::BEFORE)
    FIELD(obj, max_characters, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20250305::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20250305::UserLocation)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, city, CommaDirection::BEFORE)
    FIELD(obj, country, CommaDirection::BEFORE)
    FIELD(obj, region, CommaDirection::BEFORE)
    FIELD(obj, timezone, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20250305)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, allowed_domains, CommaDirection::BEFORE)
    FIELD(obj, blocked_domains, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, max_uses, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
    FIELD(obj, user_location, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20250910::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20250910::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20250910)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, allowed_domains, CommaDirection::BEFORE)
    FIELD(obj, blocked_domains, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, max_content_tokens, CommaDirection::BEFORE)
    FIELD(obj, max_uses, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20260209::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20260209::UserLocation)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, city, CommaDirection::BEFORE)
    FIELD(obj, country, CommaDirection::BEFORE)
    FIELD(obj, region, CommaDirection::BEFORE)
    FIELD(obj, timezone, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool20260209)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, allowed_domains, CommaDirection::BEFORE)
    FIELD(obj, blocked_domains, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, max_uses, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
    FIELD(obj, user_location, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20260209::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20260209::CitationsConfigParam)
    FIELD(obj, enabled, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebFetchTool20260209)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, allowed_domains, CommaDirection::BEFORE)
    FIELD(obj, blocked_domains, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, citations, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, max_content_tokens, CommaDirection::BEFORE)
    FIELD(obj, max_uses, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolSearchToolBm25_20251119::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolSearchToolBm25_20251119)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolSearchToolRegex20251119::CacheControlEphemeral)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, ttl, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolSearchToolRegex20251119)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_callers, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, defer_loading, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request)
    FIELD(obj, max_tokens, CommaDirection::NONE)
    FIELD(obj, messages, CommaDirection::BEFORE)
    FIELD(obj, model, CommaDirection::BEFORE)
    FIELD(obj, cache_control, CommaDirection::BEFORE)
    FIELD(obj, container, CommaDirection::BEFORE)
    FIELD(obj, inference_geo, CommaDirection::BEFORE)
    FIELD(obj, metadata, CommaDirection::BEFORE)
    FIELD(obj, output_config, CommaDirection::BEFORE)
    FIELD(obj, service_tier, CommaDirection::BEFORE)
    FIELD(obj, stop_sequences, CommaDirection::BEFORE)
    FIELD(obj, stream, CommaDirection::BEFORE)
    FIELD(obj, system, CommaDirection::BEFORE)
    FIELD(obj, temperature, CommaDirection::BEFORE)
    FIELD(obj, thinking, CommaDirection::BEFORE)
    FIELD(obj, tool_choice, CommaDirection::BEFORE)
    FIELD(obj, tools, CommaDirection::BEFORE)
    FIELD(obj, top_k, CommaDirection::BEFORE)
    FIELD(obj, top_p, CommaDirection::BEFORE)
END_SERIALIZE

/***
 * Top-level Serialize
 */
std::vector<std::byte> Serialize(const Request& request) {
    static thread_local string_builder builder{};

    try {
        builder.clear();
        SerializeFrom(builder, request);

        if (!builder.validate_unicode()) {
            throw AnnotatedException{"Serialize Failed", "string_builder generated invalid unicode data."};
        }

        auto result = builder.view();
        if (result.error() != simdjson::SUCCESS) {
            throw AnnotatedException{"Serialize Failed", simdjson::error_message(result.error())};
        }
        std::string_view json_str = result.value();

        return json_str |
               std::views::transform([](auto const& c) { return static_cast<std::byte>(c); }) |
               std::ranges::to<std::vector<std::byte>>();
    } catch (AnnotatedException const&) {
        throw;
    } catch (std::exception const& e) {
        AnnotatedException ex{"Serialize Failed"};
        ex.AddContext(e.what());
        throw ex;
    }
}

} // namespace jai::llm::anthropic
