// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/gemini/generate_content.hpp"
#include "../../../interface/protocols/gemini/generate_content_strings.hpp"
#include "base.hpp"

using namespace simdjson::builder;

namespace jai::llm::gemini {

BEGIN_SERIALIZE(Blob)
    FIELD(obj, mimeType, CommaDirection::NONE)
    FIELD(obj, data, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE_EMPTY(CodeExecution)
END_SERIALIZE

BEGIN_SERIALIZE(CodeExecutionResult)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, outcome, CommaDirection::BEFORE)
    FIELD(obj, output, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ComputerUse)
    FIELD(obj, environment, CommaDirection::NONE)
    FIELD(obj, excludedPredefinedFunctions, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(DynamicRetrievalConfig)
    FIELD(obj, mode, CommaDirection::NONE)
    FIELD(obj, dynamicThreshold, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ExecutableCode)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, language, CommaDirection::BEFORE)
    FIELD(obj, code, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FileData)
    FIELD(obj, mimeType, CommaDirection::NONE)
    FIELD(obj, fileUri, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FileSearch)
    FIELD(obj, fileSearchStoreNames, CommaDirection::NONE)
    FIELD(obj, topK, CommaDirection::BEFORE)
    FIELD(obj, metadataFilter, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, args, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionCallingConfig)
    FIELD(obj, mode, CommaDirection::NONE)
    FIELD(obj, allowedFunctionNames, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionResponseBlob)
    FIELD(obj, mimeType, CommaDirection::NONE)
    FIELD(obj, data, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(GoogleMaps)
    FIELD(obj, enableWidget, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(ImageConfig)
    FIELD(obj, aspectRatio, CommaDirection::NONE)
    FIELD(obj, imageSize, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE_EMPTY(ImageSearch)
END_SERIALIZE

BEGIN_SERIALIZE(Interval)
    FIELD(obj, startTime, CommaDirection::NONE)
    FIELD(obj, endTime, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(LatLng)
    FIELD(obj, latitude, CommaDirection::NONE)
    FIELD(obj, longitude, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(PrebuiltVoiceConfig)
    FIELD(obj, voiceName, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(SafetySetting)
    FIELD(obj, category, CommaDirection::NONE)
    FIELD(obj, threshold, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Schema)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, format, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
    FIELD(obj, nullable, CommaDirection::BEFORE)
    FIELD_ALT(obj, enum_value, "enum", CommaDirection::BEFORE)
    FIELD(obj, items, CommaDirection::BEFORE)
    FIELD(obj, maxItems, CommaDirection::BEFORE)
    FIELD(obj, minItems, CommaDirection::BEFORE)
    FIELD(obj, properties, CommaDirection::BEFORE)
    FIELD(obj, required, CommaDirection::BEFORE)
    FIELD(obj, minProperties, CommaDirection::BEFORE)
    FIELD(obj, maxProperties, CommaDirection::BEFORE)
    FIELD(obj, minimum, CommaDirection::BEFORE)
    FIELD(obj, maximum, CommaDirection::BEFORE)
    FIELD(obj, minLength, CommaDirection::BEFORE)
    FIELD(obj, maxLength, CommaDirection::BEFORE)
    FIELD(obj, pattern, CommaDirection::BEFORE)
    FIELD(obj, example, CommaDirection::BEFORE)
    FIELD(obj, anyOf, CommaDirection::BEFORE)
    FIELD(obj, propertyOrdering, CommaDirection::BEFORE)
    FIELD_ALT(obj, default_value, "default", CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(StreamableHttpTransport)
    FIELD(obj, url, CommaDirection::NONE)
    FIELD(obj, headers, CommaDirection::BEFORE)
    FIELD(obj, timeout, CommaDirection::BEFORE)
    FIELD(obj, sseReadTimeout, CommaDirection::BEFORE)
    FIELD(obj, terminateOnClose, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ThinkingConfig)
    FIELD(obj, includeThoughts, CommaDirection::NONE)
    FIELD(obj, thinkingBudget, CommaDirection::BEFORE)
    FIELD(obj, thinkingLevel, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ToolCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, toolType, CommaDirection::BEFORE)
    FIELD(obj, args, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ToolResponse)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, toolType, CommaDirection::BEFORE)
    FIELD(obj, response, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE_EMPTY(UrlContext)
END_SERIALIZE

BEGIN_SERIALIZE_EMPTY(WebSearch)
END_SERIALIZE

BEGIN_SERIALIZE(GoogleSearchRetrieval)
    FIELD(obj, dynamicRetrievalConfig, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionResponsePart)
    FIELD(obj, inlineData, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(RetrievalConfig)
    FIELD(obj, latLng, CommaDirection::NONE)
    FIELD(obj, languageCode, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(VoiceConfig)
    FIELD(obj, prebuiltVoiceConfig, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionDeclaration)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, description, CommaDirection::BEFORE)
    FIELD(obj, parameters, CommaDirection::BEFORE)
    FIELD(obj, parametersJsonSchema, CommaDirection::BEFORE)
    FIELD(obj, response, CommaDirection::BEFORE)
    FIELD(obj, responseJsonSchema, CommaDirection::BEFORE)
    FIELD(obj, behavior, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(McpServer)
    FIELD(obj, streamableHttpTransport, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(SearchTypes)
    FIELD(obj, webSearch, CommaDirection::NONE)
    FIELD(obj, imageSearch, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(FunctionResponse)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, response, CommaDirection::BEFORE)
    FIELD(obj, parts, CommaDirection::BEFORE)
    FIELD(obj, willContinue, CommaDirection::BEFORE)
    FIELD(obj, scheduling, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(ToolConfig)
    FIELD(obj, functionCallingConfig, CommaDirection::NONE)
    FIELD(obj, retrievalConfig, CommaDirection::BEFORE)
    FIELD(obj, includeServerSideToolInvocations, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(SpeakerVoiceConfig)
    FIELD(obj, speaker, CommaDirection::NONE)
    FIELD(obj, voiceConfig, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(GoogleSearch)
    FIELD(obj, timeRangeFilter, CommaDirection::NONE)
    FIELD(obj, searchTypes, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Part)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, inlineData, CommaDirection::BEFORE)
    FIELD(obj, functionCall, CommaDirection::BEFORE)
    FIELD(obj, functionResponse, CommaDirection::BEFORE)
    FIELD(obj, fileData, CommaDirection::BEFORE)
    FIELD(obj, executableCode, CommaDirection::BEFORE)
    FIELD(obj, codeExecutionResult, CommaDirection::BEFORE)
    FIELD(obj, toolCall, CommaDirection::BEFORE)
    FIELD(obj, toolResponse, CommaDirection::BEFORE)
    FIELD(obj, thought, CommaDirection::BEFORE)
    FIELD(obj, thoughtSignature, CommaDirection::BEFORE)
    FIELD(obj, partMetadata, CommaDirection::BEFORE)
    FIELD(obj, mediaResolution, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(MultiSpeakerVoiceConfig)
    FIELD(obj, speakerVoiceConfigs, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Tool)
    FIELD(obj, functionDeclarations, CommaDirection::NONE)
    FIELD(obj, googleSearchRetrieval, CommaDirection::BEFORE)
    FIELD(obj, codeExecution, CommaDirection::BEFORE)
    FIELD(obj, googleSearch, CommaDirection::BEFORE)
    FIELD(obj, computerUse, CommaDirection::BEFORE)
    FIELD(obj, urlContext, CommaDirection::BEFORE)
    FIELD(obj, fileSearch, CommaDirection::BEFORE)
    FIELD(obj, mcpServers, CommaDirection::BEFORE)
    FIELD(obj, googleMaps, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Content)
    FIELD(obj, parts, CommaDirection::NONE)
    FIELD(obj, role, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(SpeechConfig)
    FIELD(obj, voiceConfig, CommaDirection::NONE)
    FIELD(obj, multiSpeakerVoiceConfig, CommaDirection::BEFORE)
    FIELD(obj, languageCode, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(GenerationConfig)
    FIELD(obj, candidateCount, CommaDirection::NONE)
    FIELD(obj, stopSequences, CommaDirection::BEFORE)
    FIELD(obj, maxOutputTokens, CommaDirection::BEFORE)
    FIELD(obj, temperature, CommaDirection::BEFORE)
    FIELD(obj, topP, CommaDirection::BEFORE)
    FIELD(obj, topK, CommaDirection::BEFORE)
    FIELD(obj, seed, CommaDirection::BEFORE)
    FIELD(obj, responseMimeType, CommaDirection::BEFORE)
    FIELD(obj, responseSchema, CommaDirection::BEFORE)
    FIELD(obj, _responseJsonSchema, CommaDirection::BEFORE)
    FIELD(obj, responseJsonSchema, CommaDirection::BEFORE)
    FIELD(obj, presencePenalty, CommaDirection::BEFORE)
    FIELD(obj, frequencyPenalty, CommaDirection::BEFORE)
    FIELD(obj, responseLogprobs, CommaDirection::BEFORE)
    FIELD(obj, logprobs, CommaDirection::BEFORE)
    FIELD(obj, enableEnhancedCivicAnswers, CommaDirection::BEFORE)
    FIELD(obj, responseModalities, CommaDirection::BEFORE)
    FIELD(obj, speechConfig, CommaDirection::BEFORE)
    FIELD(obj, thinkingConfig, CommaDirection::BEFORE)
    FIELD(obj, imageConfig, CommaDirection::BEFORE)
    FIELD(obj, mediaResolution, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(GenerateContentRequest)
    FIELD(obj, model, CommaDirection::NONE)
    FIELD(obj, systemInstruction, CommaDirection::BEFORE)
    FIELD(obj, contents, CommaDirection::BEFORE)
    FIELD(obj, tools, CommaDirection::BEFORE)
    FIELD(obj, toolConfig, CommaDirection::BEFORE)
    FIELD(obj, safetySettings, CommaDirection::BEFORE)
    FIELD(obj, generationConfig, CommaDirection::BEFORE)
    FIELD(obj, cachedContent, CommaDirection::BEFORE)
    FIELD(obj, serviceTier, CommaDirection::BEFORE)
    FIELD(obj, store, CommaDirection::BEFORE)
END_SERIALIZE

/***
 * Top-level Serialize
 */
std::vector<std::byte> Serialize(const Request& request) {
    static thread_local string_builder builder{};

    try {
        builder.clear();
        SerializeFrom(builder, request);

        if (!builder.validate_unicode()) {
            throw AnnotatedException{"Serialize Failed", "string_builder generated invalid unicode data."};
        }

        auto result = builder.view();
        if (result.error() != simdjson::SUCCESS) {
            throw AnnotatedException{"Serialize Failed", simdjson::error_message(result.error())};
        }
        std::string_view json_str = result.value();

        return json_str |
               std::views::transform([](auto const& c) { return static_cast<std::byte>(c); }) |
               std::ranges::to<std::vector<std::byte>>();
    } catch (AnnotatedException const&) {
        throw;
    } catch (std::exception const& e) {
        AnnotatedException ex{"Serialize Failed"};
        ex.AddContext(e.what());
        throw ex;
    }
}

} // namespace jai::llm::gemini
