// ============================================================================
// AUTO-GENERATED — DO NOT EDIT
//
// Generated by scripts/api_parity.  Changes will be overwritten on the next
// audit run.  To modify the output, edit the codegen scripts instead.
// ============================================================================

#include "../../../interface/protocols/openai/responses.hpp"
#include "../../../interface/protocols/openai/responses_strings.hpp"
#include "base.hpp"

using namespace simdjson::builder;

namespace jai::llm::openai {

BEGIN_SERIALIZE(Request::Request_context_management)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, compact_threshold, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseConversationParam)
    FIELD(obj, id, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::EasyInputMessage::ResponseInputText)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::EasyInputMessage::ResponseInputImage)
    FIELD(obj, detail, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::EasyInputMessage::ResponseInputFile)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_data, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, file_url, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::EasyInputMessage)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, role, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Message::ResponseInputText)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Message::ResponseInputImage)
    FIELD(obj, detail, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Message::ResponseInputFile)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_data, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, file_url, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Message)
    FIELD(obj, content, CommaDirection::NONE)
    FIELD(obj, role, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::FileCitation)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, filename, CommaDirection::BEFORE)
    FIELD(obj, index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::URLCitation)
    FIELD(obj, end_index, CommaDirection::NONE)
    FIELD(obj, start_index, CommaDirection::BEFORE)
    FIELD(obj, title, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::ContainerFileCitation)
    FIELD(obj, container_id, CommaDirection::NONE)
    FIELD(obj, end_index, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
    FIELD(obj, start_index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::FilePath)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, index, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::ResponseOutputText_logprobs::ResponseOutputText_logprobs_top_logprobs)
    FIELD(obj, token, CommaDirection::NONE)
    FIELD(obj, bytes, CommaDirection::BEFORE)
    FIELD(obj, logprob, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText::ResponseOutputText_logprobs)
    FIELD(obj, token, CommaDirection::NONE)
    FIELD(obj, bytes, CommaDirection::BEFORE)
    FIELD(obj, logprob, CommaDirection::BEFORE)
    FIELD(obj, top_logprobs, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputText)
    FIELD(obj, annotations, CommaDirection::NONE)
    FIELD(obj, logprobs, CommaDirection::BEFORE)
    FIELD(obj, text, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage::ResponseOutputRefusal)
    FIELD(obj, refusal, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseOutputMessage)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, content, CommaDirection::BEFORE)
    FIELD(obj, role, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFileSearchToolCall::ResponseFileSearchToolCall_results)
    FIELD(obj, attributes, CommaDirection::NONE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
    FIELD(obj, score, CommaDirection::BEFORE)
    FIELD(obj, text, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFileSearchToolCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, queries, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, results, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Click)
    FIELD(obj, button, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, x, CommaDirection::BEFORE)
    FIELD(obj, y, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::DoubleClick)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, x, CommaDirection::BEFORE)
    FIELD(obj, y, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Drag::Drag_path)
    FIELD(obj, x, CommaDirection::NONE)
    FIELD(obj, y, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Drag)
    FIELD(obj, path, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Keypress)
    FIELD(obj, keys, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Move)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, x, CommaDirection::BEFORE)
    FIELD(obj, y, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Screenshot)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Scroll)
    FIELD(obj, scroll_x, CommaDirection::NONE)
    FIELD(obj, scroll_y, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, x, CommaDirection::BEFORE)
    FIELD(obj, y, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Type)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::Wait)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall::ResponseComputerToolCall_pending_safety_checks)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, code, CommaDirection::BEFORE)
    FIELD(obj, message, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseComputerToolCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, action, CommaDirection::BEFORE)
    FIELD(obj, call_id, CommaDirection::BEFORE)
    FIELD(obj, pending_safety_checks, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ComputerCallOutput::ResponseComputerToolCallOutputScreenshot)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ComputerCallOutput::ComputerCallOutput_acknowledged_safety_checks)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, code, CommaDirection::BEFORE)
    FIELD(obj, message, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ComputerCallOutput)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, acknowledged_safety_checks, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionWebSearch::Search::Search_sources)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionWebSearch::Search)
    FIELD(obj, query, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, queries, CommaDirection::BEFORE)
    FIELD(obj, sources, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionWebSearch::OpenPage)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionWebSearch::FindInPage)
    FIELD(obj, pattern, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionWebSearch)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, action, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseFunctionToolCall)
    FIELD(obj, arguments, CommaDirection::NONE)
    FIELD(obj, call_id, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionCallOutput::ResponseInputTextContent)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionCallOutput::ResponseInputImageContent)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, detail, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionCallOutput::ResponseInputFileContent)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_data, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, file_url, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionCallOutput)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseReasoningItem::SummaryTextContent)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseReasoningItem::ResponseReasoningItem_content)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseReasoningItem)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, summary, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, content, CommaDirection::BEFORE)
    FIELD(obj, encrypted_content, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCompactionItemParam)
    FIELD(obj, encrypted_content, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ImageGenerationCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, result, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCodeInterpreterToolCall::Logs)
    FIELD(obj, logs, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCodeInterpreterToolCall::Image)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCodeInterpreterToolCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, code, CommaDirection::BEFORE)
    FIELD(obj, container_id, CommaDirection::BEFORE)
    FIELD(obj, outputs, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::LocalShellCall::LocalShellCall_action)
    FIELD(obj, command, CommaDirection::NONE)
    FIELD(obj, env, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, timeout_ms, CommaDirection::BEFORE)
    FIELD(obj, user, CommaDirection::BEFORE)
    FIELD(obj, working_directory, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::LocalShellCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, action, CommaDirection::BEFORE)
    FIELD(obj, call_id, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::LocalShellCallOutput)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCall::ShellCall_action)
    FIELD(obj, commands, CommaDirection::NONE)
    FIELD(obj, max_output_length, CommaDirection::BEFORE)
    FIELD(obj, timeout_ms, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCall::LocalEnvironment::LocalSkill)
    FIELD(obj, description, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, path, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCall::LocalEnvironment)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, skills, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCall::ContainerReference)
    FIELD(obj, container_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCall)
    FIELD(obj, action, CommaDirection::NONE)
    FIELD(obj, call_id, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, environment, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCallOutput::ResponseFunctionShellCallOutputContent::Timeout)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCallOutput::ResponseFunctionShellCallOutputContent::Exit)
    FIELD(obj, exit_code, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCallOutput::ResponseFunctionShellCallOutputContent)
    FIELD(obj, outcome, CommaDirection::NONE)
    FIELD_ALT(obj, stderr_, "stderr", CommaDirection::BEFORE)
    FIELD_ALT(obj, stdout_, "stdout", CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ShellCallOutput)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, max_output_length, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchCall::CreateFile)
    FIELD(obj, diff, CommaDirection::NONE)
    FIELD(obj, path, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchCall::DeleteFile)
    FIELD(obj, path, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchCall::UpdateFile)
    FIELD(obj, diff, CommaDirection::NONE)
    FIELD(obj, path, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchCall)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, operation, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchCallOutput)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, status, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, output, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::McpListTools::McpListTools_tools)
    FIELD(obj, input_schema, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, annotations, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::McpListTools)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, server_label, CommaDirection::BEFORE)
    FIELD(obj, tools, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, error, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::McpApprovalRequest)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, arguments, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, server_label, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::McpApprovalResponse)
    FIELD(obj, approval_request_id, CommaDirection::NONE)
    FIELD(obj, approve, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
    FIELD(obj, reason, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::McpCall)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, arguments, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, server_label, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, approval_request_id, CommaDirection::BEFORE)
    FIELD(obj, error, CommaDirection::BEFORE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, status, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCustomToolCallOutput::ResponseInputText)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCustomToolCallOutput::ResponseInputImage)
    FIELD(obj, detail, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCustomToolCallOutput::ResponseInputFile)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_data, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, file_url, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCustomToolCallOutput)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, output, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseCustomToolCall)
    FIELD(obj, call_id, CommaDirection::NONE)
    FIELD(obj, input, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, id, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ItemReference)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponsePrompt::ResponseInputText)
    FIELD(obj, text, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponsePrompt::ResponseInputImage)
    FIELD(obj, detail, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponsePrompt::ResponseInputFile)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_data, CommaDirection::BEFORE)
    FIELD(obj, file_id, CommaDirection::BEFORE)
    FIELD(obj, file_url, CommaDirection::BEFORE)
    FIELD(obj, filename, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponsePrompt)
    FIELD(obj, id, CommaDirection::NONE)
    FIELD(obj, variables, CommaDirection::BEFORE)
    FIELD(obj, version, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Reasoning)
    FIELD(obj, effort, CommaDirection::NONE)
    FIELD(obj, generate_summary, CommaDirection::BEFORE)
    FIELD(obj, summary, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Request_stream_options)
    FIELD(obj, include_obfuscation, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseTextConfig::ResponseFormatText)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseTextConfig::ResponseFormatTextJSONSchemaConfig)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, schema, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseTextConfig::ResponseFormatJSONObject)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ResponseTextConfig)
    FIELD(obj, format, CommaDirection::NONE)
    FIELD(obj, verbosity, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceAllowed)
    FIELD(obj, mode, CommaDirection::NONE)
    FIELD(obj, tools, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceTypes)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceFunction)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceMcp)
    FIELD(obj, server_label, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, name, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceCustom)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceApplyPatch)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ToolChoiceShell)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionTool)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, parameters, CommaDirection::BEFORE)
    FIELD(obj, strict, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool::ComparisonFilter)
    FIELD(obj, key, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, value, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool::CompoundFilter::ComparisonFilter)
    FIELD(obj, key, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, value, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool::CompoundFilter)
    FIELD(obj, filters, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool::FileSearchTool_ranking_options::FileSearchTool_ranking_options_hybrid_search)
    FIELD(obj, embedding_weight, CommaDirection::NONE)
    FIELD(obj, text_weight, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool::FileSearchTool_ranking_options)
    FIELD(obj, hybrid_search, CommaDirection::NONE)
    FIELD(obj, ranker, CommaDirection::BEFORE)
    FIELD(obj, score_threshold, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FileSearchTool)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, vector_store_ids, CommaDirection::BEFORE)
    FIELD(obj, filters, CommaDirection::BEFORE)
    FIELD(obj, max_num_results, CommaDirection::BEFORE)
    FIELD(obj, ranking_options, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ComputerTool)
    FIELD(obj, display_height, CommaDirection::NONE)
    FIELD(obj, display_width, CommaDirection::BEFORE)
    FIELD(obj, environment, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool::WebSearchTool_filters)
    FIELD(obj, allowed_domains, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool::WebSearchTool_user_location)
    FIELD(obj, city, CommaDirection::NONE)
    FIELD(obj, country, CommaDirection::BEFORE)
    FIELD(obj, region, CommaDirection::BEFORE)
    FIELD(obj, timezone, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchTool)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, filters, CommaDirection::BEFORE)
    FIELD(obj, search_context_size, CommaDirection::BEFORE)
    FIELD(obj, user_location, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Mcp::McpToolFilter)
    FIELD(obj, read_only, CommaDirection::NONE)
    FIELD(obj, tool_names, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Mcp::McpToolApprovalFilter::McpToolApprovalFilter_always)
    FIELD(obj, read_only, CommaDirection::NONE)
    FIELD(obj, tool_names, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Mcp::McpToolApprovalFilter::McpToolApprovalFilter_never)
    FIELD(obj, read_only, CommaDirection::NONE)
    FIELD(obj, tool_names, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Mcp::McpToolApprovalFilter)
    FIELD(obj, always, CommaDirection::NONE)
    FIELD(obj, never, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::Mcp)
    FIELD(obj, server_label, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, allowed_tools, CommaDirection::BEFORE)
    FIELD(obj, authorization, CommaDirection::BEFORE)
    FIELD(obj, connector_id, CommaDirection::BEFORE)
    FIELD(obj, headers, CommaDirection::BEFORE)
    FIELD(obj, require_approval, CommaDirection::BEFORE)
    FIELD(obj, server_description, CommaDirection::BEFORE)
    FIELD(obj, server_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyDisabled)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyAllowlist::ContainerNetworkPolicyDomainSecret)
    FIELD(obj, domain, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, value, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeInterpreter::CodeInterpreterToolAuto::ContainerNetworkPolicyAllowlist)
    FIELD(obj, allowed_domains, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, domain_secrets, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeInterpreter::CodeInterpreterToolAuto)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_ids, CommaDirection::BEFORE)
    FIELD(obj, memory_limit, CommaDirection::BEFORE)
    FIELD(obj, network_policy, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CodeInterpreter)
    FIELD(obj, container, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ImageGeneration::ImageGeneration_input_image_mask)
    FIELD(obj, file_id, CommaDirection::NONE)
    FIELD(obj, image_url, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ImageGeneration)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, action, CommaDirection::BEFORE)
    FIELD(obj, background, CommaDirection::BEFORE)
    FIELD(obj, input_fidelity, CommaDirection::BEFORE)
    FIELD(obj, input_image_mask, CommaDirection::BEFORE)
    FIELD(obj, model, CommaDirection::BEFORE)
    FIELD(obj, moderation, CommaDirection::BEFORE)
    FIELD(obj, output_compression, CommaDirection::BEFORE)
    FIELD(obj, output_format, CommaDirection::BEFORE)
    FIELD(obj, partial_images, CommaDirection::BEFORE)
    FIELD(obj, quality, CommaDirection::BEFORE)
    FIELD(obj, size, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::LocalShell)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyDisabled)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyAllowlist::ContainerNetworkPolicyDomainSecret)
    FIELD(obj, domain, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, value, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::ContainerNetworkPolicyAllowlist)
    FIELD(obj, allowed_domains, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, domain_secrets, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::SkillReference)
    FIELD(obj, skill_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, version, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::InlineSkill::InlineSkillSource)
    FIELD(obj, data, CommaDirection::NONE)
    FIELD(obj, media_type, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto::InlineSkill)
    FIELD(obj, description, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, source, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerAuto)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, file_ids, CommaDirection::BEFORE)
    FIELD(obj, memory_limit, CommaDirection::BEFORE)
    FIELD(obj, network_policy, CommaDirection::BEFORE)
    FIELD(obj, skills, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::LocalEnvironment::LocalSkill)
    FIELD(obj, description, CommaDirection::NONE)
    FIELD(obj, name, CommaDirection::BEFORE)
    FIELD(obj, path, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::LocalEnvironment)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, skills, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool::ContainerReference)
    FIELD(obj, container_id, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::FunctionShellTool)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, environment, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CustomTool::Text)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CustomTool::Grammar)
    FIELD(obj, definition, CommaDirection::NONE)
    FIELD(obj, syntax, CommaDirection::BEFORE)
    FIELD(obj, type, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::CustomTool)
    FIELD(obj, name, CommaDirection::NONE)
    FIELD(obj, type, CommaDirection::BEFORE)
    FIELD(obj, description, CommaDirection::BEFORE)
    FIELD(obj, format, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchPreviewTool::WebSearchPreviewTool_user_location)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, city, CommaDirection::BEFORE)
    FIELD(obj, country, CommaDirection::BEFORE)
    FIELD(obj, region, CommaDirection::BEFORE)
    FIELD(obj, timezone, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::WebSearchPreviewTool)
    FIELD(obj, type, CommaDirection::NONE)
    FIELD(obj, search_context_size, CommaDirection::BEFORE)
    FIELD(obj, user_location, CommaDirection::BEFORE)
END_SERIALIZE

BEGIN_SERIALIZE(Request::ApplyPatchTool)
    FIELD(obj, type, CommaDirection::NONE)
END_SERIALIZE

BEGIN_SERIALIZE(Request)
    FIELD(obj, background, CommaDirection::NONE)
    FIELD(obj, context_management, CommaDirection::BEFORE)
    FIELD(obj, conversation, CommaDirection::BEFORE)
    FIELD(obj, include, CommaDirection::BEFORE)
    FIELD(obj, input, CommaDirection::BEFORE)
    FIELD(obj, instructions, CommaDirection::BEFORE)
    FIELD(obj, max_output_tokens, CommaDirection::BEFORE)
    FIELD(obj, max_tool_calls, CommaDirection::BEFORE)
    FIELD(obj, metadata, CommaDirection::BEFORE)
    FIELD(obj, model, CommaDirection::BEFORE)
    FIELD(obj, parallel_tool_calls, CommaDirection::BEFORE)
    FIELD(obj, previous_response_id, CommaDirection::BEFORE)
    FIELD(obj, prompt, CommaDirection::BEFORE)
    FIELD(obj, prompt_cache_key, CommaDirection::BEFORE)
    FIELD(obj, prompt_cache_retention, CommaDirection::BEFORE)
    FIELD(obj, reasoning, CommaDirection::BEFORE)
    FIELD(obj, safety_identifier, CommaDirection::BEFORE)
    FIELD(obj, service_tier, CommaDirection::BEFORE)
    FIELD(obj, store, CommaDirection::BEFORE)
    FIELD(obj, stream, CommaDirection::BEFORE)
    FIELD(obj, stream_options, CommaDirection::BEFORE)
    FIELD(obj, temperature, CommaDirection::BEFORE)
    FIELD(obj, text, CommaDirection::BEFORE)
    FIELD(obj, tool_choice, CommaDirection::BEFORE)
    FIELD(obj, tools, CommaDirection::BEFORE)
    FIELD(obj, top_logprobs, CommaDirection::BEFORE)
    FIELD(obj, top_p, CommaDirection::BEFORE)
    FIELD(obj, truncation, CommaDirection::BEFORE)
    FIELD(obj, user, CommaDirection::BEFORE)
END_SERIALIZE

/***
 * Top-level Serialize
 */
std::vector<std::byte> Serialize(const Request& request) {
    static thread_local string_builder builder{};

    try {
        builder.clear();
        SerializeFrom(builder, request);

        if (!builder.validate_unicode()) {
            throw AnnotatedException{"Serialize Failed", "string_builder generated invalid unicode data."};
        }

        auto result = builder.view();
        if (result.error() != simdjson::SUCCESS) {
            throw AnnotatedException{"Serialize Failed", simdjson::error_message(result.error())};
        }
        std::string_view json_str = result.value();

        return json_str |
               std::views::transform([](auto const& c) { return static_cast<std::byte>(c); }) |
               std::ranges::to<std::vector<std::byte>>();
    } catch (AnnotatedException const&) {
        throw;
    } catch (std::exception const& e) {
        AnnotatedException ex{"Serialize Failed"};
        ex.AddContext(e.what());
        throw ex;
    }
}

} // namespace jai::llm::openai
