"""
Stage 4 (flat): Generate C++ artifacts from flat intermediate JSON.

This codegen consumes the intermediate JSON produced by the discovery parser,
where all schemas are flat siblings (not nested in a tree).  It emits:

  - <endpoint>.hpp            — struct/enum declarations at namespace level
  - <endpoint>_strings.hpp    — to_string_view / from_string_view for enums
  - <endpoint>_serialize.cpp  — request-side (+ shared) serialization
  - <endpoint>_deserialize.cpp — response-side (+ shared) deserialization

Usage:
    from scripts.api_parity.codegen_flat import generate
    generate("gemini")
"""

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

from . import config

# Banner prepended to every generated file.
_GENERATED_BANNER = (
    "// ============================================================================\n"
    "// AUTO-GENERATED — DO NOT EDIT\n"
    "//\n"
    "// Generated by scripts/api_parity.  Changes will be overwritten on the next\n"
    "// audit run.  To modify the output, edit the codegen scripts instead.\n"
    "// ============================================================================\n"
    "\n"
)


# ─── Tables ───────────────────────────────────────────────────────────────────

CPP_KEYWORDS = {
    "default": "default_value",
    "class": "class_value",
    "enum": "enum_value",
    "operator": "operator_",
    "stderr": "stderr_",
    "stdout": "stdout_",
}

# Map from discovery intermediate types to C++ types.
# All integer types widen to int64_t and floats to double because:
#   - JSON numbers are IEEE 754 doubles (no int32/float distinction)
#   - simdjson internally uses int64_t (get_int64) and double (get_double)
#   - Narrowing to int32_t/float would risk silent truncation
_SCALAR_MAP = {
    "string":   "std::string",
    "boolean":  "bool",
    "int32":    "int64_t",
    "int64":    "int64_t",
    "uint32":   "int64_t",
    "float":    "double",
    "double":   "double",
    "any":      "jai::llm::json::Value",
    "object":   "jai::llm::json::Object",
}


# ─── Naming helpers ──────────────────────────────────────────────────────────

def _escape(name: str) -> str:
    return CPP_KEYWORDS.get(name, name)


_CPP_ENUM_KEYWORDS = {"NULL": "NULL_T", "TRUE": "TRUE_T", "FALSE": "FALSE_T"}

def _upper_snake(value: str) -> str:
    """Turn a string value into an UPPER_SNAKE_CASE enum member name."""
    s = value
    s = s.replace("/", "_").replace("-", "_").replace(".", "_").replace(" ", "_")
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", s)
    s = s.upper()
    s = re.sub(r"_+", "_", s).strip("_")
    if s and s[0].isdigit():
        s = "V_" + s
    # C++ keyword collisions
    return _CPP_ENUM_KEYWORDS.get(s, s)


# ─── Dependency analysis ─────────────────────────────────────────────────────

def _extract_refs(type_str: str) -> list[str]:
    """Extract schema references from a type string.

    Examples:
        "Content"              → ["Content"]
        "array<Part>"          → ["Part"]
        "map<string, Schema>"  → ["Schema"]
        "string"               → []
        "enum"                 → []
    """
    if type_str in _SCALAR_MAP or type_str == "enum":
        return []
    m = re.match(r"array<(.+)>", type_str)
    if m:
        inner = m.group(1).strip()
        return [] if inner in _SCALAR_MAP else [inner]
    m = re.match(r"map<string,\s*(.+)>", type_str)
    if m:
        inner = m.group(1).strip()
        return [] if inner in _SCALAR_MAP else [inner]
    # Bare type name → reference to another schema
    if type_str not in _SCALAR_MAP:
        return [type_str]
    return []


def _topo_sort(schemas: dict[str, dict]) -> list[str]:
    """Topological sort of schema names by dependency order.

    Returns names so that each schema appears after all schemas it references.
    Handles cycles by breaking them (shared types like Content ↔ Part).
    """
    # Build adjacency: schema → set of schemas it depends on
    deps: dict[str, set[str]] = {}
    for name, schema in schemas.items():
        refs = set()
        for field in schema.get("fields", []):
            ftype = field.get("type", "")
            for ref in _extract_refs(ftype):
                if ref in schemas and ref != name:
                    refs.add(ref)
        deps[name] = refs

    # Kahn's algorithm
    in_degree: dict[str, int] = {n: 0 for n in schemas}
    for name, d in deps.items():
        for dep in d:
            if dep in in_degree:
                in_degree[dep] = in_degree.get(dep, 0)  # ensure exists

    # Reverse: who depends on me?
    dependents: dict[str, set[str]] = defaultdict(set)
    for name, d in deps.items():
        for dep in d:
            if dep in schemas:
                dependents[dep].add(name)

    # Actually compute in-degrees
    in_degree = {n: 0 for n in schemas}
    for name, d in deps.items():
        for dep in d:
            if dep in schemas:
                in_degree[name] += 1  # name depends on dep

    # Start with nodes that have no dependencies
    queue = sorted([n for n, deg in in_degree.items() if deg == 0])
    result: list[str] = []
    visited: set[str] = set()

    while queue:
        node = queue.pop(0)
        if node in visited:
            continue
        visited.add(node)
        result.append(node)
        for dependent in sorted(dependents.get(node, set())):
            if dependent in visited:
                continue
            in_degree[dependent] -= 1
            if in_degree[dependent] <= 0:
                queue.append(dependent)

    # Any remaining (cycles) — add them in alphabetical order
    for name in sorted(schemas):
        if name not in visited:
            result.append(name)

    return result


# ─── Enum collection ─────────────────────────────────────────────────────────

class _EnumInfo:
    """An enum class to emit."""
    __slots__ = ("name", "pairs", "owner_schema", "field_name")

    def __init__(self, name: str, pairs: list[tuple[str, str]],
                 owner_schema: str, field_name: str):
        self.name = name
        self.pairs = pairs  # [(UPPER_SNAKE, original_string), ...]
        self.owner_schema = owner_schema
        self.field_name = field_name


def _collect_enums(schemas: dict[str, dict]) -> dict[str, _EnumInfo]:
    """Collect all enum fields and deduplicate by (name, values).

    Many schemas share the same enum (e.g. HarmCategory appears in both
    SafetySetting and SafetyRating).  We deduplicate: if two fields yield
    the same enum name AND have identical values, they share one enum.
    If they have different values, they get disambiguated names.
    """
    # group by enum name → list of (values_tuple, owner, field)
    by_name: dict[str, list[tuple[tuple[str, ...], str, str]]] = defaultdict(list)

    for schema_name, schema in schemas.items():
        for field in schema.get("fields", []):
            if field.get("type") != "enum":
                continue
            values = field.get("values", [])
            fname = field["name"]
            enum_name = _derive_enum_name(fname, values)
            by_name[enum_name].append((tuple(values), schema_name, fname))

    result: dict[str, _EnumInfo] = {}
    for enum_name, occurrences in by_name.items():
        # Group by distinct value sets
        distinct: dict[tuple[str, ...], list[tuple[str, str]]] = defaultdict(list)
        for vals, owner, fname in occurrences:
            distinct[vals].append((owner, fname))

        if len(distinct) == 1:
            # All occurrences have the same values → single enum
            vals = next(iter(distinct))
            owners = next(iter(distinct.values()))
            pairs = [(_upper_snake(v), v) for v in vals]
            result[enum_name] = _EnumInfo(enum_name, pairs, owners[0][0], owners[0][1])
        else:
            # Collision: different value sets under the same field name.
            # Disambiguate by prepending the owner schema name.
            for vals, owners in distinct.items():
                owner, fname = owners[0]
                scoped_name = f"{owner}{enum_name}"
                pairs = [(_upper_snake(v), v) for v in vals]
                result[scoped_name] = _EnumInfo(scoped_name, pairs, owner, fname)

    return result


def _derive_enum_name(field_name: str, values: list[str]) -> str:
    """Derive a PascalCase enum name from the field name.

    Handles both snake_case (e.g. finish_reason → FinishReason)
    and camelCase (e.g. finishReason → FinishReason).
    """
    # Split on camelCase boundaries first
    parts = re.sub(r"([a-z])([A-Z])", r"\1_\2", field_name).split("_")
    return "".join(w.capitalize() for w in parts)


# ─── Type resolution ─────────────────────────────────────────────────────────

def _resolve_cpp_type(field: dict, schema_names: set[str],
                      enum_map: dict[str, str],
                      all_enum_names: set[str] | None = None) -> str:
    """Resolve a field to its C++ type string.

    enum_map: field_name → enum_class_name (for enum fields in this schema)
    all_enum_names: set of all globally-known enum names (for $ref resolution)
    """
    ftype = field.get("type", "")
    all_enums = all_enum_names or set()

    if ftype == "enum":
        fname = field["name"]
        if fname in enum_map:
            return enum_map[fname]
        return "std::string /* UNRESOLVED enum */"

    if ftype in _SCALAR_MAP:
        return _SCALAR_MAP[ftype]

    # array<T>
    m = re.match(r"array<(.+)>", ftype)
    if m:
        inner = m.group(1).strip()
        cpp_inner = _resolve_inner_type(inner, schema_names, all_enums)
        return f"std::vector<{cpp_inner}>"

    # map<string, T>
    m = re.match(r"map<string,\s*(.+)>", ftype)
    if m:
        inner = m.group(1).strip()
        cpp_inner = _resolve_inner_type(inner, schema_names, all_enums)
        return f"std::map<std::string, {cpp_inner}>"

    # Named type reference → schema or enum
    if ftype in schema_names:
        return ftype
    if ftype in all_enums:
        return ftype
    # Check if the field name maps to an enum in our local scope
    fname = field.get("name", "")
    if fname in enum_map:
        return enum_map[fname]

    return f"std::string /* UNRESOLVED: {ftype} */"


def _resolve_inner_type(inner: str, schema_names: set[str],
                        all_enum_names: set[str]) -> str:
    """Resolve an inner type (array element, map value) to C++."""
    if inner in _SCALAR_MAP:
        return _SCALAR_MAP[inner]
    if inner in schema_names:
        return inner
    if inner in all_enum_names:
        return inner
    return f"{inner} /* UNRESOLVED */"


# ─── Build field→enum mapping ────────────────────────────────────────────────


def _build_per_schema_enum_map(
    schemas: dict[str, dict],
    enums: dict[str, _EnumInfo],
) -> dict[str, dict[str, str]]:
    """Build per-schema field→enum mapping.

    Returns: {schema_name: {field_name: enum_class_name}}

    This handles disambiguated enum names (e.g. DynamicRetrievalConfigMode)
    by matching on owner_schema + field_name.
    """
    # Build reverse lookup: (owner_schema, field_name) → enum_name
    owner_lookup: dict[tuple[str, str], str] = {}
    # Also build field_name → enum_name for non-collided enums
    field_lookup: dict[str, str] = {}
    for enum_name, info in enums.items():
        owner_lookup[(info.owner_schema, info.field_name)] = enum_name
        # If the enum name matches the field name derivation, it's non-collided
        base_name = _derive_enum_name(info.field_name, [])
        if enum_name == base_name:
            field_lookup[info.field_name] = enum_name

    result: dict[str, dict[str, str]] = {}
    for schema_name, schema in schemas.items():
        local: dict[str, str] = {}
        for field in schema.get("fields", []):
            if field.get("type") != "enum":
                continue
            fname = field["name"]
            values = tuple(field.get("values", []))

            # Try exact owner match first
            if (schema_name, fname) in owner_lookup:
                local[fname] = owner_lookup[(schema_name, fname)]
            else:
                # Try to find an enum with matching values
                found = False
                for ename, einfo in enums.items():
                    if tuple(v for _, v in einfo.pairs) == values:
                        local[fname] = ename
                        found = True
                        break
                if not found:
                    # Fallback to derived name
                    local[fname] = _derive_enum_name(fname, list(values))

        result[schema_name] = local
    return result


# ─── Code generator class ────────────────────────────────────────────────────

class FlatCppCodegen:
    """Generate C++ artifacts from flat intermediate JSON (discovery format)."""

    def __init__(self, spec: dict, provider: str, endpoint: str):
        self.spec = spec
        self.provider = provider
        self.endpoint = endpoint
        self.schemas: dict[str, dict] = spec.get("schemas", {})
        self.req_type = spec.get("request_type", "GenerateContentRequest")
        self.resp_type = spec.get("response_type", "GenerateContentResponse")

        self._schema_names = set(self.schemas.keys())
        self._enums = _collect_enums(self.schemas)
        self._per_schema_enums = _build_per_schema_enum_map(
            self.schemas, self._enums
        )
        self._sorted_names = _topo_sort(self.schemas)

    def run(self) -> Path:
        out = config.SCRATCH_DIR / "generated" / self.provider
        out.mkdir(parents=True, exist_ok=True)

        ep = self.endpoint

        header = self.emit_header()
        (out / f"{ep}.hpp").write_text(header, encoding="utf-8")

        strings = self.emit_strings()
        (out / f"{ep}_strings.hpp").write_text(strings, encoding="utf-8")

        ser = self.emit_serializer()
        (out / f"{ep}_serialize.cpp").write_text(ser, encoding="utf-8")

        deser = self.emit_deserializer()
        (out / f"{ep}_deserialize.cpp").write_text(deser, encoding="utf-8")

        return out

    # =====================================================================
    #  HEADER  (messages.hpp)
    # =====================================================================

    def emit_header(self) -> str:
        parts: list[str] = [
            _GENERATED_BANNER +
            "#pragma once\n\n"
            "#include <cstdint>\n"
            "#include <map>\n"
            "#include <optional>\n"
            "#include <string>\n"
            "#include <variant>\n"
            "#include <vector>\n\n"
            '#include "../../core/types.hpp"\n\n\n'
            f"namespace jai::llm::{self.provider} {{\n"
        ]

        # ── Enums ──
        parts.append("\n\n/***\n * Vocabulary enums\n */\n")
        for enum_name in sorted(self._enums):
            info = self._enums[enum_name]
            members = ", ".join(p[0] for p in info.pairs)
            parts.append(f"enum class {enum_name} {{ {members} }};\n")

        # ── Structs in dependency order ──
        parts.append("\n\n/***\n * Data structures\n */\n")

        # Forward declarations for cycles
        parts.append(self._emit_forward_decls())

        for name in self._sorted_names:
            schema = self.schemas[name]
            parts.append(self._emit_struct(name, schema))
            parts.append("\n\n")

        # ── Type aliases for Request / Response ──
        if self.req_type in self._schema_names:
            parts.append(f"using Request = {self.req_type};\n")
        if self.resp_type in self._schema_names:
            parts.append(f"using Response = {self.resp_type};\n")

        parts.append(f"\n\n}} // namespace jai::llm::{self.provider}\n")
        return "".join(parts)

    def _emit_forward_decls(self) -> str:
        """Emit forward declarations for types involved in cycles."""
        refs_map: dict[str, set[str]] = {}
        for name, schema in self.schemas.items():
            refs = set()
            for field in schema.get("fields", []):
                for ref in _extract_refs(field.get("type", "")):
                    if ref in self._schema_names and ref != name:
                        refs.add(ref)
            refs_map[name] = refs

        # Find mutually referencing pairs
        needs_forward: set[str] = set()
        for a, a_refs in refs_map.items():
            for b in a_refs:
                if b in refs_map and a in refs_map[b]:
                    idx_a = self._sorted_names.index(a) if a in self._sorted_names else 999
                    idx_b = self._sorted_names.index(b) if b in self._sorted_names else 999
                    if idx_a < idx_b:
                        needs_forward.add(b)
                    else:
                        needs_forward.add(a)

        if not needs_forward:
            return ""

        lines = ["// Forward declarations (cyclic references)\n"]
        for name in sorted(needs_forward):
            lines.append(f"struct {name};\n")
        lines.append("\n")
        return "".join(lines)

    def _emit_struct(self, name: str, schema: dict) -> str:
        """Emit a single struct definition."""
        fields = schema.get("fields", [])
        enum_map = self._per_schema_enums.get(name, {})
        desc = schema.get("description", "")

        lines: list[str] = []
        if desc:
            short = desc[:100] + "..." if len(desc) > 100 else desc
            lines.append(f"/** {short} */")
        lines.append(f"struct {name} {{")

        if not fields:
            lines.append("};")
            return "\n".join(lines)

        for field in fields:
            fname = field["name"]
            cpp_name = _escape(fname)
            req = field.get("required", False)

            cpp_type = _resolve_cpp_type(
                field, self._schema_names, enum_map,
                set(self._enums.keys())
            )

            # Self-referential wrapping (Schema.items → Schema)
            needs_box = (cpp_type == name)
            if needs_box:
                cpp_type = f"ValueBox<{cpp_type}>"

            if req:
                decl = f"    Required<{cpp_type}> {cpp_name};"
            else:
                decl = f"    std::optional<{cpp_type}> {cpp_name}{{}};"

            if cpp_name != fname:
                decl += f"  // JSON: \"{fname}\""

            lines.append(decl)

        lines.append("};")
        return "\n".join(lines)

    # =====================================================================
    #  STRINGS  (strings.hpp)
    # =====================================================================

    def emit_strings(self) -> str:
        ns = self.provider
        parts: list[str] = [
            _GENERATED_BANNER +
            "#pragma once\n\n"
            '#include "../../core/strings_base.hpp"\n'
            '#include "../../core/error.hpp"\n'
            f'#include "{self.endpoint}.hpp"\n\n'
            "namespace jai::llm {\n\n"
        ]

        for enum_name in sorted(self._enums):
            info = self._enums[enum_name]
            fq = f"{ns}::{enum_name}"

            # from_string_view
            parts.append(
                f"template <>\n"
                f"constexpr std::optional<{fq}>\n"
                f"from_string_view<{fq}>(std::string_view sv) {{\n"
            )
            for upper, orig in info.pairs:
                parts.append(f'    if (sv == "{orig}") return {fq}::{upper};\n')
            parts.append("    return std::nullopt;\n}\n\n")

            # to_string_view
            parts.append(f"constexpr std::string_view to_string_view({fq} val) {{\n")
            parts.append("    switch (val) {\n")
            for upper, orig in info.pairs:
                parts.append(f'        case {fq}::{upper}: return "{orig}";\n')
            parts.append(
                f'        default: throw AnnotatedException{{"invalid {fq}"}};\n'
                f"    }}\n}}\n\n"
            )

        parts.append("} // namespace jai::llm\n")
        return "".join(parts)

    # =====================================================================
    #  SERIALIZER  (serialize.cpp)
    # =====================================================================

    def emit_serializer(self) -> str:
        ns = self.provider
        iface = f"../../../interface/protocols/{ns}"
        parts: list[str] = [
            _GENERATED_BANNER +
            f'#include "{iface}/{self.endpoint}.hpp"\n'
            f'#include "{iface}/{self.endpoint}_strings.hpp"\n'
            f'#include "base.hpp"\n\n'
            f"using namespace simdjson::builder;\n\n"
            f"namespace jai::llm::{ns} {{\n\n"
        ]

        # Serialize request-side and shared structs
        for name in self._sorted_names:
            schema = self.schemas[name]
            side = schema.get("side", "shared")
            if side not in ("request", "shared"):
                continue
            parts.append(self._serialize_block(name, schema))
            parts.append("\n\n")

        # Top-level Serialize function
        req_name = "Request"
        parts.append(
            f"/***\n"
            f" * Top-level Serialize\n"
            f" */\n"
            f"std::vector<std::byte> Serialize(const {req_name}& request) {{\n"
            f"    static thread_local string_builder builder{{}};\n"
            f"\n"
            f"    try {{\n"
            f"        builder.clear();\n"
            f"        SerializeFrom(builder, request);\n"
            f"\n"
            f"        if (!builder.validate_unicode()) {{\n"
            f'            throw AnnotatedException{{"Serialize Failed", "string_builder generated invalid unicode data."}};\n'
            f"        }}\n"
            f"\n"
            f"        auto result = builder.view();\n"
            f"        if (result.error() != simdjson::SUCCESS) {{\n"
            f'            throw AnnotatedException{{"Serialize Failed", simdjson::error_message(result.error())}};\n'
            f"        }}\n"
            f"        std::string_view json_str = result.value();\n"
            f"\n"
            f"        return json_str |\n"
            f"               std::views::transform([](auto const& c) {{ return static_cast<std::byte>(c); }}) |\n"
            f"               std::ranges::to<std::vector<std::byte>>();\n"
            f"    }} catch (AnnotatedException const&) {{\n"
            f"        throw;\n"
            f"    }} catch (std::exception const& e) {{\n"
            f'        AnnotatedException ex{{"Serialize Failed"}};\n'
            f"        ex.AddContext(e.what());\n"
            f"        throw ex;\n"
            f"    }}\n"
            f"}}\n\n"
        )

        parts.append(f"}} // namespace jai::llm::{ns}\n")
        return "".join(parts)

    def _serialize_block(self, name: str, schema: dict) -> str:
        """Emit a BEGIN_SERIALIZE block for a flat struct."""
        fields = schema.get("fields", [])

        lines = [f"BEGIN_SERIALIZE({name})"]
        for i, field in enumerate(fields):
            fname = field["name"]
            cpp_name = _escape(fname)
            cd = "NONE" if i == 0 else "BEFORE"
            if cpp_name != fname:
                lines.append(
                    f'    FIELD_ALT(obj, {cpp_name}, "{fname}", '
                    f"CommaDirection::{cd})"
                )
            else:
                lines.append(
                    f"    FIELD(obj, {fname}, CommaDirection::{cd})"
                )
        lines.append("END_SERIALIZE")
        return "\n".join(lines)

    # =====================================================================
    #  DESERIALIZER  (deserialize.cpp)
    # =====================================================================

    def emit_deserializer(self) -> str:
        ns = self.provider
        iface = f"../../../interface/protocols/{ns}"
        parts: list[str] = [
            _GENERATED_BANNER +
            f'#include "{iface}/{self.endpoint}.hpp"\n'
            f'#include "{iface}/{self.endpoint}_strings.hpp"\n'
            f'#include "base.hpp"\n'
            f'#include "../../curl.hpp"\n\n'
            f"namespace jai::llm {{\n\n"
        ]

        # Deserialize response-side and shared structs
        for name in self._sorted_names:
            schema = self.schemas[name]
            side = schema.get("side", "shared")
            if side not in ("response", "shared"):
                continue
            parts.append(self._deserialize_block(name, schema))
            parts.append("\n\n")

        # Top-level Deserialize function
        resp_name = "Response"
        parts.append(
            f"/***\n"
            f" * Top-level Deserialize\n"
            f" */\n"
            f"namespace {ns} {{\n"
            f"    {resp_name} Deserialize(const curl::Response& response) {{\n"
            f"        if (response.body.size() < response.body_len + simdjson::SIMDJSON_PADDING) {{\n"
            f'            throw AnnotatedException{{"Simdjson padding check failed"}};\n'
            f"        }}\n"
            f"\n"
            f"        static thread_local simdjson::dom::parser parser{{}};\n"
            f"\n"
            f"        try {{\n"
            f"            simdjson::dom::element doc = parser.parse(\n"
            f"                reinterpret_cast<const char*>(response.body.data()), response.body_len);\n"
            f"            return DeserializeTo<{resp_name}>(doc);\n"
            f"        }} catch (const simdjson::simdjson_error& e) {{\n"
            f'            throw AnnotatedException{{"{ns}::Deserialize Failed", e.what()}};\n'
            f"        }}\n"
            f"    }}\n"
            f"}}\n\n"
        )

        parts.append("} // namespace jai::llm\n")
        return "".join(parts)

    def _deserialize_block(self, name: str, schema: dict) -> str:
        """Emit a BEGIN_DESERIALIZE block for a flat struct."""
        ns = self.provider
        fields = schema.get("fields", [])

        fq = f"{ns}::{name}"
        lines = [f"BEGIN_DESERIALIZE({fq})"]
        for i, field in enumerate(fields):
            fname = field["name"]
            cpp_name = _escape(fname)
            comma = "," if i < len(fields) - 1 else ""
            if cpp_name != fname:
                lines.append(
                    f'    FIELD_ALT(src, {cpp_name}, "{fname}"){comma}'
                )
            else:
                lines.append(f"    FIELD(src, {fname}){comma}")
        lines.append("END_DESERIALIZE")
        return "\n".join(lines)


# ─── Public entry point ──────────────────────────────────────────────────────

def generate(provider: str) -> Path:
    """Generate C++ from flat intermediate JSON for *provider*.

    Returns the output directory path.
    """
    json_path = config.extracted_json_path(provider)
    if not json_path.exists():
        raise FileNotFoundError(
            f"Extracted JSON not found: {json_path}\n"
            f"Run 'extract --provider {provider}' first."
        )

    print(f"Loading {json_path}")
    spec = json.loads(json_path.read_text(encoding="utf-8"))

    endpoint = config.ENDPOINTS[provider].endpoint
    gen = FlatCppCodegen(spec, provider, endpoint)
    out = gen.run()

    # Summary
    print(f"Generated C++ in {out}/")
    print(f"  Enums:   {len(gen._enums)}")
    print(f"  Schemas: {len(gen._sorted_names)}")

    return out
