"""
Stage 4: Generate — Emit C++ artifacts from intermediate JSON.

Usage:
    from scripts.api_parity.codegen import generate
    generate("anthropic")
"""

import json
import re
from pathlib import Path
from typing import Any

from . import config

# Banner prepended to every generated file.
_GENERATED_BANNER = (
    "// ============================================================================\n"
    "// AUTO-GENERATED — DO NOT EDIT\n"
    "//\n"
    "// Generated by scripts/api_parity.  Changes will be overwritten on the next\n"
    "// audit run.  To modify the output, edit the codegen scripts instead.\n"
    "// ============================================================================\n"
    "\n"
)


# ─── Tables ───────────────────────────────────────────────────────────────────

# C++ reserved words / macro conflicts → safe member names
CPP_KEYWORDS = {
    "default": "default_value",
    "class": "class_value",
    "enum": "enum_value",
    "operator": "operator_",
    "stderr": "stderr_",
    "stdout": "stdout_",
}


# ─── Naming helpers ──────────────────────────────────────────────────────────

def _escape(name: str) -> str:
    """Return the safe C++ identifier for a field name."""
    return CPP_KEYWORDS.get(name, name)


def _pascal(name: str) -> str:
    """snake_case → PascalCase."""
    return "".join(w.capitalize() for w in name.split("_"))


def _upper_snake(value: str) -> str:
    """Turn a spec string value into an UPPER_SNAKE_CASE enum member name.

    Examples:
        "end_turn"              → "END_TURN"
        "image/gif"             → "IMAGE_GIF"
        "5m"                    → "V_5M"
        "str_replace_editor"    → "STR_REPLACE_EDITOR"
    """
    s = value
    s = s.replace("/", "_").replace("-", "_").replace(".", "_").replace(" ", "_")
    # camelCase boundaries
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", s)
    s = s.upper()
    # collapse multi-underscores, strip edges
    s = re.sub(r"_+", "_", s).strip("_")
    # C++ identifiers cannot start with a digit
    if s and s[0].isdigit():
        s = "V_" + s
    return s


def _indent(text: str, level: int) -> str:
    """Indent every non-empty line by *level* × 4 spaces."""
    pad = "    " * level
    return "\n".join(pad + ln if ln.strip() else "" for ln in text.split("\n"))


# Map of union member type → (simdjson predicate, C++ type)
_TYPE_CHECK_MAP = {
    "string":   ("is_string()", "std::string"),
    "boolean":  ("is_bool()",   "bool"),
    "number":   ("is_number()", "double"),
    "integer":  ("is_int64()",  "int64_t"),
}

# Map raw primitive type names to C++ types (used for array element types
# in union members before namespace-qualifying).
_PRIMITIVE_TYPE_MAP: dict[str, str] = {
    "string":  "std::string",
    "boolean": "bool",
    "number":  "double",
    "integer": "int64_t",
}


def _resolve_array_element_cpp(m: dict) -> str:
    """Resolve the C++ type for an array union member's element.

    If the member has ``element_members`` (a list of union member
    descriptors), produce ``std::variant<T1, T2, ...>``.  Otherwise
    fall back to ``element_type`` mapped through ``_PRIMITIVE_TYPE_MAP``.
    """
    elem_members = m.get("element_members")
    if elem_members:
        parts: list[str] = []
        for em in elem_members:
            emt = em.get("type", "")
            cpp = _PRIMITIVE_TYPE_MAP.get(emt)
            if cpp:
                parts.append(cpp)
            elif emt == "struct":
                parts.append(em.get("ref", "UNKNOWN"))
            elif emt in ("object", "unknown"):
                parts.append("jai::llm::json::Object")
            else:
                parts.append(emt)
        return f"std::variant<{', '.join(parts)}>"
    elem = m.get("element", m.get("element_type", "UNKNOWN"))
    return _PRIMITIVE_TYPE_MAP.get(elem, elem)


_BUILTIN_CPP = {"std::string", "bool", "double", "int64_t"}


def _qualify_cpp_type(m: str, parent_path: str) -> str:
    """Fully qualify a C++ type name relative to *parent_path* for dedup.

    Handles ``std::vector<X>`` and ``std::variant<X, Y>`` by recursively
    qualifying the inner types.  Builtin types and already-qualified
    names (``std::`` / ``jai::`` prefixed) are returned as-is.
    """
    if m in _BUILTIN_CPP:
        return m
    if m.startswith("std::vector<"):
        inner = m[len("std::vector<"):-1]
        q = _qualify_cpp_type(inner, parent_path)
        return f"std::vector<{q}>"
    if m.startswith("std::variant<"):
        inner = m[len("std::variant<"):-1]
        parts = [p.strip() for p in inner.split(", ")]
        qparts = [_qualify_cpp_type(p, parent_path) for p in parts]
        return f"std::variant<{', '.join(qparts)}>"
    if m.startswith("std::") or m.startswith("jai::"):
        return m
    return f"{parent_path}::{m}"


def _build_dispatch_entries(
    raw_entries: list[tuple[str, str]],
) -> list[tuple[str, str, str]]:
    """Build (enum_member, disc_value, struct_ref) triples from (disc_value, struct_ref) pairs.

    When multiple struct refs share the same discriminator value (e.g. versioned
    tools like CodeExecutionTool20250522 / CodeExecutionTool20250825 both using
    ``"code_execution"``), the enum member name is derived from the struct ref
    name instead, to avoid C++ compilation errors from duplicate enum members.
    """
    # Count occurrences of each discriminator value
    dv_count: dict[str, int] = {}
    for dv, _ in raw_entries:
        dv_count[dv] = dv_count.get(dv, 0) + 1

    result: list[tuple[str, str, str]] = []
    for dv, ref in raw_entries:
        if dv_count[dv] > 1:
            # Collision — use the struct ref name for the enum member
            enum_member = _upper_snake(ref)
        else:
            enum_member = _upper_snake(dv)
        result.append((enum_member, dv, ref))
    return result


# ─── Data carriers ────────────────────────────────────────────────────────────

class _KindInfo:
    """A Kind struct that was emitted (for strings.hpp)."""
    __slots__ = ("qualified", "value")

    def __init__(self, qualified: str, value: str):
        self.qualified = qualified   # e.g. "Request::MessageParam::TextBlockParam::TypeKind"
        self.value = value           # e.g. "text"


class _EnumInfo:
    """An enum class that was emitted (for strings.hpp)."""
    __slots__ = ("qualified", "pairs")

    def __init__(self, qualified: str, pairs: list[tuple[str, str]]):
        self.qualified = qualified   # e.g. "Request::MessageParam::Role"
        self.pairs = pairs           # [(UPPER_SNAKE, original_string), ...]


class _DispatchInfo:
    """A dispatch enum for variant deserialization (synthesized)."""
    __slots__ = ("qualified", "entries", "discriminator_field", "type_checks",
                 "variant_type")

    def __init__(self, qualified: str, entries: list[tuple[str, str, str]],
                 discriminator_field: str = "type",
                 type_checks: list[tuple[str, str]] | None = None,
                 variant_type: str = ""):
        self.qualified = qualified           # e.g. "Request::MessageParam::ContentKind"
        self.entries = entries                # [(enum_member, kind_value, member_struct_name), ...]
        self.discriminator_field = discriminator_field  # JSON field name used to dispatch
        # Non-struct variant arms that need JSON-value-type checks before
        # discriminator dispatch.  Each entry is (json_check, cpp_type) where
        # json_check is the simdjson predicate, e.g. "is_array()", "is_string()".
        self.type_checks = type_checks or []
        # The concrete std::variant<...> type string for dedup detection.
        self.variant_type = variant_type


class _FieldInfo:
    """Resolved information about a single struct field."""
    __slots__ = (
        "json_name", "cpp_name", "cpp_type", "required",
        "is_kind", "is_enum", "is_union",
    )

    def __init__(self, json_name: str, cpp_name: str, cpp_type: str,
                 required: bool, *, is_kind=False, is_enum=False, is_union=False):
        self.json_name = json_name
        self.cpp_name = cpp_name
        self.cpp_type = cpp_type
        self.required = required
        self.is_kind = is_kind
        self.is_enum = is_enum
        self.is_union = is_union


class _StructRecord:
    """A struct emitted during the header walk (for serialize/deserialize)."""
    __slots__ = ("qualified", "fields")

    def __init__(self, qualified: str, fields: list[_FieldInfo]):
        self.qualified = qualified
        self.fields = fields


# ─── Code generator ──────────────────────────────────────────────────────────

class CppCodegen:
    """Walk the intermediate-JSON tree and emit C++ artifacts."""

    def __init__(self, spec: dict, provider: str, endpoint: str):
        self.spec = spec
        self.provider = provider
        self.endpoint = endpoint
        self.request_root = spec.get("request", {}).get("root")
        self.response_root = spec.get("response", {}).get("root")

        # If the response root is a fieldless wrapper with a single child,
        # unwrap it — the spec defines the return type directly (e.g.
        # "Message"), not a synthetic "Response" container.
        if self.response_root:
            rr = self.response_root
            if (not rr.get("fields") and not rr.get("kind")
                    and len(rr.get("children", [])) == 1):
                self.response_root = rr["children"][0]

        # Populated during emit_header()
        self._kinds: list[_KindInfo] = []
        self._enums: list[_EnumInfo] = []
        self._dispatches: list[_DispatchInfo] = []
        self._req_structs: list[_StructRecord] = []
        self._resp_structs: list[_StructRecord] = []
        # Map value variant aliases:
        #   (qualified_alias, member_info, concrete_variant_type)
        # concrete_variant_type is the std::variant<...> string for dedup.
        self._map_value_variants: list[tuple[str, list[tuple[str, str, str]], str]] = []

    # ── public API ────────────────────────────────────────────────────────

    def run(self) -> Path:
        out = config.SCRATCH_DIR / "generated" / self.provider
        out.mkdir(parents=True, exist_ok=True)

        ep = self.endpoint

        header = self.emit_header()
        (out / f"{ep}.hpp").write_text(header, encoding="utf-8")

        strings = self.emit_strings()
        (out / f"{ep}_strings.hpp").write_text(strings, encoding="utf-8")

        ser = self.emit_serializer()
        (out / f"{ep}_serialize.cpp").write_text(ser, encoding="utf-8")

        deser = self.emit_deserializer()
        (out / f"{ep}_deserialize.cpp").write_text(deser, encoding="utf-8")

        return out

    # =====================================================================
    #  HEADER  (messages.hpp)
    # =====================================================================

    def emit_header(self) -> str:
        parts: list[str] = []
        parts.append(
            _GENERATED_BANNER +
            "#pragma once\n\n"
            "#include <cstdint>\n"
            "#include <map>\n"
            "#include <optional>\n"
            "#include <string>\n"
            "#include <variant>\n"
            "#include <vector>\n\n"
            '#include "../../core/types.hpp"\n\n'
            f"namespace jai::llm::{self.provider} {{\n"
        )

        if self.request_root:
            parts.append("\n// ── Request ────────────────────────────────────────────\n")
            parts.append(self._emit_struct(self.request_root, "", is_resp=False))

        if self.response_root:
            parts.append("\n\n// ── Response ───────────────────────────────────────────\n")
            parts.append(self._emit_struct(self.response_root, "", is_resp=True))

        parts.append(f"\n\n}} // namespace jai::llm::{self.provider}\n")
        return "".join(parts)

    # ── recursive struct emitter ──────────────────────────────────────────

    def _emit_struct(self, node: dict, parent_path: str, *, is_resp: bool) -> str:
        name = node["name"]
        qpath = f"{parent_path}::{name}" if parent_path else name
        kind_val = node.get("kind")
        fields_json = node.get("fields", [])
        children = node.get("children", [])
        child_names = {c["name"] for c in children}

        lines: list[str] = [f"struct {name} {{"]

        # ① nested children (depth-first)
        for child in children:
            child_code = self._emit_struct(child, qpath, is_resp=is_resp)
            lines.append(_indent(child_code, 1))
            lines.append("")

        # ② Kind structs — one per kind-typed field
        #    The struct-level `kind` value matches the `type` field.
        #    Other kind fields (e.g. `role`) get their own Kind structs.
        kind_fields_emitted = False
        for fld in fields_json:
            if fld.get("type") != "kind":
                continue
            kv = fld.get("value", "")
            fn = fld["name"]
            if fn == "type":
                kn = "TypeKind"
            else:
                kn = f"{_pascal(fn)}Kind"
            lines.append(
                f'    struct {kn} : Kind '
                f'{{ static constexpr std::string_view value = "{kv}"; }};'
            )
            self._kinds.append(_KindInfo(f"{qpath}::{kn}", kv))
            kind_fields_emitted = True
        if kind_fields_emitted:
            lines.append("")

        # ③ enum class for each enum-typed field
        for fld in fields_json:
            if fld.get("type") != "enum":
                continue
            ename = _pascal(fld["name"])
            vals = fld.get("values", [])
            pairs = [(_upper_snake(v), v) for v in vals]
            members_str = ", ".join(p[0] for p in pairs)
            lines.append(f"    enum class {ename} {{ {members_str} }};")
            self._enums.append(_EnumInfo(f"{qpath}::{ename}", pairs))
        # ③b enum class for array element enums
        # When a field is ``array<string>`` with ``element_enum_values``,
        # emit a named enum class for the element type.
        for fld in fields_json:
            eevals = fld.get("element_enum_values")
            if not eevals:
                continue
            ename = _pascal(fld["name"]) + "Item"
            pairs = [(_upper_snake(v), v) for v in eevals]
            members_str = ", ".join(p[0] for p in pairs)
            lines.append(f"    enum class {ename} {{ {members_str} }};")
            self._enums.append(_EnumInfo(f"{qpath}::{ename}", pairs))

        # blank line after enums if any were emitted
        has_enums = any(
            f.get("type") == "enum" or f.get("element_enum_values")
            for f in fields_json
        )
        if has_enums:
            lines.append("")

        # ④ dispatch enums + using declarations for unions
        usings, map_value_aliases = self._build_usings(
            fields_json, children, child_names, qpath,
        )
        for u in usings:
            lines.append(f"    {u}")
        if usings:
            lines.append("")

        # ⑤ field declarations
        field_infos = self._resolve_fields(
            fields_json, child_names, qpath,
            map_value_aliases=map_value_aliases,
        )
        for fi in field_infos:
            lines.append(f"    {self._field_decl(fi)}")

        lines.append("};")

        # record for serialize / deserialize
        rec = _StructRecord(qpath, field_infos)
        (self._resp_structs if is_resp else self._req_structs).append(rec)

        return "\n".join(lines)

    # ── using declarations & dispatch enums ───────────────────────────────

    def _build_usings(
        self,
        fields_json: list[dict],
        children: list[dict],
        child_names: set[str],
        parent_path: str,
    ) -> tuple[list[str], dict[str, str]]:
        """Return (lines, map_value_aliases) for dispatch-enum + using declarations.

        *map_value_aliases* maps field names to the alias emitted for their
        ``map<string, variant<…>>`` value type so that ``_resolve_type`` can
        reference the alias instead of inlining the variant.

        Sources of union information (no heuristics):
          1. Explicit ``"type": "union"`` fields (from ``or`` in the spec).
          2. ``union_def`` on a field (from the parser detecting named-type
             children under a named-type-reference field).
          3. Array element_type references that resolve to children variants.
          4. ``map<string, T | U | …>`` fields where the value is a union.
        """
        out: list[str] = []
        map_value_aliases: dict[str, str] = {}
        # Track which union_def names we've already emitted, since the same
        # type name (e.g. TextCitationParam) may appear on multiple fields
        # inside the same parent struct but should only produce one using.
        emitted_union_names: set[str] = set()

        # ── Pre-pass: emit children variant usings for array element_types ──
        # When a union member has an array with element_type that isn't a
        # direct child name, it may reference a variant of children.
        # The parser may supply ``element_variant_refs`` listing the specific
        # children, or we fall back to all kind-bearing children.
        kind_children = [c for c in children if c.get("kind") is not None]
        if kind_children:
            # Collect (element_type_name, explicit_refs_or_None) pairs.
            needed_elem_types: list[tuple[str, list[str] | None]] = []
            seen_et: set[str] = set()
            for fld in fields_json:
                if fld.get("type") == "union":
                    for m in fld.get("members", []):
                        if m.get("type") == "array":
                            et = m.get("element_type")
                            if et and et not in child_names and et not in seen_et:
                                seen_et.add(et)
                                needed_elem_types.append(
                                    (et, m.get("element_variant_refs")))
            for et_name, explicit_refs in needed_elem_types:
                if et_name in emitted_union_names:
                    continue
                emitted_union_names.add(et_name)
                # Use explicit refs from the parser if available,
                # otherwise fall back to all kind-bearing children.
                if explicit_refs:
                    refs = explicit_refs
                    ref_children = [c for c in children
                                    if c["name"] in set(explicit_refs)]
                else:
                    refs = [c["name"] for c in kind_children]
                    ref_children = kind_children
                raw_entries: list[tuple[str, str]] = []
                for c in ref_children:
                    for f in c.get("fields", []):
                        if f.get("type") == "kind":
                            raw_entries.append((f["value"], c["name"]))
                            break
                if raw_entries:
                    entries = _build_dispatch_entries(raw_entries)
                    de_name = f"{et_name}Kind"
                    de_members = ", ".join(em for em, _, _ in entries)
                    out.append(f"enum class {de_name} {{ {de_members} }};")
                    self._dispatches.append(
                        _DispatchInfo(f"{parent_path}::{de_name}", entries,
                                      "type")
                    )
                variant_args = ", ".join(refs)
                out.append(f"using {et_name} = std::variant<{variant_args}>;")

        for fld in fields_json:
            ftype = fld.get("type", "")

            # ── explicit union field (from "type or type" in spec) ──
            if ftype == "union":
                self._emit_union_using(fld["name"], fld.get("members", []),
                                       fld.get("discriminator"),
                                       parent_path, out,
                                       enum_values=fld.get("enum_values"))

            # ── union_def from parser (named-type children) ──
            udef = fld.get("union_def")
            if udef:
                uname = udef["name"]
                if uname in emitted_union_names:
                    continue
                emitted_union_names.add(uname)
                members = udef.get("members", [])
                # Every member type is a variant arm except "literal",
                # which gets condensed into an enum class.
                non_literal = [m for m in members
                               if m.get("type") != "literal"]
                literals = [m for m in members
                            if m.get("type") == "literal"]
                # Condense literals into a single synthetic "enum" member
                # so they contribute as one variant arm.
                effective = list(non_literal)
                if literals:
                    effective.append({
                        "type": "enum",
                        "values": [m.get("value", "") for m in literals],
                    })
                if len(effective) >= 2:
                    self._emit_union_using_from_def(
                        uname, effective, udef.get("discriminator"),
                        parent_path, out,
                    )
                elif len(effective) == 1 and effective[0].get("type") == "enum":
                    # All members are literals → emit a pure enum class
                    vals = effective[0]["values"]
                    pairs = [(_upper_snake(v), v) for v in vals]
                    members_str = ", ".join(p[0] for p in pairs)
                    out.append(f"enum class {uname} {{ {members_str} }};")
                    self._enums.append(
                        _EnumInfo(f"{parent_path}::{uname}", pairs))

        # ── map<string, union> fields → named using aliases ──
        # Build a lookup from child name → kind value for discriminated dispatch.
        _child_kind: dict[str, str] = {}
        for c in children:
            k = c.get("kind")
            if k:
                _child_kind[c["name"]] = k
        _JSON_TYPE_CHECKS: dict[str, str] = {
            "std::string": "is_string()",
            "double": "is_double() || src.is_int64() || src.is_uint64()",
            "bool": "is_bool()",
            "int64_t": "is_int64()",
            "jai::llm::json::Object": "is_object()",
        }
        for fld in fields_json:
            mvms = fld.get("map_value_members")
            if not mvms:
                continue
            cpp_parts: list[str] = []
            # Each entry is either:
            #   ("scalar", json_check, cpp_type) for scalars, or
            #   ("struct", kind_value, child_name) for kind-bearing structs
            member_info: list[tuple[str, str, str]] = []
            for mvm in mvms:
                mt = mvm.get("type", "")
                resolved = self._resolve_scalar(mt)
                if resolved:
                    cpp_parts.append(resolved)
                    check = _JSON_TYPE_CHECKS.get(resolved)
                    if check:
                        member_info.append(("scalar", check, resolved))
                elif mt == "struct":
                    ref = mvm.get("ref", "UNKNOWN")
                    cpp_parts.append(ref)
                    kv = _child_kind.get(ref, "")
                    member_info.append(("struct", kv, ref))
                elif mt in ("object", "unknown"):
                    cpp_parts.append("jai::llm::json::Object")
                    check = _JSON_TYPE_CHECKS.get("jai::llm::json::Object")
                    if check:
                        member_info.append(("scalar", check, "jai::llm::json::Object"))
                else:
                    cpp_parts.append(f"std::string /* UNRESOLVED: {mt} */")
            alias = _pascal(fld["name"]) + "Value"
            out.append(
                f"using {alias} = std::variant<{', '.join(cpp_parts)}>;"
            )
            map_value_aliases[fld["name"]] = alias
            # Record for deserializer generation.  Include the concrete
            # variant type string for dedup (C++ template specializations
            # see through using aliases).
            concrete = f"std::variant<{', '.join(cpp_parts)}>"
            self._map_value_variants.append(
                (f"{parent_path}::{alias}", member_info, concrete)
            )

        return out, map_value_aliases

    def _register_element_variant_dispatch(
        self, element_members: list[dict], alias_name: str,
        concrete_cpp: str, parent_path: str,
    ) -> None:
        """Register a dispatch for an array element variant type.

        *alias_name* is the using-alias name (e.g. ``"ValueElement"``).
        *concrete_cpp* is the raw ``std::variant<…>`` type string used
        for dedup (since C++ template specializations see through aliases).
        """
        elem_type_checks: list[tuple[str, str]] = []
        for em in element_members:
            emt = em.get("type", "")
            if emt in _TYPE_CHECK_MAP:
                elem_type_checks.append(_TYPE_CHECK_MAP[emt])
            elif emt == "struct":
                elem_type_checks.append(
                    ("is_object()", f"{parent_path}::{em.get('ref', 'UNKNOWN')}"))
            elif emt in ("object", "unknown"):
                elem_type_checks.append(
                    ("is_object()", "jai::llm::json::Object"))
        if elem_type_checks:
            fq_key = _qualify_cpp_type(concrete_cpp, parent_path)
            self._dispatches.append(
                _DispatchInfo(
                    f"{parent_path}::{alias_name}", [],
                    "type",
                    elem_type_checks,
                    variant_type=fq_key,
                )
            )

    def _emit_union_using(
        self, field_name: str, members_json: list[dict],
        discriminator: str | None,
        parent_path: str, out: list[str],
        *,
        enum_values: list[str] | None = None,
    ) -> None:
        """Emit dispatch-enum + using for an explicit union field."""
        alias = _pascal(field_name)
        cpp_members = self._resolve_union_members(members_json)

        # Pre-pass: emit named using aliases for array element variants
        # and replace the corresponding cpp_members entry (which
        # _resolve_union_members populated as std::vector<std::variant<…>>)
        # with std::vector<AliasElement>.
        _elem_alias_map: dict[int, str] = {}
        # Maps aliased cpp_members entries → concrete types for dedup.
        # C++ template specializations see through using aliases, so the
        # dedup key must use the expanded concrete type.
        _alias_to_concrete: dict[str, str] = {}
        for i, m_json in enumerate(members_json):
            if m_json.get("type") == "array" and m_json.get("element_members"):
                elem_alias = f"{alias}Element"
                elem_cpp = _resolve_array_element_cpp(m_json)
                out.append(f"using {elem_alias} = {elem_cpp};")
                self._register_element_variant_dispatch(
                    m_json["element_members"], elem_alias, elem_cpp,
                    parent_path)
                aliased = f"std::vector<{elem_alias}>"
                _alias_to_concrete[aliased] = f"std::vector<{elem_cpp}>"
                cpp_members[i] = aliased
                _elem_alias_map[i] = elem_alias

        # Handle enum members: merge all enum values into one enum class
        # and replace the first __ENUM__ placeholder; remove subsequent ones.
        all_enum_vals: list[str] = []
        for m_json in members_json:
            if m_json.get("type") == "enum":
                all_enum_vals.extend(m_json.get("values", []))
        enum_emitted = False
        enum_name = f"{alias}Values"
        for i, m_json in enumerate(members_json):
            if m_json.get("type") == "enum" and i < len(cpp_members) \
                    and cpp_members[i] == "__ENUM__":
                if not enum_emitted:
                    pairs = [(_upper_snake(v), v) for v in all_enum_vals]
                    members_str = ", ".join(p[0] for p in pairs)
                    out.append(f"enum class {enum_name} {{ {members_str} }};")
                    self._enums.append(
                        _EnumInfo(f"{parent_path}::{enum_name}", pairs))
                    cpp_members[i] = enum_name
                    enum_emitted = True
                else:
                    cpp_members[i] = "__REMOVE__"
        cpp_members = [m for m in cpp_members if m != "__REMOVE__"]

        # If all members are unresolvable but we have enum_values from the
        # parser, this union is really a string enum (e.g. allowed_callers).
        # Emit an enum class instead of a broken variant.
        has_unresolved = any("/*" in m for m in cpp_members)
        all_unresolved = all("/*" in m for m in cpp_members)
        if all_unresolved and enum_values:
            entries = _build_dispatch_entries(
                [(v, v) for v in enum_values]
            )
            de_members = ", ".join(em for em, _, _ in entries)
            out.append(f"enum class {alias} {{ {de_members} }};")
            self._dispatches.append(
                _DispatchInfo(f"{parent_path}::{alias}", entries,
                              discriminator or "type")
            )
            return

        # Filter out unresolved comment placeholders from variant members.
        if has_unresolved:
            cpp_members = [m for m in cpp_members if "/*" not in m]
            if not cpp_members:
                # Nothing resolvable and no enum_values — skip entirely.
                out.append(f"// {alias}: all union members unresolvable, skipped")
                return

        raw_entries: list[tuple[str, str]] = []
        type_checks: list[tuple[str, str]] = []
        for m in members_json:
            mt = m.get("type", "")
            if mt == "struct" and m.get("discriminator_value"):
                raw_entries.append(
                    (m["discriminator_value"], m["ref"])
                )
            elif mt == "struct" and not m.get("discriminator_value"):
                # Struct without discriminator — use is_object() type check.
                # Qualify ref with parent_path so _variant_block can emit
                # the correct fully-qualified type.
                type_checks.append(("is_object()", f"{parent_path}::{m['ref']}"))
            elif mt == "array":
                elem_members = m.get("element_members")
                if elem_members:
                    # Named alias was emitted in the pre-pass above;
                    # cpp_members entry was already replaced there.
                    qualified_elem = f"{alias}Element"
                else:
                    elem = _resolve_array_element_cpp(m)
                    qualified_elem = f"{parent_path}::{elem}" if elem not in (
                        "std::string", "bool", "double", "int64_t", "UNKNOWN",
                    ) and not elem.startswith("std::") else elem
                type_checks.append(("is_array()", f"std::vector<{qualified_elem}>"))
            elif mt in ("object", "unknown"):
                type_checks.append(("is_object()", "jai::llm::json::Object"))
            elif mt == "enum":
                # Only add enum type_check once (multiple enum members
                # are merged into a single enum class above).
                enum_tc = ("is_string()", enum_name)
                if enum_tc not in type_checks:
                    type_checks.append(enum_tc)
            elif mt in _TYPE_CHECK_MAP:
                type_checks.append(_TYPE_CHECK_MAP[mt])

        # Deduplicate variant members (preserving order) — duplicate C++
        # types in std::variant cause constructor ambiguity.
        seen_m: set[str] = set()
        deduped: list[str] = []
        for m in cpp_members:
            if m not in seen_m:
                seen_m.add(m)
                deduped.append(m)
        variant_args = ", ".join(deduped)
        concrete_variant = f"std::variant<{variant_args}>"
        # Build a fully-qualified variant type key for dedup.  Expand
        # any alias names back to concrete types so that different
        # aliases of the same underlying type correctly dedup.
        concrete_deduped = [_alias_to_concrete.get(m, m) for m in deduped]
        fq_members = [_qualify_cpp_type(m, parent_path) for m in concrete_deduped]
        fq_variant_key = f"std::variant<{', '.join(fq_members)}>"

        if raw_entries:
            entries = _build_dispatch_entries(raw_entries)
            de_name = f"{alias}Kind"
            de_members = ", ".join(em for em, _, _ in entries)
            out.append(f"enum class {de_name} {{ {de_members} }};")
            self._dispatches.append(
                _DispatchInfo(f"{parent_path}::{de_name}", entries,
                              discriminator or "type",
                              type_checks,
                              variant_type=fq_variant_key)
            )
        elif type_checks:
            # No struct members with discriminators, but we have type-based
            # dispatch (e.g. variant<string, vector<...>>).  Create a
            # _DispatchInfo with empty entries so a DESERIALIZE_VARIANT
            # block is emitted using only JSON value-type checks.
            self._dispatches.append(
                _DispatchInfo(f"{parent_path}::{alias}", [],
                              discriminator or "type",
                              type_checks,
                              variant_type=fq_variant_key)
            )

        out.append(f"using {alias} = {concrete_variant};")

    def _emit_union_using_from_def(
        self, union_name: str, members: list[dict],
        discriminator: str | None, parent_path: str, out: list[str],
    ) -> str:
        """Emit dispatch-enum + using from a parser-generated union_def."""
        # Merge all enum member values into a single enum class.
        all_enum_values: list[str] = []
        for m in members:
            if m.get("type") == "enum":
                all_enum_values.extend(m.get("values", []))
        enum_emitted = False
        enum_name = f"{union_name}Values"

        # Build C++ type list for the variant
        cpp_members: list[str] = []
        _alias_to_concrete: dict[str, str] = {}
        type_checks: list[tuple[str, str]] = []
        for m in members:
            mt = m.get("type", "")
            if mt == "struct":
                cpp_members.append(m["ref"])
            elif mt == "array":
                elem_members = m.get("element_members")
                if elem_members:
                    elem_alias = f"{union_name}Element"
                    elem_cpp = _resolve_array_element_cpp(m)
                    out.append(f"using {elem_alias} = {elem_cpp};")
                    self._register_element_variant_dispatch(
                        elem_members, elem_alias, elem_cpp, parent_path)
                    vec_type = f"std::vector<{elem_alias}>"
                    _alias_to_concrete[vec_type] = f"std::vector<{elem_cpp}>"
                else:
                    elem = _resolve_array_element_cpp(m)
                    qualified_elem = f"{parent_path}::{elem}" if elem not in (
                        "std::string", "bool", "double", "int64_t", "UNKNOWN",
                    ) and not elem.startswith("std::") else elem
                    vec_type = f"std::vector<{qualified_elem}>"
                cpp_members.append(vec_type)
                type_checks.append(("is_array()", vec_type))
            elif mt in ("object", "unknown"):
                cpp_members.append("jai::llm::json::Object")
                type_checks.append(("is_object()", "jai::llm::json::Object"))
            elif mt == "enum":
                # Emit the merged enum class once for all enum members.
                if not enum_emitted:
                    pairs = [(_upper_snake(v), v) for v in all_enum_values]
                    members_str = ", ".join(p[0] for p in pairs)
                    out.append(f"enum class {enum_name} {{ {members_str} }};")
                    self._enums.append(
                        _EnumInfo(f"{parent_path}::{enum_name}", pairs))
                    cpp_members.append(enum_name)
                    type_checks.append(("is_string()", enum_name))
                    enum_emitted = True
                # Skip subsequent enum members — values already merged.
            elif mt in _TYPE_CHECK_MAP:
                check, cpp_t = _TYPE_CHECK_MAP[mt]
                cpp_members.append(cpp_t)
                type_checks.append((check, cpp_t))

        # Dispatch enum from discriminator values (struct members only)
        raw_entries: list[tuple[str, str]] = []
        for m in members:
            dv = m.get("discriminator_value")
            if dv and m.get("type") == "struct":
                raw_entries.append((dv, m["ref"]))
            elif m.get("type") == "struct" and not dv:
                # Struct without discriminator — use is_object() type check.
                type_checks.append(("is_object()", f"{parent_path}::{m['ref']}"))

        # Deduplicate variant members (preserving order).
        seen_m: set[str] = set()
        deduped: list[str] = []
        for m in cpp_members:
            if m not in seen_m:
                seen_m.add(m)
                deduped.append(m)
        variant_args = ", ".join(deduped)
        concrete_variant = f"std::variant<{variant_args}>"
        # Build a fully-qualified variant type key for dedup.  Expand
        # alias names back to concrete types so different aliases of
        # the same underlying type correctly dedup.
        concrete_deduped = [_alias_to_concrete.get(m, m) for m in deduped]
        fq_members = [_qualify_cpp_type(m, parent_path) for m in concrete_deduped]
        fq_variant_key = f"std::variant<{', '.join(fq_members)}>"

        if raw_entries:
            entries = _build_dispatch_entries(raw_entries)
            de_name = f"{union_name}Kind"
            de_members = ", ".join(em for em, _, _ in entries)
            out.append(f"enum class {de_name} {{ {de_members} }};")
            self._dispatches.append(
                _DispatchInfo(f"{parent_path}::{de_name}", entries,
                              discriminator or "type",
                              type_checks,
                              variant_type=fq_variant_key)
            )
        elif type_checks:
            # Type-only dispatch (no struct discriminators).
            self._dispatches.append(
                _DispatchInfo(f"{parent_path}::{union_name}", [],
                              discriminator or "type",
                              type_checks,
                              variant_type=fq_variant_key)
            )

        out.append(f"using {union_name} = {concrete_variant};")
        return union_name

    @staticmethod
    def _resolve_union_members(members_json: list[dict]) -> list[str]:
        """Map union member descriptors to C++ type strings."""
        out: list[str] = []
        for m in members_json:
            mt = m.get("type", "")
            if mt == "string":
                out.append("std::string")
            elif mt == "struct":
                out.append(m.get("ref", "UNKNOWN"))
            elif mt == "array":
                elem = _resolve_array_element_cpp(m)
                out.append(f"std::vector<{elem}>")
            elif mt == "boolean":
                out.append("bool")
            elif mt == "number":
                out.append("double")
            elif mt == "integer":
                out.append("int64_t")
            elif mt in ("object", "unknown"):
                out.append("jai::llm::json::Object")
            elif mt == "enum":
                # Enum member — the caller will emit the enum class
                # and replace this with the actual enum type name.
                out.append(f"__ENUM__")
            else:
                out.append(f"/* unhandled union member: {mt} */")
        return out

    # ── field resolution ──────────────────────────────────────────────────

    def _resolve_fields(
        self,
        fields_json: list[dict],
        child_names: set[str],
        parent_path: str,
        *,
        map_value_aliases: dict[str, str] | None = None,
    ) -> list[_FieldInfo]:
        out: list[_FieldInfo] = []
        for fld in fields_json:
            fname = fld["name"]
            cname = _escape(fname)
            req = fld.get("required", False)
            ftype = fld.get("type", "")

            cpp_type, is_kind, is_enum, is_union = self._resolve_type(
                fld, child_names,
                map_value_aliases=map_value_aliases,
            )

            out.append(_FieldInfo(
                fname, cname, cpp_type, req,
                is_kind=is_kind, is_enum=is_enum, is_union=is_union,
            ))
        return out

    def _resolve_type(
        self, fld: dict, child_names: set[str],
        *, map_value_aliases: dict[str, str] | None = None,
    ) -> tuple[str, bool, bool, bool]:
        """Return (cpp_type, is_kind, is_enum, is_union).

        No heuristics — every type must resolve via one of:
          1. Primitive type keywords
          2. ``"kind"`` / ``"enum"`` / ``"union"`` field types
          3. ``array<T>`` wrapper
          4. Child struct name
          5. ``union_def`` on the field (parser-generated)
          6. ``"Model"`` alias → ``std::string``
        Anything else is flagged with a ``/* UNRESOLVED */`` comment.
        """
        ftype = fld.get("type", "")
        fname = fld.get("name", "")
        udef = fld.get("union_def")

        # ── kind ──
        if ftype == "kind":
            if fname == "type":
                return "TypeKind", True, False, False
            return f"{_pascal(fname)}Kind", True, False, False

        # ── enum ──
        if ftype == "enum":
            return _pascal(fname), False, True, False

        # ── union ──
        if ftype == "union":
            return _pascal(fname), False, False, True

        # ── scalars ──
        if ftype == "string":
            return "std::string", False, False, False
        if ftype == "boolean":
            return "bool", False, False, False
        if ftype == "integer":
            return "int64_t", False, False, False
        if ftype == "number":
            return "double", False, False, False
        if ftype in ("object", "unknown", "map<string, unknown>"):
            return "jai::llm::json::Object", False, False, False

        # ── map<string, T> ──
        m = re.match(r"^map<string,\s*(.+)>$", ftype)
        if m:
            # If _build_usings already emitted a named alias for this map's
            # value type, reference it instead of inlining the variant.
            alias = (map_value_aliases or {}).get(fname)
            if alias:
                return f"std::map<std::string, {alias}>", False, False, False
            inner = m.group(1).strip()
            val_type = self._resolve_map_value(inner, child_names)
            return f"std::map<std::string, {val_type}>", False, False, False

        # ── array<T> ──
        m = re.match(r"^array<(.+)>$", ftype)
        if m:
            # If the parser recorded element_enum_values, the element
            # type is the enum class emitted in step ③b.
            if fld.get("element_enum_values"):
                ename = _pascal(fname) + "Item"
                return f"std::vector<{ename}>", False, False, False
            inner = m.group(1).strip()
            elem = self._resolve_element(inner, child_names, fld)
            return f"std::vector<{elem}>", False, False, False

        # ── named struct reference ──
        if ftype in child_names:
            return ftype, False, False, False

        # ── union_def present → the using alias was already emitted ──
        if udef:
            members = udef.get("members", [])
            non_literal = [mm for mm in members if mm.get("type") != "literal"]
            has_literals = any(mm.get("type") == "literal" for mm in members)
            # Count effective arms: non-literals + (1 if any literals → enum)
            effective_count = len(non_literal) + (1 if has_literals else 0)
            if effective_count >= 2:
                # Variant was emitted by _build_usings
                return udef["name"], False, False, True
            if effective_count == 1 and has_literals and not non_literal:
                # Pure enum class emitted by _build_usings
                return udef["name"], False, False, False
            if effective_count == 1 and non_literal:
                # Single non-literal member — resolve directly
                single = non_literal[0]
                st = single.get("type", "")
                if st == "struct":
                    return single.get("ref", ftype), False, False, False
                if st in self._SCALAR_MAP:
                    return self._SCALAR_MAP[st], False, False, False

        # ── UNRESOLVED — flag clearly, never guess ──
        return f"std::string /* UNRESOLVED: {ftype} */", False, False, False

    _SCALAR_MAP: dict[str, str] = {
        "string": "std::string",
        "boolean": "bool",
        "integer": "int64_t",
        "number": "double",
        "object": "jai::llm::json::Object",
        "unknown": "jai::llm::json::Object",
    }

    def _resolve_scalar(self, t: str) -> str | None:
        """Resolve a scalar type name to its C++ type, or None."""
        return self._SCALAR_MAP.get(t)

    def _resolve_map_value(self, inner: str, child_names: set[str]) -> str:
        """Resolve the value type of a map<string, V>.

        Handles scalars, named types, unknown, and union value types
        (e.g. ``string | number | boolean``).
        """
        # Simple scalar
        s = self._resolve_scalar(inner)
        if s:
            return s

        # Union value type: string | number | boolean
        if ' | ' in inner:
            parts = [p.strip() for p in inner.split(' | ')]
            cpp_parts: list[str] = []
            for p in parts:
                resolved = self._resolve_scalar(p)
                if resolved:
                    cpp_parts.append(resolved)
                elif p in child_names:
                    cpp_parts.append(p)
                else:
                    cpp_parts.append(f"std::string /* UNRESOLVED: {p} */")
            return f"std::variant<{', '.join(cpp_parts)}>"

        # Named type reference
        if inner in child_names:
            return inner

        return f"std::string /* UNRESOLVED: {inner} */"

    def _resolve_element(self, inner: str, child_names: set[str],
                         fld: dict | None = None) -> str:
        """Resolve the element type of an array."""
        s = self._resolve_scalar(inner)
        if s:
            return s
        if inner == "map<string, unknown>":
            return "jai::llm::json::Object"
        if inner in child_names:
            return inner
        # Check if a union_def was emitted for this name
        udef = fld.get("union_def") if fld else None
        if udef and udef.get("name") == inner:
            return inner
        # map<string, T> inside array
        m = re.match(r"^map<string,\s*(.+)>$", inner)
        if m:
            val_type = self._resolve_map_value(m.group(1).strip(), child_names)
            return f"std::map<std::string, {val_type}>"
        return f"{inner} /* UNRESOLVED */"

    # ── field declaration ─────────────────────────────────────────────────

    @staticmethod
    def _field_decl(fi: _FieldInfo) -> str:
        if fi.is_kind:
            # Kind fields get default-initialised
            if fi.required:
                return f"Required<{fi.cpp_type}> {fi.cpp_name}{{{{}}}};"
            return f"std::optional<{fi.cpp_type}> {fi.cpp_name}{{}};"
        if fi.required:
            return f"Required<{fi.cpp_type}> {fi.cpp_name};"
        return f"std::optional<{fi.cpp_type}> {fi.cpp_name}{{}};"

    # =====================================================================
    #  STRINGS  (strings.hpp)
    # =====================================================================

    def emit_strings(self) -> str:
        ns = self.provider  # "anthropic"
        parts: list[str] = [
            _GENERATED_BANNER +
            "#pragma once\n\n"
            '#include "../../core/strings_base.hpp"\n'
            '#include "../../core/error.hpp"\n'
            f'#include "{self.endpoint}.hpp"\n\n'
            "namespace jai::llm {\n\n"
            "// ── from_string_view: Kinds ──────────────────────────────\n"
        ]

        for ki in self._kinds:
            fq = f"{ns}::{ki.qualified}"
            parts.append(
                f"template <>\n"
                f"constexpr std::optional<{fq}>\n"
                f"from_string_view<{fq}>(std::string_view sv) {{\n"
                f"    if (sv == {fq}::value) return {fq}{{}};\n"
                f"    return std::nullopt;\n"
                f"}}\n"
            )

        parts.append("\n// ── from_string_view / to_string_view: Enums ──────────\n")

        for ei in self._enums:
            fq = f"{ns}::{ei.qualified}"
            # from_string_view
            parts.append(
                f"template <>\n"
                f"constexpr std::optional<{fq}>\n"
                f"from_string_view<{fq}>(std::string_view sv) {{\n"
            )
            for upper, orig in ei.pairs:
                parts.append(f'    if (sv == "{orig}") return {fq}::{upper};\n')
            parts.append("    return std::nullopt;\n}\n\n")

            # to_string_view
            parts.append(f"constexpr std::string_view to_string_view({fq} val) {{\n")
            parts.append("    switch (val) {\n")
            for upper, orig in ei.pairs:
                parts.append(f'        case {fq}::{upper}: return "{orig}";\n')
            parts.append(
                f'        default: throw AnnotatedException{{"invalid {fq}"}};\n'
                f"    }}\n}}\n\n"
            )

        parts.append("// ── from_string_view / to_string_view: Dispatch Enums ─\n")

        for di in self._dispatches:
            # Type-only dispatches have no enum — skip string conversions.
            if not di.entries:
                continue

            fq = f"{ns}::{di.qualified}"

            # Emit from_string_view — when duplicate kind_values exist
            # (multiple enum members mapping to the same string), emit only
            # the first mapping so the function remains unambiguous.
            parts.append(
                f"template <>\n"
                f"constexpr std::optional<{fq}>\n"
                f"from_string_view<{fq}>(std::string_view sv) {{\n"
            )
            seen_kv: set[str] = set()
            for em, kv, _ in di.entries:
                if kv not in seen_kv:
                    seen_kv.add(kv)
                    parts.append(
                        f'    if (sv == "{kv}") return {fq}::{em};\n'
                    )
            parts.append("    return std::nullopt;\n}\n\n")

            # to_string_view
            parts.append(f"constexpr std::string_view to_string_view({fq} val) {{\n")
            parts.append("    switch (val) {\n")
            for em, kv, _ in di.entries:
                parts.append(
                    f'        case {fq}::{em}: return "{kv}";\n'
                )
            parts.append(
                f'        default: throw AnnotatedException{{"invalid {fq}"}};\n'
                f"    }}\n}}\n\n"
            )

        parts.append("} // namespace jai::llm\n")
        return "".join(parts)

    # =====================================================================
    #  SERIALIZER  (serialize.cpp)  — request-side only
    # =====================================================================

    def emit_serializer(self) -> str:
        ns = self.provider
        req_name = self.request_root["name"] if self.request_root else "Request"
        iface = f"../../../interface/protocols/{ns}"
        parts: list[str] = [
            _GENERATED_BANNER +
            f'#include "{iface}/{self.endpoint}.hpp"\n'
            f'#include "{iface}/{self.endpoint}_strings.hpp"\n'
            f'#include "base.hpp"\n\n'
            f"using namespace simdjson::builder;\n\n"
            f"namespace jai::llm::{ns} {{\n\n"
        ]

        for rec in self._req_structs:
            parts.append(self._serialize_block(rec))
            parts.append("\n\n")

        # Top-level Serialize function
        parts.append(
            f"/***\n"
            f" * Top-level Serialize\n"
            f" */\n"
            f"std::vector<std::byte> Serialize(const {req_name}& request) {{\n"
            f"    static thread_local string_builder builder{{}};\n"
            f"\n"
            f"    try {{\n"
            f"        builder.clear();\n"
            f"        SerializeFrom(builder, request);\n"
            f"\n"
            f"        if (!builder.validate_unicode()) {{\n"
            f'            throw AnnotatedException{{"Serialize Failed", "string_builder generated invalid unicode data."}};\n'
            f"        }}\n"
            f"\n"
            f"        auto result = builder.view();\n"
            f"        if (result.error() != simdjson::SUCCESS) {{\n"
            f'            throw AnnotatedException{{"Serialize Failed", simdjson::error_message(result.error())}};\n'
            f"        }}\n"
            f"        std::string_view json_str = result.value();\n"
            f"\n"
            f"        return json_str |\n"
            f"               std::views::transform([](auto const& c) {{ return static_cast<std::byte>(c); }}) |\n"
            f"               std::ranges::to<std::vector<std::byte>>();\n"
            f"    }} catch (AnnotatedException const&) {{\n"
            f"        throw;\n"
            f"    }} catch (std::exception const& e) {{\n"
            f'        AnnotatedException ex{{"Serialize Failed"}};\n'
            f"        ex.AddContext(e.what());\n"
            f"        throw ex;\n"
            f"    }}\n"
            f"}}\n\n"
        )

        parts.append(f"}} // namespace jai::llm::{ns}\n")
        return "".join(parts)

    def _serialize_block(self, rec: _StructRecord) -> str:
        macro = "BEGIN_SERIALIZE_EMPTY" if not rec.fields else "BEGIN_SERIALIZE"
        lines = [f"{macro}({rec.qualified})"]
        for i, fi in enumerate(rec.fields):
            cd = "NONE" if i == 0 else "BEFORE"
            if fi.cpp_name != fi.json_name:
                lines.append(
                    f'    FIELD_ALT(obj, {fi.cpp_name}, "{fi.json_name}", '
                    f"CommaDirection::{cd})"
                )
            else:
                lines.append(
                    f"    FIELD(obj, {fi.cpp_name}, CommaDirection::{cd})"
                )
        lines.append("END_SERIALIZE")
        return "\n".join(lines)

    # =====================================================================
    #  DESERIALIZER  (deserialize.cpp)  — response-side only
    # =====================================================================

    def emit_deserializer(self) -> str:
        ns = self.provider
        resp_name = self.response_root["name"] if self.response_root else "Response"
        iface = f"../../../interface/protocols/{ns}"
        parts: list[str] = [
            _GENERATED_BANNER +
            f'#include "{iface}/{self.endpoint}.hpp"\n'
            f'#include "{iface}/{self.endpoint}_strings.hpp"\n'
            f'#include "base.hpp"\n'
            f'#include "../../curl.hpp"\n\n'
            f"namespace jai::llm {{\n\n"
        ]

        # First emit BEGIN_DESERIALIZE for all plain structs,
        # then emit variant blocks.
        for rec in self._resp_structs:
            if not rec.fields:
                continue
            parts.append(self._deserialize_block(rec))
            parts.append("\n\n")

        # Variant blocks for dispatch enums on the response side.
        # Multiple aliases can resolve to the same concrete variant type —
        # only emit one DESERIALIZE_VARIANT per concrete type.
        emitted_variant_types: set[str] = set()
        for di in self._dispatches:
            # Only emit for response-side dispatches
            if not self._is_response_path(di.qualified):
                continue
            if di.variant_type and di.variant_type in emitted_variant_types:
                continue
            if di.variant_type:
                emitted_variant_types.add(di.variant_type)
            parts.append(self._variant_block(di))
            parts.append("\n\n")

        # Variant blocks for map value aliases (e.g. AttributesValue,
        # VariablesValue).  These need DeserializeTo specializations so the
        # generic map deserializer can call DeserializeTo<V> on each value.
        # Dedup against the same emitted_variant_types set since C++
        # template specializations see through using aliases.
        for qalias, minfo, concrete in self._map_value_variants:
            if not self._is_response_path(qalias):
                continue
            if concrete in emitted_variant_types:
                continue
            emitted_variant_types.add(concrete)
            parts.append(self._map_value_variant_block(qalias, minfo))
            parts.append("\n\n")

        # Top-level Deserialize function
        parts.append(
            f"/***\n"
            f" * Top-level Deserialize\n"
            f" */\n"
            f"namespace {ns} {{\n"
            f"    {resp_name} Deserialize(const curl::Response& response) {{\n"
            f"        if (response.body.size() < response.body_len + simdjson::SIMDJSON_PADDING) {{\n"
            f'            throw AnnotatedException{{"Simdjson padding check failed"}};\n'
            f"        }}\n"
            f"\n"
            f"        static thread_local simdjson::dom::parser parser{{}};\n"
            f"\n"
            f"        try {{\n"
            f"            simdjson::dom::element doc = parser.parse(\n"
            f"                reinterpret_cast<const char*>(response.body.data()), response.body_len);\n"
            f"            return DeserializeTo<{resp_name}>(doc);\n"
            f"        }} catch (const simdjson::simdjson_error& e) {{\n"
            f'            throw AnnotatedException{{"{ns}::Deserialize Failed", e.what()}};\n'
            f"        }}\n"
            f"    }}\n"
            f"}}\n\n"
        )

        parts.append("} // namespace jai::llm\n")
        return "".join(parts)

    def _is_response_path(self, qpath: str) -> bool:
        """Check if a qualified path belongs to the response tree."""
        return any(
            qpath.startswith(r.qualified) for r in self._resp_structs
        )

    def _deserialize_block(self, rec: _StructRecord) -> str:
        fq = f"{self.provider}::{rec.qualified}"
        lines = [f"BEGIN_DESERIALIZE({fq})"]
        for i, fi in enumerate(rec.fields):
            comma = "," if i < len(rec.fields) - 1 else ""
            if fi.cpp_name != fi.json_name:
                lines.append(
                    f'    FIELD_ALT(src, {fi.cpp_name}, "{fi.json_name}"){comma}'
                )
            else:
                lines.append(f"    FIELD(src, {fi.cpp_name}){comma}")
        lines.append("END_DESERIALIZE")
        return "\n".join(lines)

    def _variant_block(self, di: _DispatchInfo) -> str:
        """Emit BEGIN_DESERIALIZE_VARIANT block for a dispatch enum."""
        ns = self.provider

        if di.entries:
            variant_alias = di.qualified.rsplit("Kind", 1)[0]
            fq_variant = f"{ns}::{variant_alias}"
            fq_dispatch = f"{ns}::{di.qualified}"
        else:
            variant_alias = di.qualified
            fq_variant = f"{ns}::{variant_alias}"
            fq_dispatch = f"{ns}::{di.qualified}"

        lines = [f"BEGIN_DESERIALIZE_VARIANT({fq_variant})"]

        # Non-struct members are dispatched by JSON value type before
        # falling through to the discriminator-based struct dispatch.
        # Parent path for qualifying sibling types at the same struct scope.
        # e.g. for "Request::ImageGeneration::Model" → parent is
        # "Request::ImageGeneration" so ModelValues → openai::Request::ImageGeneration::ModelValues
        parent_path = "::".join(variant_alias.split("::")[:-1])

        for json_check, cpp_type in di.type_checks:
            # Qualify custom types with the provider namespace.
            # e.g. std::vector<Response::Foo> → std::vector<anthropic::Response::Foo>
            fq_cpp_type = cpp_type
            if "std::vector<" in cpp_type and not cpp_type.startswith("std::vector<std::"):
                inner = cpp_type[len("std::vector<"):-1]
                # Qualify the inner type using the same sibling logic:
                # unqualified names are siblings at the parent scope.
                if parent_path and "::" not in inner:
                    fq_cpp_type = f"std::vector<{ns}::{parent_path}::{inner}>"
                else:
                    fq_cpp_type = f"std::vector<{ns}::{inner}>"
            elif cpp_type not in ("std::string", "bool", "double", "int64_t") \
                    and not cpp_type.startswith("std::") \
                    and not cpp_type.startswith("jai::"):
                # If the type is a sibling at the same struct scope (e.g.
                # enum class ModelValues emitted alongside using Model),
                # qualify relative to the parent struct path.
                if parent_path and "::" not in cpp_type:
                    fq_cpp_type = f"{ns}::{parent_path}::{cpp_type}"
                else:
                    fq_cpp_type = f"{ns}::{cpp_type}"
            lines.append(f"    if (src.{json_check}) {{")
            lines.append(f"        return T{{DeserializeTo<{fq_cpp_type}>(src)}};")
            lines.append(f"    }}")

        if di.entries:
            lines.append(
                f'    auto kind = EXTRACT_KIND({fq_dispatch}, src, "{di.discriminator_field}");'
            )
            for em, kv, member_type in di.entries:
                # member_type is a child struct name — qualify relative to parent
                parent_path = "::".join(di.qualified.split("::")[:-1])
                fq_member = f"{ns}::{parent_path}::{member_type}"
                lines.append(
                    f"    FIELD_KIND(src, kind, {fq_dispatch}::{em}, {fq_member})"
                )
        lines.append(f"END_DESERIALIZE_VARIANT({fq_variant})")
        return "\n".join(lines)

    def _map_value_variant_block(
        self, qalias: str, member_info: list[tuple[str, str, str]],
    ) -> str:
        """Emit DeserializeTo for a map-value variant alias.

        *member_info* entries are either:
          ("scalar", json_check, cpp_type) — dispatch by JSON value type
          ("struct", kind_value, child_name) — dispatch by kind discriminator
        """
        ns = self.provider
        fq = f"{ns}::{qalias}"

        # Separate scalar and struct members.
        scalars = [(check, ctype) for tag, check, ctype in member_info
                   if tag == "scalar"]
        structs = [(kv, cname) for tag, kv, cname in member_info
                   if tag == "struct"]

        # Parent path for qualifying child struct names.
        parent_path = "::".join(qalias.split("::")[:-1])

        lines = [f"BEGIN_DESERIALIZE_VARIANT({fq})"]

        # Emit scalar type checks first.
        for json_check, cpp_type in scalars:
            lines.append(f"    if (src.{json_check}) {{")
            lines.append(f"        return T{{DeserializeTo<{cpp_type}>(src)}};")
            lines.append(f"    }}")

        # Emit struct dispatch via kind discriminator.
        if structs:
            kind_bearing = [(kv, cn) for kv, cn in structs if kv]
            if kind_bearing:
                # Use kind-based dispatch (same as FIELD_KIND pattern).
                lines.append(f'    if (src.is_object()) {{')
                lines.append(f'        auto type_sv = src.get_object()["type"].get_string().value();')
                for kind_val, child_name in kind_bearing:
                    fq_child = f"{ns}::{parent_path}::{child_name}"
                    lines.append(f'        if (type_sv == "{kind_val}") {{')
                    lines.append(f"            return T{{DeserializeTo<{fq_child}>(src)}};")
                    lines.append(f"        }}")
                lines.append(f"    }}")
            else:
                # No kind discriminator — fall back to positional.
                for _, child_name in structs:
                    fq_child = f"{ns}::{parent_path}::{child_name}"
                    lines.append(f"    if (src.is_object()) {{")
                    lines.append(f"        return T{{DeserializeTo<{fq_child}>(src)}};")
                    lines.append(f"    }}")

        lines.append(f"END_DESERIALIZE_VARIANT({fq})")
        return "\n".join(lines)


# ─── Public entry point ──────────────────────────────────────────────────────

def generate(provider: str) -> Path:
    """Generate C++ from intermediate JSON for *provider*.

    Returns the output directory path.
    """
    json_path = config.extracted_json_path(provider)
    if not json_path.exists():
        raise FileNotFoundError(
            f"Extracted JSON not found: {json_path}\n"
            f"Run 'extract --provider {provider}' first."
        )

    print(f"Loading {json_path}")
    spec = json.loads(json_path.read_text(encoding="utf-8"))

    endpoint = config.ENDPOINTS[provider].endpoint
    gen = CppCodegen(spec, provider, endpoint)
    out = gen.run()

    # Summary
    print(f"Generated C++ in {out}/")
    print(f"  Kinds:          {len(gen._kinds)}")
    print(f"  Enums:          {len(gen._enums)}")
    print(f"  Dispatch enums: {len(gen._dispatches)}")
    print(f"  Request structs:  {len(gen._req_structs)}")
    print(f"  Response structs: {len(gen._resp_structs)}")

    return out
